### ISSUE TITLE
Driver and filtering not working in results

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#1018]
Driver not showing and filtering not working

Support info:
http://www.virtualflybrain.org/do/individual_list.html?action=exemplar_neuron&id=FBbt:00110461
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36 Size:[2505,945]
!M56-0.1!e2eZ!e8e-12!M1511,255,108!e1e!B Template!11!j1!F327!4e!L047054!4L!6225!L24t!6synaptic neuropil domain!12!I316208!4N!6!o4!F3177!4t!O1L313!j1!F47!4e!L047053!4L!6187!L24t!6synaptic neuropil domain!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

![driver](https://cloud.githubusercontent.com/assets/1872083/20797576/492f44fc-b7d3-11e6-835e-ba67d880b87c.png)

**Comment by Robbie1977** [comment]
@dosumis do we have a driver as the description immediately hints to there being nothing there?

**Comment by Robbie1977** [comment]
@mmc46 if you sort by driver there are some that have one, I assume you're expecting one. What are you seeing with the filtering?

**Comment by mmc46** [comment]
For the driver: yes, you're probably right. 
For the filtering: just nothing happens

**Comment by Robbie1977** [comment]
@mmc46 this issue seems to be 'fru' exists in either the description or name for all rows

**Comment by mmc46** [comment]
Ok, I thought it would only filter on the name.

**Comment by dosumis** [comment]
A believe these are backfills from e-phys experiments in this paper: https://www.ncbi.nlm.nih.gov/pubmed/24360281

So the expression shown is not from a driver - hence no driver shown.

The new def gen code should have coped with the absence of a driver.  Need to check why it didn't.

**Comment by Robbie1977** [comment]
Has now been updated on http://vfbsandbox.inf.ed.ac.uk/ 
@mmc46 if you get a sec check you're happy and I can start deploying

**Comment by mmc46** [comment]
No example images showing up on 

http://vfbsandbox.inf.ed.ac.uk/

**Comment by Robbie1977** [comment]
Have you got an example as seems to be working my end?

**Comment by mmc46** [comment]
http://vfbsandbox.inf.ed.ac.uk/site/stacks/index.htm?id=FBbt_00110461 <http://vfbsandbox.inf.ed.ac.uk/site/stacks/index.htm?id=FBbt_00110461>

**Comment by Robbie1977** [comment]
Sorry can you send me a screen cap as seeing 22 examples

**Comment by mmc46** [comment]
![asp-g](https://cloud.githubusercontent.com/assets/1872083/20839546/fe0e65f2-b8a4-11e6-8dec-71dd5da7b2ba.png)

Referring page: http://vfbsandbox.inf.ed.ac.uk/site/stacks/index.htm
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36 Size:[2030,937]
LocalData: !M56-0.1!e2eZ!e8e0!M1511,255,108!E!B Template!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!4N!6Janelia Adult Brain Template!4t!6<a href=\"http://www.flybase.net/reports/FBgn0259246.html\" target=\"_new\">Nc82</a>!G!P3!0

**Comment by mmc46** [comment]
It's woking on the mains site.
There's something funny in dev with `Janelia Adult Brain Template!4t!6<a href="http://www.flybase.net/reports/FBgn0259246.html\" target="_new">Nc82!G!P3!0`

From main:
Referring page: http://www.virtualflybrain.org/site/stacks/index.htm
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36 Size:[2368,951]
LocalData: !M56-0.1!e2eZ!e8e-12!M1511,255,108!e1e!B Template!11!j1!F327!4e!L047054!4L!6225!L24t!6synaptic neuropil domain!12!I316208!4N!6!o4!F3177!4t!O1L313!j1!F47!4e!L047053!4L!6187!L24t!6synaptic neuropil domain!14!j1!F311!4e!L043982!4L!6253!L24t!6synaptic neuropil domain!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0
