### ISSUE TITLE
Term info not displaying anything

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#1024]
From any search,or clicking on viewer menu (class for example) the term info doesn't display anything.

http://www.virtualflybrain.org/site/stacks/index.htm?id=FBbt_00110414

I'm on Chrome/54.0.2840.98
![screen shot 2016-12-07 at 16 43 58](https://cloud.githubusercontent.com/assets/1872083/20977115/61fd5730-bc9c-11e6-9fb3-e2c5b993f696.png)

Support info:
http://www.virtualflybrain.org/site/stacks/index.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36 Size:[2282,912]
!M56-0.1!e2eZ!e8e-12!M1511,255,108!e1e!B Template!11!j1!F327!4e!L047054!4L!6225!L24t!6synaptic neuropil domain!12!j1!F47!4e!L047053!4L!6187!L24t!6synaptic neuropil domain!13!j1!F311!4e!L043982!4L!6253!L24t!6synaptic neuropil domain!14!I44688!4N!o1200139!4t!O3aDT-b!O54I!K2110417!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by Robbie1977** [comment]
Fixed

**Comment by Robbie1977** [comment]
Jenkins is now checking for any ontology server failures https://karenin.inf.ed.ac.uk:8079/job/check%20ontology%20server/
