### ISSUE TITLE
Huge thumbnails for half brain domains

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#1062]
It's great that tract images are showing up in results, but the thumbnails are a bit huge:

e.g. 

![image](https://cloud.githubusercontent.com/assets/112839/22506574/1c967704-e879-11e6-9991-c3f53bead944.png)

http://www.virtualflybrain.org/do/ont_bean_list.html?action=tract&id=FBbt:00003924

Can they be made smaller?

**Comment by Robbie1977** [comment]
I'll look at adding the restrictions on image size more flexibly as currently sets width

**Comment by Robbie1977** [comment]
Having looked again I remember how problematic this is aligning the labels and buttons without a fixed width. Will think this one over.

**Comment by Robbie1977** [comment]
Resolved in http://vfbsandbox.inf.ed.ac.uk/do/ont_bean_list.html?action=tract&id=FBbt:00003924
