### ISSUE TITLE
Improve query results text for fasciculating neurons

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#1063]
![image](https://cloud.githubusercontent.com/assets/112839/22507197/540b6ab6-e87c-11e6-9513-c23451f2860c.png)

Neuron fasiculating X -> Neurons fasciculating in (the) X

**Comment by Robbie1977** [comment]
Resolved in http://vfbsandbox.inf.ed.ac.uk/do/ont_bean_list.html?action=fasciculate&id=FBbt:00100357
