### ISSUE TITLE
Image data links need resolving: Matsuo and Kohl

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#1086]
The links in

http://www.virtualflybrain.org/site/vfb_site/image_data_downloads.htm

for the Matsuo and Kohl datasets need editing to point to something.
`<p>JFRC2 registered images of fruitless neurons of the aSP-f, aSP-g and aSP-h types are provided <a href="" `target="_blank">here</a>.</p>`

`<p>JFRC2 registered images of auditory neurons are provided <a href="" target="_blank">here</a>.</p>`

**Comment by the-dude-man** [comment]
Hi Rob,
Didn’t talk for a while, hope you are doing well!

I’m going back now to some brains I aligned back in 2016.
I like to look at these brains in VFB, but I don’t remember how in the aligner do I move alignments from
“alignment done” to “available in VFB”.

For example – brain 20160525_MCFO2_SlideB1_B2_B3_B4_20X_Brain_B2402_PC2l

Also – once available in VFB – how do I find the VFB ID for this alignment?

Thanks!
Dudi



Dr. David (Dudi) Deutsch
Princeton Neuroscience institute
Office: 609-258-7341, Cell: 609-937-9488

**Comment by Robbie1977** [comment]
@the-dude-man Set stage to 'show in VFB' then it will cue for processing then once stage says 'available in VFB' see the Notes section as the ID gets put in there. Open with https://virtualflybrain.org/reports/VFB_00000001 (with your ID)

**Comment by Robbie1977** [comment]
@the-dude-man I take that back open with http://www.virtualflybrain.org/site/stacks/index.htm?add=VFBt_00100000,VFBa_XXXXXXXX with your id instead of the XX's. The previous link takes you the alignment itself.
