### ISSUE TITLE
Weirdness in autocomplete

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#1087]
This hangs for ever (or as long as my patience lasts) with the message 'no matches yet'

![image](https://cloud.githubusercontent.com/assets/112839/26196528/261f2d66-3bb7-11e7-9df6-b0b93c72d791.png)

But if I type AMMC first, then delete it, then try the original query again:

![image](https://cloud.githubusercontent.com/assets/112839/26196597/59ae1bb0-3bb7-11e7-8809-d5525af08227.png)

I assume this is because results from the first search are cached.

The query should work first time (and quickly).

**Comment by dosumis** [comment]
This doesn't seem to be down to tokenization on '-' in the first search.  Other autocomplete searches which have worked well before are also affected. e.g.

![image](https://cloud.githubusercontent.com/assets/112839/26197091/f9dd9754-3bb8-11e7-957a-2d54aca2b1e7.png)

I think this makes it a higher priority to fix, as this breaks most or all potential examples in the paper.

**Comment by Robbie1977** [comment]
SOLR server restarted and reloading

**Comment by Robbie1977** [comment]
Back Running

**Comment by dosumis** [comment]
Ta.  Looks good.
