### ISSUE TITLE
2D stack not loading in main site

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#1097]
Referring page: http://www.virtualflybrain.org/site/stacks/index.htm
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36 Size:[1974,939]
LocalData: !M56-0.1!e2eZ!e8e-37!M1511,255,108!E!H1!2S!20!2i!6!H1!F5!4v!7!P8!9N!6Janelia Adult Brain Template!G!C Template!4t!6<li>presynaptic ( n-syb-GFP, green )</li><li>postsynaptic ( GABA receptor targeted Rdl-HA receptor, blue )</li><li>cytoplasmic counter stains (Cytoplasmic DsRed, red)</li>!11!j2!F328!4e!L047055!4L!6230!L24t!6synaptic neuropil domain!G!H3!2S!20!2i!6!H3!F5!G!P3!0

Using Chrome

**Comment by Robbie1977** [comment]
Was it showing Main-Sever in the version strap at the bottom of the page?

**Comment by mmc46** [comment]
Main-Server - V2.4.1-1116-g0e4e791 [FB2016_05] [ http://purl.obolibrary.org/obo/fbbt/2016-08-17/fbbt-simple.owl ] [ http://purl.obolibrary.org/obo/fbbt/vfb/2016-12-02/vfb.owl ]

**Comment by Robbie1977** [comment]
@mmc46 I can't get any error to occur my end; what precisely are you seeing?

**Comment by mmc46** [comment]
The stack doesn’t load.

**Comment by Robbie1977** [comment]
what is the Z stack position?

**Comment by mmc46** [comment]
It happens at all Z positions. The stack doesn't ever show.
![no-stack](https://user-images.githubusercontent.com/1872083/29318369-9d88ca64-81c7-11e7-935b-804499e68254.png)

**Comment by Robbie1977** [comment]
@mmc46 if you get a chance can you open the chrome developer console window and copy the messages. Also scroll through the stack to see if it's trying to load the images at all.

**Comment by mmc46** [comment]
Console messages (Filter set to 'All levels')
```Initialising search...
wlziip.js:2372 [Violation] 'setInterval' handler took 365ms
wlziip.js:2372 [Violation] 'setInterval' handler took 422ms
wlziip.js:2372 [Violation] 'setInterval' handler took 376ms
wlziip.js:2372 [Violation] 'setInterval' handler took 340ms
wlziip.js:2372 [Violation] 'setInterval' handler took 384ms
stackManager.js:1727 Restarting animation...
wlziip.js:2372 [Violation] 'setInterval' handler took 364ms
wlziip.js:2372 [Violation] 'setInterval' handler took 357ms
[Violation] Forced reflow while executing JavaScript took 35ms
wlziip.js:2372 [Violation] 'setInterval' handler took 337ms
[Violation] Forced reflow while executing JavaScript took 32ms
wlziip.js:2372 [Violation] 'setInterval' handler took 367ms
[Violation] Forced reflow while executing JavaScript took 33ms
wlziip.js:2372 [Violation] 'setInterval' handler took 360ms
[Violation] Forced reflow while executing JavaScript took 31ms
wlziip.js:2372 [Violation] 'setInterval' handler took 339ms
wlziip.js:2372 [Violation] 'setInterval' handler took 446ms
wlziip.js:2372 [Violation] 'setInterval' handler took 386ms```

Scrolling z, network tab
![scrolling_z](https://user-images.githubusercontent.com/1872083/29354102-52364e2c-8264-11e7-9d61-2921ac4b8b9b.png)

**Comment by Robbie1977** [comment]
@mmc46 just to check is the visibility for template enabled in the display tab?

**Comment by Robbie1977** [comment]
just decoded the debug data in the initial report and yep: ```{"current":{"template":"VFBt_001","scl":"-0.1","mod":"zeta","slice":"Z","dst":-37,"pit":0,"yaw":0,"rol":0,"qlt":80,"cvt":"png","fxp":"511,255,108","alpha":220,"blend":"screen","inverted":false},"VFBt_001":{"selected":{"0":{"id":"VFBt_00100000","visible":false,"name":"Janelia Adult Brain Template"}}},"VFBt_002":{"selected":{"0":{"id":"VFBt_00200000","name":"Ito Half Brain Template","type":""},"1":{"id":"VFBd_00200028","extid":"FBbt_00007055","L":"230","typeid":"FBbt_00040007","type":"synaptic neuropil domain"}}},"VFBt_003":{"selected":{"0":{"id":"VFBt_00300000"}}},"VFBt_004":{"selected":{"0":{"id":"VFBt_00400000"}}}}```

```"visible":false```

So that is the cause.
