### ISSUE TITLE
Autocomplete not working well for VT lines

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#1106]
Searching for VT034811 in VFB1.5, no results show up, though it's available in

http://www.virtualflybrain.org/site/vfb_site/Dickson_VT.htm

and there are 4 stacks

VDRC_VT034811_GAL4_attP2_1 [VFB_00040615.nrrd]
VDRC_VT034811_GAL4_attP2_2 [VFB_00040616.nrrd]
VDRC_VT034811_LexAGAD_attP40_1 [VFB_00040617.nrrd]
VDRC_VT034811_LexAGAD_attP40_2 [VFB_00040618.nrrd]

with name 'VT034811'.

Support info:
http://www.virtualflybrain.org/site/vfb_site/home.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Size:[2133,912]
!M56-0.1!e2eZ!e8e0!M1511,255,108!e1e!B Template!11!I5323!4N!o2200319!4t!O3aDT-e (male) neuron!O9<span id=\"partParent\"><li>adult antennal lobe projection neuron DA1 lPN!O9!4I!K2110583!12!I348442!4N!6VDRC_VT065317_GAL4_attP2_1!4t!O8expression pattern!O9!4I!6caro_003!F32!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by Robbie1977** [comment]
Investigating if SOLR has correctly loaded these as not there and should be returned correctly

**Comment by Robbie1977** [comment]
Swapped to new servers - original one was using old VFB_ind owl hence wasn't picking up changes to vfb.owl
