### ISSUE TITLE
Reference to VT lines needs updating

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#1110]
This had been mentioned in October, on slack. Reference for VT lines should now be

https://www.biorxiv.org/content/early/2017/10/05/198648

Tirian and Dickson, 2017

It's still 

"Barry Dickson, personal communication

Kvon, E., Kazmar, T., Stampfel, G., Yáñez-Cuna, O., Pagani, M., Schernhuber, K., Dickson, B., and Stark, A. (2014). Genome-scale functional characterization of Drosophila developmental enhancers in vivo. Cah Rev The 512, 91-95."

on http://www.virtualflybrain.org/site/vfb_site/Dickson_VT.htm
and 

Support info:
http://www.virtualflybrain.org/site/vfb_site/Dickson_VT.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Size:[2297,941]
!M56-0.1!e2eZ!e8e0!M1511,255,108!E!B Template!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by dosumis** [comment]
Fixed in KB

![image](https://user-images.githubusercontent.com/112839/36167595-57bd26fe-10ee-11e8-8fc5-02297812b2f8.png)

Should be visible next time pipeline runs.

@Robbie1977 - Will having DOI only cause problems?

**Comment by Robbie1977** [comment]
Amended on VFB 1.5 also

**Comment by Robbie1977** [comment]
FYI DOI should be handled - in theory - will check.

Also I'll amend the ref in VFB 1.5 to doi
