### ISSUE TITLE
ontology linkouts from FB not working properly

### ISSUE THREAD

**Issue by ah963** [VirtualFlyBrain/VFB#1129]
E.g. when you click on the linkout at the bottom of this page http://flybase.org/cgi-bin/cvreport.pl?cvterm=FBbt:00005215&childdepth=2
which is
http://www.virtualflybrain.org/site/stacks/index.htm?add=FBbt_00005215
it takes you to
http://www.virtualflybrain.org/site/stacks/index.htm?id=FBbt_00003624

**Comment by Robbie1977** [comment]
Can you copy the tiny text at the bottom left of the page?

**Comment by ah963** [comment]
External Crossreferences & Linkouts
--
VFB:FBbt_00005215

  | VFB:FBbt_00005215


this from the FB page?

or this from the VFB page?


Main-Server - V2.4.1-1155-g9c68c73 [FB2017_06] [ http://purl.obolibrary.org/obo/fbbt/2017-09-06/fbbt-simple.owl ] [ http://purl.obolibrary.org/obo/fbbt/vfb/2017-07-13/vfb.owl ]

**Comment by Robbie1977** [comment]
Can't seem to replicate the issue as works for me: FlyBase links to http://www.virtualflybrain.org/search.htm?id=FBbt:00005215 which is the VFB1.0 link request format but this and all the formats above result in the correct term info page being loaded (eventually - few seconds occasionally). 

Perhaps we should also request these links are updated to use virtualflybrain.org/reports/$ID$

**Comment by Robbie1977** [comment]
Linking should be:
http://virtualflybrain.org/reports/$ID$
With $ID$ ideally being with _ but : is supposed

**Comment by ah963** [comment]
links will be updated in the next FlyBase release

**Comment by Robbie1977** [comment]
Are you still getting the error and if so can you replicate on another machine?

**Comment by ah963** [comment]
can't replicate the error on another machine, seems fixed on this one after a restart.
