### ISSUE TITLE
first demonstration video on youtube channel has nothing to do with VFB

### ISSUE THREAD

**Issue by ah963** [VirtualFlyBrain/VFB#1172]
https://www.youtube.com/channel/UC1g10aJo13fXpO9VwRJPdHg

**Comment by Robbie1977** [comment]
Removed!

@dosumis check your not still logged into VFB account on youtube!

**Comment by dosumis** [comment]
Oops - sorry.  That's a bit weird.  I thought google had universal login - I'm dosumis everywhere else.
