### ISSUE TITLE
Split-GAL4 descriptions only listing one side

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#1206]
Example:
```
P{R41C05-GAL4.DBD} ∩ P{R55C04-p65.AD} expression pattern
ID: VFBexp_FBtp0117218FBtp0117190

Definition: All the cells in some region of the body (e.g. adult brain, larval CNS) that express P{R55C04-p65.AD}.

Parent classes: 
intersectional expression pattern
Relationships: 
has hemidriver P{R55C04-p65.AD}
has hemidriver P{R41C05-GAL4.DBD}
```

Support info:
http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Size:[1920,951]
!M56-0.1!e2eZ!e8e-4!M1511,255,108!e1e!B Template!11!I320049!4N!6VLPl&p2!o3Yu!o93!L1350146!4t!O6VLPl&amp;p2!O712!I320408!4N!6GMR_38C04_AE_01_05-fA01b!4I!6VFBexp_FBtp0059827FBbt:!F43624!4t!O8P{GMR38C04-GAL4} expression pattern!O9<span id=\"partParent\"><li>adult brain!O9!13!I363849!4N!6JRC_OL0045B Split-GAL4 in the adult brain!4I!6VFBexp_FBtp0117218FBtp0117190!4t!O8P{R41C05-GAL4.DBD} ∩ P{R55C04-p65.AD} expression pattern!O9!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!4N!6Adult Ventral Nervous System Template!4t!6<a href=\"http://www.flybase.net/reports/FBgn0259246.html\" target=\"_new\">Nc82</a>!11!I363697!4N!6JRC_MB063B Split-GAL4 in the adult VNS!4t!O8P{R68C09-GAL4.DBD} ∩ P{R93D10-p65.AD} expression pattern!O9!4I!6FBtp0117254fbtp0117252!12!I363696!4N!6JRC_MB043C Split-GAL4 in the adult VNS!4t!O8P{R32D11-GAL4.DBD} ∩ PBac{R58E02-p65.AD} expression pattern!O9!4I!6VFBexp_FBtp0099478FBtp0099551!G!H5!2S!20!2i!6!H5!F5!4v!7!P8!9N!6L1 Larval CNS Template!4t!6<a href=\"http://www.flybase.org/reports/FBgn0259246.html\" target=\"_blank\">Nc82</a>\n                            !0

**Comment by dosumis** [comment]
Fixed in KB.  Still need to fix in loading code.

**Comment by dosumis** [comment]
Fixed in loading code: https://github.com/VirtualFlyBrain/VFB_neo4j/issues/114
