### ISSUE TITLE
Links to hemidrivers should link directly to FlyBase

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#1207]
P{R55F01-GAL4.DBD} ∩ P{R35D04-p65.AD} expression pattern
ID: VFBexp_FBtp0117222FBtp0117187

Definition: All the cells in some region of the body (e.g. adult brain, larval CNS) that express P{R55F01-GAL4.DBD}.

Parent classes: 
intersectional expression pattern
Relationships: 
has hemidriver P{R55F01-GAL4.DBD}
has hemidriver P{R35D04-p65.AD}

hemidrivers should link directly to FlyBase - they currently do not.

**Comment by dosumis** [comment]
Not fixed on http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?id=VFBexp_FBtp0117227FBtp0117189

Needs to be fixed before VFB 2019 01 release,

**Comment by dosumis** [comment]
Turns out this was due to incorrect IRIs on hemidrivers.  This has now been fixed in the KB.

**Comment by dosumis** [comment]
Fixed in code here: https://github.com/VirtualFlyBrain/VFB_neo4j/commit/fd12d8f111ee5a4fb7f60294aa17374a952a68c2

**Comment by Robbie1977** [comment]
Deployed to sandbox 3 and tested OK for examples in https://github.com/VirtualFlyBrain/VFB/issues/1208#issuecomment-462288243
