### ISSUE TITLE
Split images missing

### ISSUE THREAD

**Issue by ah963** [VirtualFlyBrain/VFB#1208]
Cant see split images or FBbt terms for expression, e.g. http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?id=VFB_00069081#details

Support info:
http://vfbsandbox3.inf.ed.ac.uk/site/vfb_site/home.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:63.0) Gecko/20100101 Firefox/63.0 Size:[2560,1416]
!M56-0.1!e2eZ!e8e0!M1511,255,108!e1e!B Template!11!I369081!4v!7!P8!9N!6JRC_MB299B Split-GAL4 in the adult VNS!4I!6VFBexp_FBtp0099181FBtp0099550!4t!O8P{R37E10-GAL4.DBD} ∩ P{R58E02-p65.AD} expression pattern!O9!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by ah963** [comment]
Also, there's no info for each hemidriver if you click on them
http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?id=FBtp0099181
http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?id=FBtp0099550

**Comment by Robbie1977** [comment]
I've tracked down the missing files seems to have been a copy error pushing everything to the loading pipeline again which will catch any missed files.

**Comment by dosumis** [comment]
> Also, there's no info for each hemidriver if you click on them
> http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?id=FBtp0099181
> http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?id=FBtp0099550

hemidriver bug ticket here:
https://github.com/VirtualFlyBrain/VFB/issues/1207

**Comment by Robbie1977** [comment]
All missing images loaded.
