### ISSUE TITLE
add male fruitless stacks

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#177]
Only female ones have been added, because we didn't have the male and female terms in the ontology at the time.
Now that we do (mmc46 to check it's all ok) add the stacks to the site, and to the image downloads.

**Comment by Robbie1977** [comment]
@dosumis can we start the ID's from VFB_00016227 as we have a massive gap or are we keeping this for anything? 
Tzumins data is the next at VFB_00020000

**Comment by dosumis** [comment]
Individuals for these are now in the OWL.  Have kept short names for now, but we should probably harmonise names with others from same dataset.  (Note - having serious doubts about sustainability of keeping long, descriptive names for individuals).

**Comment by Robbie1977** [comment]
Something the ontserver doesn't like:
uk.ac.ebi.brain.error.ClassExpressionException: org.semanticweb.owlapi.expression.ParserException: Encountered C888C3DB-AEFA-447F-BD4C-858DFE33DBE7 at line 1 column 62. Expected one of:
	Class name
	Object property name
	Data property name
	not
	inverse
	Self
	(
	{

	at uk.ac.ebi.brain.core.Brain.parseClassExpression(Brain.java:1215)
	at uk.ac.ebi.brain.core.Brain.getInstances(Brain.java:1746)
	at uk.ac.ed.vfb.dao.client_server.server_includes.DLQUeryEngineBrainInd.askQuery(DLQUeryEngineBrainInd.java:41)
	at uk.ac.ed.vfb.dao.client_server.server_includes.DLQueryServer.askQuery(DLQueryServer.java:94)
	at uk.ac.ed.vfb.dao.client_server.Server$ClientHandler.run(Server.java:151)
Caused by: org.semanticweb.owlapi.expression.ParserException: Encountered C888C3DB-AEFA-447F-BD4C-858DFE33DBE7 at line 1 column 62. Expected one of:
	Class name
	Object property name
	Data property name
	not
	inverse
	Self
	(
	{

	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.createException(ManchesterOWLSyntaxEditorParser.java:2772)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.parseObjectRestriction(ManchesterOWLSyntaxEditorParser.java:745)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.parseNonNaryClassExpression(ManchesterOWLSyntaxEditorParser.java:709)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.parseUnion(ManchesterOWLSyntaxEditorParser.java:625)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.parseIntersection(ManchesterOWLSyntaxEditorParser.java:603)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.parseClassExpression(ManchesterOWLSyntaxEditorParser.java:591)
	at uk.ac.ebi.brain.core.Brain.parseClassExpression(Brain.java:1213)
	... 4 more
java.lang.NullPointerException
	at uk.ac.ed.vfb.dao.client_server.server_includes.DLQUeryEngineBrainInd.askQuery(DLQUeryEngineBrainInd.java:47)
	at uk.ac.ed.vfb.dao.client_server.server_includes.DLQueryServer.askQuery(DLQueryServer.java:94)
	at uk.ac.ed.vfb.dao.client_server.Server$ClientHandler.run(Server.java:151)

**Comment by Robbie1977** [comment]
The new individuals OWL does seem odd as previously:
Declaration(Class(<http://flybase.org/reports/FBti0016783>))
AnnotationAssertion(rdfs:label <http://flybase.org/reports/FBti0016783> "P{GawB}GH146"^^xsd:string)
Declaration(Class(<http://flybase.org/reports/FBti0132502>))
AnnotationAssertion(rdfs:label <http://flybase.org/reports/FBti0132502> "P{GAL4}G0239"^^xsd:string)

Where as the new one has just Declaration - might be further on but seems odd:
Declaration(Class(<http://flybase.org/reports/FBti0016783>))
Declaration(Class(<http://flybase.org/reports/FBti0132502>))
Declaration(Class(<http://flybase.org/reports/FBti0143413>))

**Comment by Robbie1977** [comment]
@dosumis if you can give me a list of vfbIDs to the file names I can add them in ready.

**Comment by dosumis** [comment]
Looks like failure to merge in a support file. Could be an issue with shell
script arising from branch merge to master I did this aft. Will fix
tomorrow morning, and send mapping at same time.

**Comment by dosumis** [comment]
Found the problem.  While trying to fix the reasoning bug, I switched out shortFormIDs with leading digits - as I suspected one problem may be a bug in shortForm parsing.  Have updated individual build code to reflect this.  Rebuilding now.

BTW - the apparent difference in content you flagged is just a difference in line ordering.  The same axioms are in the new file - just not in the same place.

**Comment by dosumis** [comment]
Mapping here: https://gist.github.com/dosumis/410663ada7e1778f44ad

**Comment by dosumis** [comment]
Still problems with OWL gen.  Fixing now.

**Comment by Robbie1977** [comment]
Files added to new file system

**Comment by Robbie1977** [comment]
Definitely still not happy:
http://vfbsandbox.inf.ed.ac.uk/logs/

Files are all live on sandbox:
http://vfbsandbox.inf.ed.ac.uk/owl/VFBi_00017910/

**Comment by Robbie1977** [comment]
BTW Would rather solve #442 than add to VFB DB.

**Comment by dosumis** [comment]
Anything jump out from the logs?

**Comment by Robbie1977** [comment]
Have you forced the ontology server to restart - should auto restart when owl changed plus also worth restarting tomcat to be sure - all done from jenkins.
I'll check now.

**Comment by Robbie1977** [comment]
Going to replace the individuals with the Dev copy to check everything is working.

**Comment by Robbie1977** [comment]
Still giving a similar error
It updated and decompressed the individual owl file 19-Feb-2015 18:29:42

**Comment by Robbie1977** [comment]
The individuals file is working OK if deployed on jenkins think you must of had a merge issue.
There is a process to deploy it - could link automatically if you like?

**Comment by dosumis** [comment]
Deploy from Jenkins to Sandbox would be good.  But we need to work on the Jenkins shell script first.  Needs to be set up to return false if intermediate jobs fail.

**Comment by Robbie1977** [comment]
All ready just need to either add to VFB DB or bypass to owl - going to take a look at feasibility this weekend.
http://vfbsandbox.inf.ed.ac.uk/site/tools/view_stack/3rdPartyStack.htm?tpbid=VFB_00017893

**Comment by Robbie1977** [comment]
New individuals lacking some details:

Declaration(NamedIndividual(<http://vfbsandbox3.inf.ed.ac.uk/owl/VFB_00017893>))
AnnotationAssertion(Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "PMID:20832311"^^xsd:string) <http://purl.obolibrary.org/obo/IAO_0000115> <http://vfbsandbox3.inf.ed.ac.uk/owl/VFB_00017893> ""^^xsd:string)
AnnotationAssertion(rdfs:label <http://vfbsandbox3.inf.ed.ac.uk/owl/VFB_00017893> "aDT-b_M"^^xsd:string)
ClassAssertion(owl:Thing <http://vfbsandbox3.inf.ed.ac.uk/owl/VFB_00017893>)

Previous example:
Declaration(NamedIndividual(<http://vfbsandbox3.inf.ed.ac.uk/owl/VFB_00017892>))
AnnotationAssertion(Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "PMID:20832311"^^xsd:string) <http://purl.obolibrary.org/obo/IAO_0000115> <http://vfbsandbox3.inf.ed.ac.uk/owl/VFB_00017892> "An example of an adult fruitless aDT-a lineage clone in the adult brain"^^xsd:string)
AnnotationAssertion(rdfs:label <http://vfbsandbox3.inf.ed.ac.uk/owl/VFB_00017892> "aDT-a_M"^^xsd:string)
ClassAssertion(<http://purl.obolibrary.org/obo/FBbt_00110414> <http://vfbsandbox3.inf.ed.ac.uk/owl/VFB_00017892>)
ClassAssertion(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/FBbt_00003624>) <http://vfbsandbox3.inf.ed.ac.uk/owl/VFB_00017892>)
ClassAssertion(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/FBbt_00007004>) <http://vfbsandbox3.inf.ed.ac.uk/owl/VFB_00017892>)


No Definition for one plus is there no more data for them?

**Comment by Robbie1977** [comment]
@mmc46 do we have the FlyCircuit ids?

**Comment by dosumis** [comment]
Hi Robbie, I'll provide the FlyCircuit id mapping.  (roll on ditching the VFB postgres DB...)

**Comment by Robbie1977** [comment]
@dosumis Could we include the remote URI in the OWL?

**Comment by dosumis** [comment]
Scratch that these things are from FlyCircuit - so request makes no sense.  

Yes, it is possible to include the remote URI in the OWL.  

My first instinct was to use the standard xref annotation property.  The axioms have value = string that is conventionally structured as DB:accession.  This is what we already use, along with a standard recipe, for rolling linkouts.  We could (ab)use this field by adding values of the form (source:full_url), but this will be messy to parse.  So, I'm include to asd a new annotation property for data_source_link with string value = full URL.  This can be generated from a recipe specified in the data_source table of the VFB_owl database.

The second is obviously much easier to deal with, so I'm inclined to go with that.

Unless we invent an annotation property for data source, this will require a bit of string parsing

annotation axiom on individual: xref source:http:fubar/?id=1

**Comment by Robbie1977** [comment]
So to clarify these are from CacheroOstrovsky2010 and the external link should be http://flybase.org/reports/FBrf0211926.html or would http://flybrain.mrc-lmb.cam.ac.uk/dokuwiki/doku.php?id=pub:neuroanatomy:fru:start be more useful as the Publication would be in the definition.

@dosumis can we change to FBrf (when available) rather than PMID just to be more consistent.

**Comment by mmc46** [comment]
The source should be http://flybase.org/reports/FBrf0211926.html.

**Comment by Robbie1977** [comment]
@mmc46 This is only for the source link - usually the link to the original data and the paper is already in the references. The wiki page does a better job of explaining the alignment and giving links to original data and hence I think is a more useful link?

**Comment by mmc46** [comment]
I can see that it would be useful, but possibly confusing because the wiki page gives info on the registration of the original data, not on the bridged one that we have on the site (and the only place where the template is named is in the command in the 'Registration parameters' section).

Regardless, the link to the wiki could be added here.

http://www.virtualflybrain.org/site/vfb_site/image_data_downloads.htm

**Comment by Robbie1977** [comment]
Then how about an internal link to the correct section of the image data downloads page.

**Comment by mmc46** [comment]
Ok. 
For consistency, should we do the same to the rest of the image data in the downloads page?

**Comment by Robbie1977** [comment]
Agreed but this is only where the original data is not directly available
online.
