### ISSUE TITLE
Hyperlink related anatomy terms in anatomy term page

### ISSUE THREAD

**Issue by jefferis** [VirtualFlyBrain/VFB#188]
e.g. for this entry

<http://www.virtualflybrain.org/site/tools/anatomy_finder/index.htm?id=FBbt:00004013&name=suboesophageal%2520ganglion%2520(synonym)>

it would be great if relevant terms in the Definition and Comment sections were hyperlinked to their pages. e.g. in the text below

* esophagus
* adult gnathal ganglion
* adult subesophageal zone
* GNG
* saddle
* prow
* adult cerebral ganglion

> Definition: Region of the brain beneath the esophagus, consisting of the fused ganglia of the three gnathal segments.
Comment: In the adult, this is referred to as adult gnathal ganglion (GNG). The adult subesophageal zone comprises the GNG, the saddle and the prow (which is included in the adult cerebral ganglion) (BrainName).

**Comment by Robbie1977** [comment]
Without markup or some sort we could only feasibly resolve the abbreviations.

@dosumis would it be feasible to append instances of names and synonyms found in text fields with their  FBbt ref in brackets? I could then make these links quite quickly.

**Comment by Robbie1977** [comment]
It would also be nice to still mark the name so it could be marked as non-translatable for google #237

**Comment by dosumis** [comment]
We have almost 2000 classes with an OBO-style FBbt ID in brackets in the definition, following the name in some form in the text.  In almost all cases, the name is not delimited.  It wouldn't be a huge job to write a perl script that searched for matches to names (& synonyms?) of the term in the preceding text and delimited those found.  The most sensible way to do this would be to use Markdown link syntax.  => [name](FBbt:12345678) or maybe [name](FBbt_12345678).  We could covert to a full URL, but this wouldn't be great for readability.

I wouldn't be keen to mine the text for matches to term names/synonyms and then automatically generate links - as I don't think this will be sufficiently reliable.  We could mine as a way of generating lists of suggestions for hyperlinking that could then be reviewed by a curator.

**Comment by mmc46** [comment]
It would be good to hyperlink names and synonyms in text, but without adding FBbt ids or URLs to the text itself, please. That will make it hard to read the definition.

**Comment by Robbie1977** [comment]
Just putting square brackets around all terms would be satisfactory to resolve although I'd be happier if we precalculated and put the FBbt in the OWL version of the text when it's created to reduce the live processing.

**Comment by dosumis** [comment]
> It would be good to hyperlink names and synonyms in text, but without adding FBbt ids or URLs to the text itself, please.

We _already have_ almost 2000 classes with an OBO-style FBbt ID in brackets in the definition.  Many of these are auto-rolled definitions, but some were manually added.

**Comment by dosumis** [comment]
BTW - auto-rolled don't appear in the editor's file.

**Comment by Robbie1977** [comment]
FBbt and also FBal all auto linked on the vfbdev site now.

**Comment by Robbie1977** [comment]
Would be nicer to read if I could put the links on the names and then remove the refs in brackets. 

If we could possibly square bracket the name before (at least on the auto-rolled ones) this would result in a more readable output?

**Comment by Robbie1977** [comment]
Also added FBti FBtp FBgn links - any more I should cover?

**Comment by mmc46** [comment]
I meant to add any more FBids to the ones already there.

I think it's just missing FBim

to link to 

http://flybase.org/reports/FBimXXXXXXX.html

I could try changing the brackets. @dosumis would know if it might break something.

**Comment by dosumis** [comment]
Having the IDs in place and the names delimited in some way has two potential purposes.  One is for hyperlinking, the other is that it gives us a way to keep names in text in sync.  I'm not keen to remove the IDs in brackets as I'm not confident of automatically generating links based on lexical matching - given that names drift, and we often use shorter forms of names in text than when naming ontology classes.

If square brackets as delimiters are too distracting for consumers of the raw file, we could go with using backticks ( ` ) instead - as per the original proporal.  I belive there are some OBO ontology dev groups who do this - most notably HPO.
