### ISSUE TITLE
Autocomplete on half brain stack needs to point to the correct tree

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#248]
Currently appears to be populated from JFRC stack tree, so painted domains specific to half brain, such as the great commissure, cannot be found using stack specific autocomplete.

**Comment by Robbie1977** [comment]
autocomplete now resolves all adult anatomy.

This resolves the issue for not but #362 will resolve long term although if the current fix slows down the selection too much we could refine an autocomplete list for each tree.

**Comment by dosumis** [comment]
> autocomplete now resolves all adult anatomy.

Hmmm - I think this is too radical. At least for now.  The autocomplete you are using is populated by an OWL query: overlaps some 'nervous system'

A suitable OWL query for this autocomplete could be: 
"multi-cell component structure that 'part of' some 'adult brain'"

More conservative would be to find a way to drive this from the displayed tree.

There is a very general design issue with the current site.  It has always wrankled that you have to know to go back from the viewer page to the anatomy search page in order to do a general search.  I definitely don't want the new site to behave like this.  But finding a way to deal with this on the existing site and keep it usable is potentially tricky. Perhaps better avoided?
