### ISSUE TITLE
Composite view fails with 1 channel only selected

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#297]
with only one channel the viewer fails

http://vfbsandbox3.inf.ed.ac.uk/do/composite_view.html?colours=&action=View+composite

**Comment by Robbie1977** [comment]
Problem is not so clear cut. This specific problem no longer exists however current system is buggy and really needs a serious rethink.

**Comment by dosumis** [comment]
Leave for VFB 2.0?

**Comment by Robbie1977** [comment]
I have got an idea for a nice simple bean based (designed to be portable)
2d viewer rather than the horrible JavaScript tangle that we currently
have. I can cause so many error states it's impossible to log them all at
the moment. Was going to have a quick stab at a new prototype on sandbox 3
once the next release is out the way.

**Comment by dosumis** [comment]
Would it be re-usable in VFB2 ?

**Comment by dosumis** [comment]
Also - how is interface to OWL side?

**Comment by Robbie1977** [comment]
Would be designed to simplify the interface and the backend (even if we have to change language) to be usable with multiple templates and displays so the 3D should slot in.
The OWL we need to discuss as there are a few things that might want to be in the OWL plus tree construction etc.

**Comment by Robbie1977** [comment]
shall we have a chat before or after meeting today?
