### ISSUE TITLE
Review annotation shorthand mapping  - on table and test server

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#310]
Annotation shorthand mapping needs checking before public release:

* [mapping table](https://github.com/VirtualFlyBrain/VFB_owl/blob/master/doc/annotation_map.md)
* Also live on sandbox server (e.g. search for Kenyon cells and look for thumbs at bottom)
  * [to check - are antennal lobe neurons as expected](http://vfbsandbox.inf.ed.ac.uk/do/individual_list.html?action=ind_neuron_overlap&id=FBbt:00007401)

**Comment by Robbie1977** [comment]
Review again now with working system
