### ISSUE TITLE
Roll json files for tract stack

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#311]
This is a subticket of #116 

For now, tree should just have adult brain at top and a flat list of tracts underneath.  For more structure, we could look in to assigning tracts to neuromeres.

Note - for this, it is important that tree autcomplete switches to appropriate tree - see #248.

**Comment by dosumis** [comment]
Draft files here:  
https://github.com/VirtualFlyBrain/VFB_owl/tree/master/src/trees/BrainName_tracts/json

Sorry for delay.  

Not sure how to go about adding them to VFB. Do we need a new directory under here:
https://github.com/VirtualFlyBrain/VFB/tree/master/data/flybrain

?

**Comment by Robbie1977** [comment]
@dosumis Rather than having a separate stack why not include in the main ontology under the subheading 'tract' (FBbt:00005100) or 'tract neuropil' (FBbt:00040004)?

**Comment by dosumis** [comment]
Could work.  Are the domain IDs for the 2 stacks distinct?

**Comment by dosumis** [comment]
Do you envision combining the masks?  If so, will probably require some careful tuning of colours...

**Comment by Robbie1977** [comment]
We could easily do it - Woolz is fine with overlapping domains.

The domain numbers would have to be increased. 
Simply adding 100 would fit the current ranges.

This is why a favour a dynamic colour range rather than fixed colours as impossible to cover all potential overlaps without limiting to selected content (let alone the colour BG on the half brain). We'd just have to use the lab spaced colours as usual and hope for the best for now.

**Comment by dosumis** [comment]
TODO - add dynamic assignment of colours to VFB 2.0 image browser spec.  We should also add a colour key for currently displayed domains.

**Comment by dosumis** [comment]
> Simply adding 100 would fit the current ranges.

Working on combined version now.

**Comment by Robbie1977** [comment]
Already in my spec in my head and was on the mock up - just need to update the actual spec! (it's on my todo list). Just need to find an alternative to Lab spaced that's colorblind friendly to offer as an alternative. 

Although this is a discussion for another thread.

**Comment by dosumis** [comment]
Should also link to mockups from spec.

**Comment by dosumis** [comment]
> Rather than having a separate stack why not include in the main ontology under the subheading 'tract' (FBbt:00005100) or 'tract neuropil' (FBbt:00040004)?

To do this, we'd really need a new term 'adult brain tract' - as tract (5100) doesn't sit under the root ('adult brain').  Doing this properly would require an ontology update, although _could_ be added as a temporary hack. 

One possibility might be to have two roots, leaving the tracts out from under 'adult brain' - even though they are are part of itL

adult brain
.     adult antennal lobe
.     ... etc
tracts
.     antennal lobe commissure
.     ...  etc

But looking at treeStructure.jso - I think two roots may be impossible.

(Roll on automation of this all in VFB 2.0 ....  Way too much bespoke tinkering going on right now.)

**Comment by Robbie1977** [comment]
Would tract neuropil not cover it?

**Comment by Robbie1977** [comment]
can't think why two routes should be a problem from the treeviewer point of view.

**Comment by dosumis** [comment]
> can't think why two roots should be a problem from the treeviewer point of view.

treeStructure.json 

~~~~~~~.json
{
    "node": {
        "children": [
            {
                "node": {
                    "nodeId": "1"
                }
            },
            {
                "node": {
                    "nodeId": "2"
                }
            }
        ],
        "nodeId": "0"
    }
}
~~~~~~~~

**Comment by dosumis** [comment]
> Would tract neuropil not cover it? 

Still makes a parallel root with 'adult brain'.  Either choice, if queries on will produce results for all tracts in NS at all stages.  Would be odd beheviour for a node sat underneath 'adult brain'.

**Comment by Robbie1977** [comment]
But our tracts are only adult brain

**Comment by dosumis** [comment]
There are non-adult ones in the ontology.  At least some of these have annotations attached.

**Comment by dosumis** [comment]
For now - here's a combined version with tracts listed alphabetically at the bottom of the tree. 

https://github.com/VirtualFlyBrain/VFB_owl/tree/master/src/trees/BrainName_combined/json

New domain IDs for tracts in domain_data.tsv under tracts.

But just realised there is another problem - Great commissure is on both stacks.  Probably some others too.  Guess we can just prune off duplicates...

**Comment by dosumis** [comment]
Updated to remove duplicate domains.  Please test ASAP.  Note - tract domainIDs are all +300.  (see 
https://github.com/VirtualFlyBrain/VFB_owl/tree/master/src/trees/BrainName_tracts/domain_data.tsv)

**Comment by Robbie1977** [comment]
@dosumis all ready on dev but failing as colour values need to be integers - you seem to have used 0-1 floats on only some:

  {
        "domainData": {
            "domainCentre": "287.82,91.929,69.2617",
            "domainColour": "0.44828,0.37931,0.48276",
            "domainId": "324",
            "domainSelected": "false"
        },
        "extId": [
            "FBbt:00100338"
        ],
        "name": "pyriform fascicle",
        "nodeId": "301",
        "nodeState": {
            "open": "true",
            "selected": "false"
        }
    },

**Comment by dosumis** [comment]
The numbers come from the tsv mapping file that's been sitting here for ages.  Not entirely sure where they originate from before that.  Possibly stripped from the amira label field provided with the stack. If you can update the tsv entries to something sensible, I can easily re-run the script to regenerate the json files.

**Comment by Robbie1977** [comment]
Done

**Comment by dosumis** [comment]
Uploaded regenerated treeContent.jso .  (BTW - can you try to make sure edited tsv files have unix line endings? My tsv munging assumes this.

**Comment by Robbie1977** [comment]
Sorry Excel in Mac has an annoying habit of doing that.

**Comment by Robbie1977** [comment]
Seem to be missing colours now?

 {
        "domainData": {
            "domainCentre": [
                403.787,
                233.636,
                72.8754
            ],
            "domainId": "43",
            "domainSelected": "false"
        },
        "extId": [
            "FBbt:00007080"
        ],
        "name": "great commissure",
        "nodeId": "273",
        "nodeState": {
            "open": "false",
            "selected": "false"
        }
    },

**Comment by Robbie1977** [comment]
Also the great commissure should be 304?

**Comment by Robbie1977** [comment]
tsv should be in correct format now.

**Comment by dosumis** [comment]
Fixed. 
Note - Where a field is in both masks, as with the great commissure, the one in BrainName_domain takes precedence.

**Comment by Robbie1977** [comment]
Just be aware they (great commissure: 43, 304) are grossly the same but not identical.

![image](https://cloud.githubusercontent.com/assets/4630768/6545850/5397a814-c593-11e4-9e73-6f2f88bbea4e.png)

**Comment by dosumis** [comment]
Easy enough to switch precedence.  Your call.

**Comment by Robbie1977** [comment]
Hard to say which is more accurate, maybe the tract ones might be a better beat as they are not restricted by avoiding overlap with the neuropil regions.

Also the overlapped domains seem to be missing or have invalid colour specifications.

**Comment by Robbie1977** [comment]
All now working on:
http://vfbdev.inf.ed.ac.uk/site/stacks/halfmain.htm

**Comment by dosumis** [comment]
Not sure about the combination.  Especially as in cases of overlap, you don't get float-over selection.  It's also pretty hard to find some of the tracts even after being selected and centred. Perhaps a better way to navigate this stuff would be to have it on a separately selectable mask and to have the option of highlighting all.  That, along with some judicious choice of colors, might make it navigable by browsing through the stack.  Ideally we'd have a maximum projection view too, although don't know where that would fit in the current system.  Ultimately we need 3D though - just as we do for single neurons.

For now - can you fix the broken colors?  I know nothing about how to work with these - apart from just choosing a random selection from the table of colors you posted.

**Comment by Robbie1977** [comment]
Tidied up the bulk on the colours and a few centres (if the contralateral version is there it throws off the centre of mass).
The float over label now works for more than one name returned.

**Comment by Robbie1977** [comment]
I'm happy with it for now (may need tweaking of colours and centres if they prove an issue).

Rather improve the browser in general than manually pick colours.

**Comment by dosumis** [comment]
What are the blockers on this.  Can we push it out in time for the Crete milestone ?

**Comment by Robbie1977** [comment]
I think you just need to reproduce the json in VFB_OWL and then we can test on sandbox

**Comment by dosumis** [comment]
Should already be there

As far as I remember, the remaining issue is whether it is best to combine with the neuropil stack:
https://github.com/VirtualFlyBrain/VFB_owl/tree/master/src/trees/BrainName_combined/json

Or keep separate:
https://github.com/VirtualFlyBrain/VFB_owl/tree/master/src/trees/BrainName_tracts/json

I think the latter would be easier as we don't have the problem of how to deal with overlapping painted domains.  I think it will also be clearer for users.  The remaining problem is then how to let users choose the mask.  Perhaps just add another menu item?

**Comment by Robbie1977** [comment]
They'd have to be separate stacks on the existing system: half brain
neuropil & half brain tracts.

The overlap shouldn't be too bad as both items show up in the hover over
description now.
