### ISSUE TITLE
Cluster searching broken on sandbox server

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#312]
See http://vfbsandbox.inf.ed.ac.uk/do/cluster_list.html?action=cluster_found&id=FBbt:00007401

Running the [query](https://github.com/VirtualFlyBrain/VFB/wiki/Queries) for this directly on the [OWL file on the sandbox branch](https://github.com/VirtualFlyBrain/VFB/blob/Sandbox-Server/resources/fbbt_vfb_ind_pr_nr.owl) finds 73 cluster examplars:

![image](https://cloud.githubusercontent.com/assets/112839/5217623/ec653636-763a-11e4-8e44-19e3bc649695.png)

**Comment by dosumis** [comment]
Progress - or sorts.  Query works fine in scripty test using the latest elk lib + org.obolibrary.macro.ManchesterSyntaxTool from oboformat-all.jar (using version from WEB-INF/lib/).  Using the original elk lib is a little more complicated.  I will try this next.

I have also further documented the existing code.  The path that queries take in the ontology query server is now clear.

**Comment by dosumis** [comment]
I may have found the problem.  In my tests at least, It looks like the ordering of JARS in the classpath that consistently causes the fail.  It works if the ELK JAR is specified before the OWLtools jar on the classpath, but not the other way round.

So - I *think* the problem is with multiple copies of the OWL-API lurking in various JARS.  When the fail happens, no reasoning happens and the reasoner call return noneType.  I suspect that the fail happens when the owl-api dataFactory comes from one instance of the OWL-API and the ontology manager  (&/or the ontology object itself) comes from another.

Conclusion: We badly need to switch to a dependency management system for java libs - which in this case has to mean Maven.

Notes on cleaning up libs (perhaps independent of mavenising):  Specify OWL-API version separately from Elk, OWLtools and Brain, avoiding mega jars for any of these, with the OWL-API embedded. . Somewhat challenging to work out which version is good for all - High priority:  Talk to Owtools devs about safe JARs to use to get only owltools specific libs without embedded OWL-API - also discuss with them whether we can pull using Maven.

**Comment by Robbie1977** [comment]
Resolved with new ontology server
