### ISSUE TITLE
Thresholding Issue on some examples 

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#314]
This is on a few which I will try and extract out but an example is:
fru-M-200324 
http://vfbdev.inf.ed.ac.uk/owl/VFB_00000007

**Comment by Robbie1977** [comment]
The problem is in the original files so nothing we can do to clean-up this end.

The affected files are easy to spot as they are much larger:
-rwxrwxrwx 1 s1002628 people  1.2M Mar 23  2014 ChaMARCM-F000178_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.3M Mar 23  2014 ChaMARCM-F000192_seg002.nrrd
-rwxrwxrwx 1 s1002628 people  1.3M Mar 23  2014 ChaMARCM-F000221_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.2M Mar 23  2014 ChaMARCM-F000327_seg002.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 ChaMARCM-F000523_seg002.nrrd
-rwxrwxrwx 1 s1002628 people  9.2M Mar 23  2014 ChaMARCM-F000614_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  8.3M Mar 23  2014 ChaMARCM-F000757_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.6M Mar 23  2014 ChaMARCM-F000878_seg004.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 ChaMARCM-F000948_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.2M Mar 23  2014 ChaMARCM-F001312_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 ChaMARCM-F001368_seg002.nrrd
-rwxrwxrwx 1 s1002628 people  1.4M Mar 23  2014 ChaMARCM-F001378_seg002.nrrd
-r-xr-xr-x 1 s1002628 people  3.3M Mar 23  2014 ChaMARCM-F001436_seg002.nrrd
-r-xr-xr-x 1 s1002628 people  1.6M Mar 23  2014 ChaMARCM-F001464_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.3M Mar 23  2014 ChaMARCM-F001543_seg003.nrrd
-r-xr-xr-x 1 s1002628 people  2.0M Mar 23  2014 ChaMARCM-F001554_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.3M Mar 23  2014 dTdc2MARCM-F000076_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.2M Mar 23  2014 dTdc2MARCM-F000180_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.2M Mar 23  2014 dTdc2MARCM-F000181_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.2M Mar 23  2014 dTdc2MARCM-F000190_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  5.7M Mar 23  2014 dTdc2MARCM-F000211_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.9M Mar 23  2014 dTdc2MARCM-F000215_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  4.0M Mar 23  2014 dTdc2MARCM-F000227_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.1M Mar 23  2014 dTdc2MARCM-F000230_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 dTdc2MARCM-F000246_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  3.2M Mar 23  2014 dTdc2MARCM-F000248_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.2M Mar 23  2014 DvGlutMARCM-F002282_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  2.7M Mar 23  2014 DvGlutMARCM-F002424_seg002.nrrd
-rwxrwxrwx 1 s1002628 people  2.7M Mar 23  2014 DvGlutMARCM-F002512_seg002.nrrd
-rwxrwxrwx 1 s1002628 people  2.4M Mar 23  2014 DvGlutMARCM-F002554_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.6M Mar 23  2014 DvGlutMARCM-F002826_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.9M Mar 23  2014 DvGlutMARCM-F002898_seg002.nrrd
-r-xr-xr-x 1 s1002628 people  1.8M Mar 23  2014 DvGlutMARCM-F002978_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.9M Mar 23  2014 DvGlutMARCM-F003214_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  2.1M Mar 23  2014 DvGlutMARCM-F003253_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.5M Mar 23  2014 DvGlutMARCM-F003551_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.7M Mar 23  2014 DvGlutMARCM-F003581_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  2.9M Mar 23  2014 DvGlutMARCM-F003597_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.2M Mar 23  2014 DvGlutMARCM-F003618_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  2.1M Mar 23  2014 DvGlutMARCM-F003624_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 DvGlutMARCM-F003640_seg002.nrrd
-rwxrwxrwx 1 s1002628 people  1.7M Mar 23  2014 DvGlutMARCM-F003670_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.3M Mar 23  2014 DvGlutMARCM-F003723_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.7M Mar 23  2014 DvGlutMARCM-F003727_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  3.1M Mar 23  2014 DvGlutMARCM-F003769_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  2.1M Mar 23  2014 DvGlutMARCM-F003841_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.1M Mar 23  2014 DvGlutMARCM-F003996_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.5M Mar 23  2014 DvGlutMARCM-F004022_seg003.nrrd
-rwxrwxrwx 1 s1002628 people  1.5M Mar 23  2014 DvGlutMARCM-F004109_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.4M Mar 23  2014 DvGlutMARCM-F004255_seg003.nrrd
-rwxrwxrwx 1 s1002628 people  1.4M Mar 23  2014 DvGlutMARCM-F004310_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 DvGlutMARCM-F004359_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  2.6M Mar 23  2014 DvGlutMARCM-F004466_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.4M Mar 23  2014 DvGlutMARCM-F004559_seg002.nrrd
-rwxrwxrwx 1 s1002628 people  1.7M Mar 23  2014 DvGlutMARCM-F004593_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 DvGlutMARCM-F022_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.5M Mar 23  2014 DvGlutMARCM-F089-montage_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  1.1M Mar 23  2014 DvGlutMARCM-F1009_seg2.nrrd
-r-xr-xr-x 1 s1002628 people  1.4M Mar 23  2014 DvGlutMARCM-F1029_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  2.7M Mar 23  2014 DvGlutMARCM-F1192_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.2M Mar 23  2014 DvGlutMARCM-F1291_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  2.5M Mar 23  2014 DvGlutMARCM-F1432_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.2M Mar 23  2014 DvGlutMARCM-F1434_seg2.nrrd
-r-xr-xr-x 1 s1002628 people  3.0M Mar 23  2014 DvGlutMARCM-F158_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  2.4M Mar 23  2014 DvGlutMARCM-F1732_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.8M Mar 23  2014 DvGlutMARCM-F1783_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  1.1M Mar 23  2014 DvGlutMARCM-F1957_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  1.2M Mar 23  2014 DvGlutMARCM-F2077_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  2.6M Mar 23  2014 DvGlutMARCM-F2147_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  1.7M Mar 23  2014 DvGlutMARCM-F2166_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.5M Mar 23  2014 DvGlutMARCM-F228_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.5M Mar 23  2014 DvGlutMARCM-F500_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  3.0M Mar 23  2014 DvGlutMARCM-F578-X2_seg2.nrrd
-r-xr-xr-x 1 s1002628 people  2.3M Mar 23  2014 DvGlutMARCM-F608_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.3M Mar 23  2014 DvGlutMARCM-F657_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  1.7M Mar 23  2014 DvGlutMARCM-F944_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.4M Mar 23  2014 DVGlutMARCMFemale-0508-02-montage_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.2M Mar 23  2014 FruMARCM-F000627_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  2.3M Mar 23  2014 FruMARCM-F000910_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  2.0M Mar 23  2014 FruMARCM-F000928_seg003.nrrd
-rwxrwxrwx 1 s1002628 people  1.5M Mar 23  2014 FruMARCM-F001397_seg002.nrrd
-r-xr-xr-x 1 s1002628 people  1.4M Mar 23  2014 FruMARCM-F001428_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.6M Mar 23  2014 FruMARCM-F001672_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.3M Mar 23  2014 FruMARCM-F002341_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  3.4M Mar 23  2014 FruMARCM-F002427_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  2.6M Mar 23  2014 FruMARCM-M000227_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.6M Mar 23  2014 FruMARCM-M001064_seg002.nrrd
-r-xr-xr-x 1 s1002628 people  1.2M Mar 23  2014 FruMARCM-M001276_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.9M Mar 23  2014 FruMARCM-M001291_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.4M Mar 23  2014 FruMARCM-M001598_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.6M Mar 23  2014 FruMARCM-M001650_seg002.nrrd
-r-xr-xr-x 1 s1002628 people  2.9M Mar 23  2014 FruMARCM-M001849_seg002.nrrd
-rwxrwxrwx 1 s1002628 people  1.2M Mar 23  2014 FruMARCM-M001945_seg002.nrrd
-r-xr-xr-x 1 s1002628 people  1.3M Mar 23  2014 FruMARCM-M001967_seg002.nrrd
-rwxrwxrwx 1 s1002628 people  1.3M Mar 23  2014 FruMARCM-M002033_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  2.5M Mar 23  2014 FruMARCM-M002239_seg002.nrrd
-rwxrwxrwx 1 s1002628 people  2.0M Mar 23  2014 FruMARCM-M002373_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.9M Mar 23  2014 FruMARCM-M002413_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.5M Mar 23  2014 FruMARCM-M002578_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.4M Mar 23  2014 GadMARCM-F000285_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.3M Mar 23  2014 GadMARCM-F000296_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.5M Mar 23  2014 GadMARCM-F000329_seg002.nrrd
-rwxrwxrwx 1 s1002628 people  2.6M Mar 23  2014 GadMARCM-F000450_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  9.3M Mar 23  2014 GadMARCM-F000515_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  2.0M Mar 23  2014 GadMARCM-F000599_seg002.nrrd
-r-xr-xr-x 1 s1002628 people  1.2M Mar 23  2014 GadMARCM-F000648_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.7M Mar 23  2014 GadMARCM-F000677_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.3M Mar 23  2014 GH146MARCM-M000006_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.2M Mar 23  2014 npfMARCM-F000007_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  1.2M Mar 23  2014 THMARCM-037F_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 THMARCM-039M_seg2.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 THMARCM-042F_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  2.3M Mar 23  2014 THMARCM-073M_seg2.nrrd
-rwxrwxrwx 1 s1002628 people  4.6M Mar 23  2014 THMARCM-093M_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.7M Mar 23  2014 THMARCM-138F_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  1.9M Mar 23  2014 THMARCM-277M_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.7M Mar 23  2014 THMARCM-314F_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  2.5M Mar 23  2014 THMARCM-330M_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.7M Mar 23  2014 THMARCM-393F_seg2.nrrd
-r-xr-xr-x 1 s1002628 people  1.9M Mar 23  2014 THMARCM-456F_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.6M Mar 23  2014 THMARCM-462F_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  1.1M Mar 23  2014 THMARCM-465M_seg2.nrrd
-r-xr-xr-x 1 s1002628 people  2.8M Mar 23  2014 THMARCM-547M_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  5.1M Mar 23  2014 THMARCM-599M-X2_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  1.7M Mar 23  2014 THMARCM-655F_seg.nrrd
-rwxrwxrwx 1 s1002628 people  2.3M Mar 23  2014 THMARCM-692F_seg.nrrd
-rwxrwxrwx 1 s1002628 people  1.9M Mar 23  2014 THMARCM-714F_seg.nrrd
-r-xr-xr-x 1 s1002628 people  4.6M Mar 23  2014 THMARCM-717F-X2_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  1.2M Mar 23  2014 THMARCM-762F_seg2.nrrd
-r-xr-xr-x 1 s1002628 people  1.1M Mar 23  2014 THMARCM-776F_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.3M Mar 23  2014 TPHMARCM-091M_seg2.nrrd
-r-xr-xr-x 1 s1002628 people  2.6M Mar 23  2014 TPHMARCM-1266F_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  3.1M Mar 23  2014 TPHMARCM-293F_seg3.nrrd
-r-xr-xr-x 1 s1002628 people  1.6M Mar 23  2014 TPHMARCM-577F_seg1.nrrd
-r-xr-xr-x 1 s1002628 people  2.4M Mar 23  2014 TPHMARCM-654F_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  2.7M Mar 23  2014 TPHMARCM-678F_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 TPHMARCM-829F_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 TPHMARCM-883F_seg1.nrrd
-rwxrwxrwx 1 s1002628 people   11M Mar 23  2014 TPHMARCM-936M_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 TPHMARCM-988M_seg1.nrrd
-rwxrwxrwx 1 s1002628 people  1.1M Mar 23  2014 TPHMARCM-F001851_seg001.nrrd
-rwxrwxrwx 1 s1002628 people  2.0M Mar 23  2014 TPHMARCM-M001422_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.3M Mar 23  2014 TPHMARCM-M001477_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.3M Mar 23  2014 TPHMARCM-M001791_seg001.nrrd
-r-xr-xr-x 1 s1002628 people  1.3M Mar 23  2014 TPHMARCM-M001815_seg001.nrrd

**Comment by Robbie1977** [comment]
@mmc46 or @jefferis could you investigate where the issue occurred and if possible supply corrected files.

**Comment by jefferis** [comment]
Hi Rob,

Can you tell if these are 8 or 12(16) but images. Perhaps they are the raw marcm channel rather than the segmented channel. 

Gregory Jefferis

**Comment by mmc46** [comment]
I think this might be related to an error I’d spotted in April 2013, when preparing sample images for Bill Hill. There were problems with any image bigger than 907kb.

@jefferis email subject “Sample images” 24th April 2013.
Greg fixed these on hex, at the time. I’m not sure if the tar was updated

http://flybrain.mrc-lmb.cam.ac.uk/vfb/fc/reformatted.JFRC2.tar

If it has, they would just need to be downloaded again.

**Comment by Robbie1977** [comment]
The tar file copies all look good - we may have reverted to an old copy when we had to restore the system a while ago.
I'll replace all the files with these copies.

**Comment by jefferis** [comment]
Sent from my iPad

> On 20 Feb 2015, at 12:21, mmc46 <notifications@github.com> wrote:
> 
> I think this might be related to an error I’d spotted in April 2013, when preparing sample images for Bill Hill. There were problems with any image bigger than 907kb.
> 
> @jefferis email subject “Sample images” 24th April 2013.
> Greg fixed these on hex, at the time. I’m not sure if the tar was updated
> 
> http://flybrain.mrc-lmb.cam.ac.uk/vfb/fc/reformatted.JFRC2.tar

Thanks @mmc46. Was still travelling today and didn't remember this.

**Comment by Robbie1977** [comment]
That's fixed it 
Being loaded in ATM with the new stack loader but all looking good and example above resolved.
