### ISSUE TITLE
Simplify Ontology Server

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#336]
It should be possible to radically simplify the ontology query server, ditching much of the current code.

To do this:
1. Brain needs to be updated to 1.4.2 or higher.
2. Individuals queries need to be rewritten to be specified as OWL shortFormIDs.
3. All queries should run via some modified or extended form of DLQueryEngineBrain.Java.  
 * Incoming queries of type 'Individual' can use code almost identical to that in the current DLQueryEngineBrain.Java with the exception that an instance query should be used in place of a subclass one:
   * subClasses = DLQueryEngineBrain.brain.getSubClasses(currExpr, false);
   * \>
   * individuals = DLQueryEngineBrain.brain.getInstances(currExpr, false);
 * We still need two ontology objects - one for class queries (running fbbt-simple) and one for individual queries (running combined ont + individuals file).  But should experiment with reducing this to one.
 * While this extension to the query engine code is simple, changing the client/server system to direct queries and results will require better documentation of this system

Caveat: The ontology server may contain additional code for dealing with post query processing of the results of annotation pre-queries.  If necessary, this should be modified to work with the Brain query engine (it may already do...)
UPDATE: looks like code for this is outside of the ontology server.

Files that should be safe to delete as a result of this work:

DLQueryEngineElk
DLQueryEngine
...

**Comment by dosumis** [comment]
Note - we will still need two instance of the DLQueryEngineBrain - one running fbbt-simple, the other running the individuals file.   it may be possible to simplify further and just have one instance running a single combined (simple) ontology + individuals file, but this will require some work on OWL file generation + performance testing.

**Comment by dosumis** [comment]
[First attempt at this commited to Sandbox server](https://github.com/VirtualFlyBrain/VFB/commit/574edc1d7a0f40e66833a428433b2956f6109dba)

Brain switched to megajar version 1.4.2 (don't have separate jar available and we're still not set up to use in recommended way via maven).  

@Robbie1977 build.xml file edited to remove stale libraries and add new Brain.  Not clear to me why there are loads of java files specied as classpath in this file.  Had to remove to get things to run locally but left in pending check.

Note - code only tested locally as far as firing up ontology server.  @Robbie1977 : How are you firing test queries at this server?

**Comment by Robbie1977** [comment]
Should be showing up on Sandbox now

**Comment by Robbie1977** [comment]
I take that back something is causing tomcat deployment to fail - investigating

**Comment by dosumis** [comment]
Wouldn't surprise me if my changes brought down the site. Need a better
local testing setup.

**Comment by dosumis** [comment]
Fixed.
