### ISSUE TITLE
Switch autocomplete to work from SOLR

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#362]
This is an umbrella ticket for work required to switch autocomplete to SOLR.  The plan is to re-use this on the new site.  Please make sub-issues and link to this issue via \#\<some ticket number>

1. Set up SOLR instance
2. Finalise Spec
 - [Functional specs](https://github.com/VirtualFlyBrain/VFB_2/blob/master/specs/functional_specs.md#autosuggest-search)
    - should include description of minimum functionality required for release.
 - Technical specs
3. Specify queries required to populate SOLR index:
   - OWL
   - SQL
4. Implementation

**Comment by dosumis** [comment]
@Robbie1977 - made a start.  Do these functional specs look reasonable?

**Comment by Robbie1977** [comment]
I'd suggest enabling searching by ID's for the appropriate search as this is something we're missing at present and SOLR should be able to handle in a nicer way than previously possible.

**Comment by dosumis** [comment]
Good point

**Comment by dosumis** [comment]
Query to find all nervous system terms: overlaps some 'nervous system'.  Can be passed to brain as query string with unquoted IDs in place of labels.  The same query could be used with ind query to find all individuals.

**Comment by Robbie1977** [comment]
can we proceed with adding required classifications to the ontology to enable SOLR as this is not affected by the OLS planned fixes

**Comment by Robbie1977** [comment]
@dosumis Latest version still doesn't seem quite right:

http://vfbdev.inf.ed.ac.uk/search/ontologySuggest?q=AMMC&wt=json&indent=true

http://vfbdev.inf.ed.ac.uk/search/ontologySuggest?q=optic+lo&wt=json&indent=true

FYI I've made all three endpoints open for testing:

http://vfbdev.inf.ed.ac.uk/search/ontologySearch

http://vfbdev.inf.ed.ac.uk/search/ontologySuggest

http://vfbdev.inf.ed.ac.uk/search/ontologySelect

**Comment by Robbie1977** [comment]
original issue resolved
