### ISSUE TITLE
Add attribution/ORCID link for contributors to terms acknowledged using initials in dbxrefs

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#380]
Many definitions have some acknowledgment of authors and contributors to definitions using FBC:<some initials>.  It would be good to turn these into attributions that make sense to the rest of the world.  We can do this via a route proposed as a general mechanism for attirbution of micro-contribtuion to OBO ontologies using linkes to ORCID pages.

To do this, we will need a mapping table of initials to names to ORCIDs.  This can then be used to roll links acknowledging contributions , e.g. [David Osumi-Sutherland](http://orcid.org/0000-0002-7073-9172)

**Comment by Robbie1977** [comment]
@mmc46 do you have a list of initials with full names if not orcid - id's directly?

**Comment by mmc46** [comment]
Here is the list. I've done some tidying up, but needs some more. 
@dosumis: are ds555 and DS the same person? In DOS&SR, is SR the same as SPR?

FBC:DOS
FBC:gg
FBC:SPR
FBC:VH
FBC:ds555
FBC:ma
FBC:FlyBase
FBC:DOS&SR
FBC:VH
FBC:AJ
FBC:VH
FBC:JR
FBC:GJ
FBC:MMC
FBC:KI&DS
FBC:LSG

**Comment by Robbie1977** [comment]
How do we want to handle joint attribution?

**Comment by Robbie1977** [comment]
Test example: http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:10005220&name=embryonic%20secondary%20branch

**Comment by mmc46** [comment]
For joint attribution, just list both FB curator names’.

In this example

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00007055&name=superior%20medial%20protocerebrum

it should show both 

FBC: Volker Hartenstein
FBC: Arnim Jenett

**Comment by dosumis** [comment]
Joint attributions should be made separate in ontology. Code should be doing as little string parsing as possible.
so
FBC:DOS&SR
>
FBC:DOS, FBC:SR

We should also check that outside contibutors are happy to have their names on these things - Just display actual FlyBase curators until we're sure about this.

**Comment by mmc46** [comment]
I have changed them in the ontology, except for the cases I asked @dosumis about, earlier in the ticket.

**Comment by dosumis** [comment]
SPR is Simon Reeve.  ds555 is me (was meant as a placeholder for a ref but never got published).  Don't know offhand  who JR, LSG & JR are.  MA is Michael Ashburner.

**Comment by mmc46** [comment]
@dosumis Are you DS as well?

**Comment by mmc46** [comment]
Ok, FBC:KI&DS is now FBC: KI, FBC:DOS.

**Comment by Robbie1977** [comment]
FYI I've allowed for the & for now and see how it copes when the changes work their way through.

**Comment by Robbie1977** [comment]
What should we call non curators?

**Comment by Robbie1977** [comment]
Should we be quoting the FBrf with references if they are used in definition:

http://www.virtualflybrain.org/site/tools/anatomy_finder/index.htm?id=FBbt:00100332

**Comment by mmc46** [comment]
I’d say no.

**Comment by dosumis** [comment]
In almost all cases we currently have a manually curated miniref (e.g. Costa et al., 2014) in the def.  Think we should just stick with this as users will easily be able to cross-ref with reference list.  FBrfs are rare in text and should probably just be removed.

**Comment by Robbie1977** [comment]
Agreed

**Comment by Robbie1977** [comment]
When we only have a FBC ref in description and not in ref:

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00004355&name=distal%20sensillum

Should we have a ref added on these or are you happy as is?

**Comment by Robbie1977** [comment]
Other than resolving all FBC names to orcidID's can anyone break the current version on vfbdev?

**Comment by mmc46** [comment]
An issue of consistency between FBc names in defs and synonyms:

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00100297&name=femoral%20sensillum%20campaniformium

It seems that FBC:SPR in synonyms is different to FlyBase curator in definition ref ((FlyBase Curator: SPR)), when it is the same person. 

Could the synonym ref show the same as the definition? In this case:

FlyBase Curator [Simon Reeve]

**Comment by Robbie1977** [comment]
yep good point - I have a ticket open #385 to move all the ref conversion into one module which should clean that up.

**Comment by Robbie1977** [comment]
On second thoughts they are different as the short version is used in synonyms so would we not be better putting the short ref as (FBC:XX) as this is how they appear in FB text such as description.

**Comment by Robbie1977** [comment]
@mmc46 how about calling non curators 'FlyBase Consultant: Xxxxx Xxxxx' ?

**Comment by Robbie1977** [comment]
*Airing towards the google search by full name rather than individual web page links if they don't have orcidID as otherwise a headache to maintain long term. See VH.

**Comment by mmc46** [comment]
"On second thoughts they are different as the short version is used in synonyms so would we not be better putting the short ref as (FBC:XX) as this is how they appear in FB text such as description?"

What do you mean by 'they are different"? 

In any case, as long as they look the same, in definition refs and synonyms that's fine by me.

I'm ok with 'FlyBase Consultant [Xxxxx Xxxxx]'  .

**Comment by Robbie1977** [comment]
Great - should all be working now.

**Comment by Robbie1977** [comment]
Just need names for:
FBC:JR ??
FBC:SR ??
FBC:KI ??
FBC:LSG ??

@dosumis if you don't know who they are @mmc46 is it possible to ask about FlyBase also is it not worth these being in the Pub table as there is something akin in the first records?

1;"gadfly3";"";"";"";"";"";"";"gadfly3";1;FALSE;"";"";"gadfly3"
2;"tupy";"";"";"";"";"";"";"tupy";1;FALSE;"";"";"tupy"
3;"andy";"";"";"";"";"";"";"andy";1;FALSE;"";"";"andy"
4;"bmatthew";"";"";"";"";"";"";"bmatthew";1;FALSE;"";"";"bmatthew"
5;"brian";"";"";"";"";"";"";"brian";57062;FALSE;"";"";"brian"
6;"campbell";"";"";"";"";"";"";"campbell";1;FALSE;"";"";"campbell"
7;"cdsmith";"";"";"";"";"";"";"cdsmith";57062;FALSE;"";"";"cdsmith"
8;"cjm";"";"";"";"";"";"";"cjm";2;FALSE;"";"";"cjm"
9;"joshk";"";"";"";"";"";"";"joshk";1;FALSE;"";"";"joshk"
10;"crosby";"";"";"";"";"";"";"crosby";1;FALSE;"";"";"crosby"
11;"mhuang";"";"";"";"";"";"";"mhuang";1;FALSE;"";"";"mhuang"
12;"null";"";"";"";"";"";"";"null";1;FALSE;"";"";"null"
13;"pavel";"";"";"";"";"";"";"pavel";1;FALSE;"";"";"pavel"
14;"sima";"";"";"";"";"";"";"sima";1;FALSE;"";"";"sima"
15;"simonp";"";"";"";"";"";"";"simonp";1;FALSE;"";"";"simonp"
16;"";"";"";"";"";"";"";"FlyBase";2;FALSE;"";"";"FlyBase_"
17;"";"";"";"";"";"";"";"leyla";2;FALSE;"";"";"leyla"
21;"validator_r32";"";"";"";"";"";"";"validator_r32";1;FALSE;"";"";"validator_r32"

**Comment by mmc46** [comment]
@Robbie1977 Sorry, don't understand what you want me to do

"is it possible to ask about FlyBase also is it not worth these being in the Pub table as there is something akin in the first records?"

**Comment by mmc46** [comment]
@Robbie1977 should the consistency between refs in synonyms and defs be solved now that #385 is closed? 
I can still see the discrepancy.

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00100297&name=femoral%20sensillum%20campaniformium

**Comment by Robbie1977** [comment]
Is it worth sending an email around everyone at FlyBase asking who the Initials belong to - someone must know.

Should these not really be recorded somewhere at the FlyBase end as give it 10 years then no one will know what the TBC refs mean. You could put them in the FlyBase DB under 'Pub' table with the uniquename 'FBC:MMC' and the miniref 'FlyBase Curator Marta Mesquita da Costa'  as a suggestion or add a new table.

**Comment by Robbie1977** [comment]
The TBC refs in synonyms are now consistent with those used in comment / description text also they give the expanded name if you hover and link to the correct users page (When it has the name).

**Comment by mmc46** [comment]
I think FBC:KI is Kei Ito, from the terms where it's used.

I can send an email around FlyBase, but I don't think the missing initials are from FlyBase staff, as there is only one term each annotated with those initials. @dosumis  any idea?

[Term]
id: FBbt:00100297
name: femoral sensillum campaniformium
def: "Sensillum campaniformium located in the femur." [FBC:LSG, FBC:SPR]
synonym: "campaniform sensilla of femur" EXACT [FBC:SPR]
synonym: "femoral campaniform sensilla" EXACT [FBC:SPR]
synonym: "sensillum campaniformium of femur" EXACT [FBC:SPR]
xref: VFB:FBbt_00100297
intersection_of: FBbt:00005183 ! sensillum campaniformium
intersection_of: part_of FBbt:00004644 ! femur
created_by: sr544
creation_date: 2010-10-21T10:30:17Z

[Term]
id: FBbt:00007061
name: baso-posterior adult midbrain
def: "." [FBC:JR, FBC:VH]
comment: Obsoleted in the processes of making the ontology consistent with Ito et al.  (2014). This term was never properly defined, so no precise replacement term can be suggested.
is_obsolete: true
consider: FBbt:00110636

[Term]
id: FBbt:00004478
name: foramen
def: "An aperture in some gross body part. Most commonly used for apertures in the exoskeleton, but also used for internal structures such as the esophageal foramen of the brain." [FBC:DOS, FBC:SR, FBC:gg]
subset: cur
subset: FB_gloss
is_a: FBbt:00007017 ! anatomical space
relationship: part_of FBbt:00005396 ! adult integumentary system

I can raise with FlyBase the question of adding the FBC refs somewhere. I think it's a good idea, but it might take some time to have it implemented in FlyBase DB if accepted. I don't know if @dosumis had raised this question before?

Re:FBC in synonyms
I still think it would be better to have them look the same as the definition ones as you land on a page. Most people won't hover it to realise it is the same person.  

FlyBase Curator [Simon Reeve]  instead of (FBC:SPR)

What do others think?

**Comment by dosumis** [comment]
For this release we only show FlyBase / ontology curators.
