### ISSUE TITLE
Individual's references

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#383]
There seem to be individuals that have PubMed refs in the definition but then not listed as refs?

example: http://vfbdev.inf.ed.ac.uk/site/tools/view_stack/3rdPartyStack.htm?type=THIRD_PARTY_STACK&tpbid=VFB_00003321&json=FlyCircuit2012/TH-M-200094/wlz_meta/tiledImageModelData.jso

Definition: A neuron expressing P{ple-GAL4.F} that is part of an adult brain from Chiang et al., 2010 (PMID:21129968).

The PubMed has a related FlyBase ref: FBrf0212704 but not in OWL definition.

How should we handle these?

I could scan for PMIDs and add ref links (wouldn't be able to get miniref) or should this be resolved at the OWL side?

**Comment by dosumis** [comment]
Yep.  Did this becuase I knew that the implementation of display of references for anatomical classes couldn't work for individuals given that they are not loaded into FlyBase.   Now you've changed reference handling I can implement properly. I'll change this in the next release of the individuals files.

**Comment by dosumis** [comment]
Can also switch PMIDs to FBrfs when I do it.  (Used PMIDs in text  of defs because I thought users more likely to know what they are.)

**Comment by Robbie1977** [comment]
I've just asked a question about this in #380 as there are FBrfs used in some definitions so might be good to add before miniref in references.

**Comment by Robbie1977** [comment]
If you put in FBrfs I could easily resolve to the shorter miniref or do you want to do at OWL creation?

**Comment by Robbie1977** [comment]
Do any individuals have refs?

Trying to test new individual bean refs works ok.

**Comment by dosumis** [comment]
Don't think so.  I can work on a test file for you this afternoon.

**Comment by Robbie1977** [comment]
no urgent rush just need to check it works ok before we push live.

**Comment by Robbie1977** [comment]
FYI PubMed id's are now also handled correctly along with ISBNs

**Comment by Robbie1977** [comment]
I've pushed the latest version to your sandbox server so you can try the new individuals OWL file when you want.

**Comment by Robbie1977** [comment]
@dosumis do you have a new individual file to test? sandbox is all ready for it.

**Comment by dosumis** [comment]
> @dosumis do you have a new individual file to test? sandbox is all ready for it.

Now building on Jenkins.  Currently uses PMIDS, as this is what is in the DB.  Can switch these to FBrfs easily enough.

**Comment by dosumis** [comment]
Here's the ref list from the DB:

mysql> select name, pub_pmid from data_source

| name               | pub_pmid |
|--------------------|:----------:|
| Yu2013             | 23541733 |
| Ito2013            | 23541729 |
| Cachero2010        | 20832311 |
| Chiang2010         | 21129968 |
| Knowles-Barley2010 |     NULL |
| Jenett2012         | 23063364 |
| CostaJefferis      |     NULL |

@mmc46 
CostaJefferis is a placeholder for clusters.  Can I map this to an FBrf yet?

**Comment by mmc46** [comment]
No, not yet.

**Comment by Robbie1977** [comment]
happy with PMIDs for now

**Comment by Robbie1977** [comment]
New standard ontology viewer has replaced the individual special page - let me know if anything is missing on #424 and fingers crossed refs should just work when you add them.
Already pushed to Sandbox.

PMID links resolve however as they are technically not provided as refs this currently flags an error in the log as I assume normally these should be in the proper ref section as well as text.

**Comment by Robbie1977** [comment]
Working as expected http://vfbsandbox.inf.ed.ac.uk/site/tools/view_stack/3rdPartyStack.htm?tpbid=VFB_00003321

Would be good to switch to FBrfs so that the minirefs resolve but this will just work when the individuals owl is updated.
