### ISSUE TITLE
ISBN refs not showing

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#387]
ISBN isn't showing in definition ref. 
I've only checked a few terms with ISBN, but none of them showed the ref.

name: posterior tract of the ventral body
def: "Longitudinal tract of the adult midbrain connecting the ventral body and central complex to the inferior medial/lateral protocerebrum." [FBC:VH, ISBN:978-3-540-07343-7]

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00007086&name=posterior%20tract%20of%20the%20ventral%20body

**Comment by Robbie1977** [comment]
I'll add ISBNs to the resolved refs under #385

**Comment by Robbie1977** [comment]
@mmc46 ISBN's now resolve - If you're happy with ref wording then close the ticket otherwise let me know what you'd like instead.
