### ISSUE TITLE
Problems with free text references in FlyBase 

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#392]
As I'm now checking text for refs I've spotted a typo and alot of FlyBase raw refs.

There are 22 'et al' missing the '.' after al - A large number being: '(Benton et al, 2009)' 
Easy to find just search for 'et al,'

Spacing of ref (appears twice) '(von Hilchen ,2008)'
Search for ',20'

6 missing spaces with 19xx dates e.g. '(Heisenberg et al.,1978)'
Search for ',19'

18 uses of 'at al' rather than 'et al'
Search for 'at al'  

There are also 45 FBrf in plain text in definitions or comments a few are probably correctly there as the ref is used outside bracket and FBrf in bracket. Just need to decide what the standard is as @dosumis wanted them all as minirefs?

I'm going to try and handle them as is but could probably do with correction in FlyBase eventually to avoid over processing.

**Comment by mmc46** [comment]
Corrected: There are 22 'et al' missing the '.' after al; Spacing of ref; missing spaces with 19xx dates; 
uses of 'at al' (there was only one, the others are correct text).

45 FBrf in plain text in definitions or comments: I've corrected these. Most of these were in the comment of obsolete terms without a definition. I deleted the FBrf and left the mini citation.

**Comment by Robbie1977** [comment]
@mmc46 With the mimirefs did you put the year in brackets?

**Comment by mmc46** [comment]
I put the whole mini ref in brackets when in the comment (for those which don't have a definition).

**Comment by Robbie1977** [comment]
Great - again that should all work.

**Comment by Robbie1977** [comment]
@mmc46 There is only one FBgn ref that is in square brackets so I'm assuming this is a typo as all others are in normal brackets? 
it's [FBgn0000422]

not a problem either way but thought I'd flag it.

**Comment by mmc46** [comment]
Corrected [FBgn0000422].
