### ISSUE TITLE
Bug with VFB_00002572

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#399]
No thumbnail or image file.

Support info:
http://vfbdev.inf.ed.ac.uk/site/tools/view_stack/3rdPartyStack.htm?json=FlyCircuit2012/GH146-M-000000/wlz_meta/tiledImageModelData.jso&type=THIRD_PARTY_STACK&tpbid=VFB_00002572
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36

**Comment by mmc46** [comment]
This is one of the bad images (for which registration didn't work). The set of good images (16129) is on here.

http://flybrain.mrc-lmb.cam.ac.uk/vfb/fc/good_images.txt

It would be better if only the good images are included in the individuals file.

**Comment by dosumis** [comment]
Removed badly registered individuals from build.  See comments on #310 for relevant SQL.
