### ISSUE TITLE
Add linkouts to FlyBrain NDB neuron pages

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#4]
Add links-outs to FlyBrain NDB.

These can be rolled from xrefs attached to terms:

e.g.

\[Term\]
id: FBbt:00003650
name: ring neuron R1
...
xref: FlyBrain\_NDB:10260

-&gt;
http://flybrain-ndb.iam.u-tokyo.ac.jp/fmi/xsl/browserecord.xsl?-lay=NDB&Accession+number=10260&-find=-find

**Comment by Robbie1977** [comment]
I've added the links to the end if the references links.
See example: http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00003650&name=ring%20neuron%20R1

Let me know if any objections to wording or positioning etc otherwise If everyone is happy I can push this live with the latest fixes?

**Comment by dosumis** [comment]
Excellent!  Great to see these finally.  Perhaps better to place at bottom with other linkouts (FlyBase and NeuroLex)?  The references in the list are those used to define the term, this is not the case for the neuronNDB xref.

How about adding a new linkouts heading for the link section? The links could use pngs of logos from the linked resources for linkouts.  I never liked the text for the links to FB and NeuroLex.

**Comment by Robbie1977** [comment]
I'm actually getting them from the synonym refs so it kind of works but happy to move down and tidy up the external links, agreed they are rather a word jam at the moment.

**Comment by Robbie1977** [comment]
Are there any other refs we could be using haven't spotted any others but let me know as always good to use?

**Comment by jefferis** [comment]
@Robbie1977 great to have these linkouts working! 

> How about adding a new linkouts heading for the link section? The links could use pngs of logos from the linked resources for linkouts. I never liked the text for the links to FB and NeuroLex.

This seems reasonable to me as well.

**Comment by dosumis** [comment]
Probably not any different, but you can get them straight from the xrefs.  Should be an obvious method on the OWLGraphWrapper to grab lists of these.

> Are there any other refs we could be using haven't spotted any others but let me know as always good to use?

Can't think of any offhand. Marta (@mmc46) can you?

**Comment by mmc46** [comment]
Not any that would be of any use.

**Comment by dosumis** [comment]
BTW - if you're processing synonym xref lists, we could easily turn the results into reference links on synonyms - something I always wanted to do.  If others agree this is worth doing, I'll make another ticket for it.

**Comment by mmc46** [comment]
Yes, that would be useful.

**Comment by Robbie1977** [comment]
How about this version:
http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00003652&name=ring%20neuron%20R3

**Comment by dosumis** [comment]
I like it.  Great to see reference links too!

May be worth tweaking a little.  Perhaps number all refs, rather than just ones used in synonyms?  Also wondering if possible to make it clearer that the External Links subhead refers to the links below it.  Adding an addition blank line before this subhead might help.

Cheers,
David

**Comment by mmc46** [comment]
I agree with David, either numbering all or none. A reference might be used for both the definition and synonyms, and that’s currently not reflected. 

I can see a bug, in that it is attributing refs to synonyms that don’t have them. 
For FBbt:00100219, dopaminergic PPL1 neuron, only the first synonym (PPL1) should be attached to the ref Mao and Davis (2009), but it’s showing all synonyms with that ref.

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00100219&name=dopaminergic%20PPL1%20neuron

**Comment by Robbie1977** [comment]
Fixed and made the referencing more consistent with the description referencing.

**Comment by mmc46** [comment]
It’s better Rob, thanks, but still needs tweaking.
For example in

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00110282&name=VO3%20motor%20neuron

the synonym MN28-Ib doesn’t show the ref (FBrf0132289 == Hoang and Chiba, 2001, Dev. Biol. 229(1): 55--70) when it should. Is that because it is not one of the definition refs? There are many cases like these, when refs are only used for synonyms.

I think to clearly show which refs are used for the definition and which ones are used for the synonyms it would be better to show them both at the end of the definition and synonyms (like you have now).  Either as mini citations or superscript numbers.


On the external links to FlyBrain, these are not resolving, I’m getting an error 956. None of the links on their site for the neuron data section (and strain/antibody data section) is working. Would it be worth checking if this is something temporary and that they are aware of it?

**Comment by dosumis** [comment]
### Some background

In the ontology file, references on the definition, which we currently display under 'references' are only those used in defining the class.  The full list of relevant references that mention the class is much longer. In as far as this is curated, this list could be pulled from FB via a query.  I'd like to do this in future, but maybe worth keeping for the new site.  Some of these additional refs are sources of synonyms (hence cases where a reference on a synonym is not currently displayed on VFB).  I think it is worth keeping synonym refs and def refs separate.

The current code for looking up references uses the representation of the ontology embedded in the FlyBase DB.  The latest work is instead directly parsing information coming from the OWL files (via the results of GraphWrapper method calls).

### Suggested new spec

New subhead:  __Defining references__ - has only refs from the definition
New subhead:  __Synonym references__ - has only (and all) references on synonyms

Modifications to code:  For both reference lists, we should parse the list that comes from GraphWrapper method calls.  This requires some RegEx to sort the types of reference (FBrf etc).  A simple query pulls pub miniref from FlyBase using FBrf extracted from the ref.
 
Apologies for the evolving spec...

### For links to FlyBrain Neuron DB: 

I think the main problem is that FlyBrain Neuron DB is very unstable.  E.g. link on [Ring neuron R3](http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00003652&name=ring%20neuron%20R3)  was working, but currently giving an error.  We may be able to script something that detects this and informs someone in Kei's lab to restart servers etc.

**Comment by Robbie1977** [comment]
BTW what should we do with the FlyBaseCurator refs (FBC:gg) - I'm assuming ignore?

**Comment by dosumis** [comment]
Not a high priority, but one option for the FB curator refs is to link to the orcid for the relevant curator (where we have one).  I thought we already had these for Marta and myself in the release files, but looks like they've gone astray.  This could be very useful for giving expert contributors credit.

**Comment by mmc46** [comment]
Yes, it would be good to link these to the ORCID.

But for now, I always like to see the refs, even if it is an FB curator.

**Comment by dosumis** [comment]
The problem with just showing the initials is no-one else will have a clue what they are.  So, I'm not in favor of displaying these.  Most FlyBase curators should have ORCIDS by now.  I'll make a new ticket for this, as think we've has more than enough scope creep on this ticket.

**Comment by dosumis** [comment]
Orcid link ticket: #380

**Comment by Robbie1977** [comment]
See if you can find some that break this version.
Same examples with FBC, direct web and FlyBrain_NDB refs:
http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:10005220&name=embryonic%20secondary%20branch
http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00110282&name=VO3%20motor%20neuron

**Comment by mmc46** [comment]
Is this still on references and refs on synonyms?

There’s a FB ref that’s not showing the mini citation.

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00007055&name=superior%20medial%20protocerebrum

**Comment by Robbie1977** [comment]
Well spotted - Using the pub table direct so issue resolving resolved.
