### ISSUE TITLE
Showing the type of synonym

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#409]
There are different types of synonyms

EXACT
NARROW
RELATED
BROAD

The type of synonym is shown as below in the ontology
For id: FBbt:00005909

synonym: "DM tract" EXACT []
synonym: "DMT" RELATED []
synonym: "dorsomedial 1 fascicle" EXACT [FlyBase:FBrf0160715]
synonym: "M1" RELATED []

It would be good if the type of synonym could be shown on the site, in the synonym section.

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00005901&name=CL%20fascicle

**Comment by dosumis** [comment]
Can get this using the OWLGraphWrapper

**Comment by Robbie1977** [comment]
@dosumis is there a ref we could link to that explains the different types for laymen?

**Comment by Robbie1977** [comment]
Think I've covered it with hover-over text.
