### ISSUE TITLE
individual details are being called direct via jsp rather than resolved to html

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#424]
This is prevent all the resolution from ontbean processing from being applied.

Rather than duplicating all this functionality we should incorporate the individuals display into ont_bean.html function.

**Comment by dosumis** [comment]
Sounds odd.  Could you give more details?

It should be possible to simplify the code alot.  There's really only one major difference between TermInfo  for Individuals vs Classes.

**Comment by Robbie1977** [comment]
Shouldn't be a problem to resolve as you say very similar just been set up weirdly.
