### ISSUE TITLE
Move to new image name/path schema

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#440]
Provisional plan:

image links will work as

http://www.virtualflybrain.org/owl/VFBi_00005678  <- Can't be done for now as NTFS and tomcat won't allow.
http://www.virtualflybrain.org/owl/VFBi_00005678/thumbnail.png  <- thumbnail view
http://www.virtualflybrain.org/owl/VFBi_00005678/volume.nrrd <- already compressed and already there.
http://www.virtualflybrain.org/owl/VFBi_00005678/woolz.nrrd
http://www.virtualflybrain.org/owl/VFBi_00005678/index.html <- link to default view (centred on brightest signal)
http://www.virtualflybrain.org/owl/VFBi_00005678/source.html <- provides link to individual data for attribution.
http://www.virtualflybrain.org/owl/VFB_00005678 <- provides (backwards compatable) symlink to VFBi_00005678/index.html 

Note - may be some issue getting this schema to work with image viewer in Protege - check!

Image ID is not for an individual image file - but for a more abstract concept of image: One that ties two or more channels together - where one is a background channel (a template) and the others are signal channels.  Channel has some metadata about how image was collected, stained, imaged etc.

OWL query 1: finds anatomical individual
OWL query 2: finds channel depicting individual (<- could be SPARQL)
OWL query 3: Finds image corresponding to channel - registered to some specified template. (<- Could be SPARQL)

Note - we may not bother to use metadata on the channel until VFB 2.0

Work to do:

1. Add channel and image classes + depicts and has_channel/channel_of
2. Generate channel and image IDs for all
3. What to do about source links?
    - There is a data redundancy issue here.  For denormalised representation, it should only be linked to one.  For now at least, this will be the anatomical individual, although it probably makes more sense for this to be the channel.
4. Make FACT table linking individual anatomical structures, channels and images.

**Comment by Robbie1977** [comment]
Done for all existing stacks on vfbdev and ready to be deployed:
http://www.virtualflybrain.org/owl/VFBi_00010001/index.html << now only needs the VFBid to open a third party stack (no longet needs type of json as now all fixed)
Can't get the folder to link directly at the moment (wasted enough time on it for now) but the old refs still work for that:
http://www.virtualflybrain.org/owl/VFBi_00010001
http://www.virtualflybrain.org/owl/VFBi_00010001/thumbnail.png << all thumbnails are now using these

Download links I'll add later

We need to resolve individuals from OWL as it all comes from DB at the moment. #442

**Comment by dosumis** [comment]
Working on LMB DB representation.  But also need to extend scripts to turn this into OWL.

Note - realised that we don't have BrainTrap individuals in DB.  Will add them.

**Comment by dosumis** [comment]
(Note - the following is mostly for my own record)

Progress:  
 * channel & image individuals + facts linking them are now in place for all anatomical individuals + JFRC2010 template. 
 * Code in place to read owl_fact table to OWL

Still to do: 
 * More work needed on typing for new individuals + metadata on channels.
 * Gen individuals by source needs to work better with pulling info on templates
 * Code for adding new individuals needs updating to reflect new system.

**Comment by Robbie1977** [comment]
http://www.virtualflybrain.org/owl/VFBi_00005678 <- Can't be done for now as NTFS and tomcat won't allow.
Ideally can you use: http://www.virtualflybrain.org/owl/VFBi_00005678/index.html or http://www.virtualflybrain.org/owl/VFB_00005678 (means lots of symlinks - ideally like to phase out long term).

**Comment by dosumis** [comment]
Didn't realise you'd switched over to the new image paths already.  As OWL queries for this are not yet in place, you can only be doing this using regex - which has to be a temorary hack. The point of having separate image IDs (perhaps better to call this registration context IDs?) is to ultimately allow for many:many 'anatomical individual':image individual'.   In the near future, we will certainly have many:1.

We also need to be careful of replicating relationships in URL paths.

I can see that I haven't been paying enough attention to the relationship of the OWL abstractions to details of resolvable paths.  I'll work on a full spec for this ASAP - including a draft of how it can work with SOLR.
