### ISSUE TITLE
Pull Thirdparty Beans from OWL

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#442]
currently pulling from VFB DB but all data should be accessible from OWL files.
ref:
VFB/src/uk/ac/ed/vfb/service/ThirdPartyBeanManager.java

**Comment by Robbie1977** [comment]
Thirdparty Bean with FB ref called from
VFB/src/uk/ac/ed/vfb/service/GeneBeanManager.java

**Comment by Robbie1977** [comment]
VFB Thirdparty Beans called from:
src/uk/ac/ed/vfb/composite/web/CompositeViewController.java 
jsp/includes/bits/credits3party.jsp 
src/uk/ac/ed/vfb/service/OntBeanManager.java

**Comment by Robbie1977** [comment]
Pulling everything except the source details - see #461

**Comment by dosumis** [comment]
Working on source details.  In order to retire the VFB DB,  you will also need a way to display only full expression patterns in expression query results.  This information is now in the OWL, but, AFAIK, the site is still dependent on a hack using the VFB DB.

**Comment by Robbie1977** [comment]
The expression boolean seems to only be there to mark the BrainTrap ones as they don't actually have images (as yet) so hopefully that problem should solve itself.

This probably needs another issue raised as not sure we would show 'normal' individuals showing transgenes at present?

**Comment by dosumis** [comment]
Source details now in OWL.  See #461
