### ISSUE TITLE
Menu bar is not appropriate to individual?

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#485]
Investigate and probably remove 

Support info:
http://www.virtualflybrain.org/site/tools/anatomy_finder/index.htm?id=VFB_00000001&name=fru-M-200266
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by dosumis** [comment]
Hmmm... Not sure how this could be happening.  My first thought was that the setup scripts that determine term classification may be runnning against the individuals files.  But even if that were the case, the scripts would need to use a different method to call individuals to the one used to find classes.  Second thought - this is the default menu, are all individuals now getting this default?  Perhaps to do with work to merge individual and class beans?

**Comment by Robbie1977** [comment]
I know why it's occurring (just a reminder to remove)

But are there really no valid query we might want to do against individuals?
