### ISSUE TITLE
Updating to FB2015_01

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#490]
FYI FlyBase updated the current directory link some time last night so the dev servers picked it up first thing this morning and have been processing for just under 8 hours so should be going live on blanik any time now so dev, sandbox & sandbox1. 

Bocian is a few hours behind (sandbox2, 3, main site backup [vfb-bocian.inf.ed.ac.uk]).

The main site is scheduled to start loading at 8pm this evening so will go live in the early hours.

If you notice any problems on the dev sites please flag asap so I can halt the main site update.

**Comment by Robbie1977** [comment]
http://vfbdev.inf.ed.ac.uk/
http://vfbsandbox.inf.ed.ac.uk/
http://vfbsandbox1.inf.ed.ac.uk/
are live with FB2015_01

**Comment by Robbie1977** [comment]
@mmc46 any obvious changes to check for?

**Comment by Robbie1977** [comment]
Complete on Bocian:
http://vfbsandbox2.inf.ed.ac.uk/
http://vfbsandbox3.inf.ed.ac.uk/
http://vfb-bocian.inf.ed.ac.uk/

**Comment by mmc46** [comment]
This name change on the ontology should come through:

FBbt:00045018 mushroom body medial lobelet

was  mushroom body beta accessory calyx fibers

Still old name shown in the 3 servers:

http://vfbsandbox2.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00045018&name=mushroom%20body%20medial%20lobelet

http://vfbsandbox3.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00045018&name=mushroom%20body%20medial%20lobelet

http://vfb-bocian.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00045018&name=mushroom%20body%20medial%20lobelet

In the footer it says it's using 


http://purl.obolibrary.org/obo/fbbt/fbbt-simple.owl

**Comment by dosumis** [comment]
Important to use the dated PURL so that we don't update before FB:
http://purl.obolibrary.org/obo/fbbt/2014-11-07/fbbt-simple.owl

For each release, we need a mechanism in place to communicate which ontology version we should be using.

**Comment by dosumis** [comment]
Unfortunately, I don't think this can be pulled from the DB.

**Comment by dosumis** [comment]
Rebuilding individuals now.  Has to be done locally as broken on Jenkins due to lib problems.
Will push new OWL files to sandbox shortly.

**Comment by dosumis** [comment]
Done

**Comment by Robbie1977** [comment]
Let me know when you're happy and I can push live when we get a dip in
users.

**Comment by dosumis** [comment]
Can see the change on the sandbox
http://vfbsandbox.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00045018&name=mushroom%20body%20beta%20accessory%20calyx%20fibers%20(synonym)

@mmc46  - can you do some more testing?

**Comment by mmc46** [comment]
I’m getting a 

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by mmc46** [comment]
The new terms seem to be there. Though there seems to be some one relationship missing for the ones I checked:

For  alpha/beta core Kenyon cell and alpha/beta surface Kenyon cell, the relationship 

has_presynaptic_terminal_in mushroom body calyx 

isn't shown on the site, though it's in the owl file. 

http://vfbsandbox.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00110929&name=alpha%2Fbeta%20core%20Kenyon%20cell

Other, existing terms I've checked seem ok.

**Comment by dosumis** [comment]
No idea why that would be. Are you sure these are in http://purl.obolibrary.org/obo/fbbt/2014-11-07/fbbt-simple.owl ?

**Comment by mmc46** [comment]
![alpha_beta_corekc_rel_missing](https://cloud.githubusercontent.com/assets/1872083/6509006/3d5f0c72-c354-11e4-9d39-0194ca701b7d.jpg)

**Comment by dosumis** [comment]
Hmmm - may be a more general parsing issue.  That code has been worked on recently I think.  Need to be careful we don't get bogged down in making and squashing bugs on our old code base...

**Comment by Robbie1977** [comment]
Sorry the restarts were me - trying to opitimise restart time so we have no downtime on live site update.

Investigating the missing relationships as it's definatly there: http://vfbdev.inf.ed.ac.uk/do/ont_bean_list.html?action=presynaptic&id=FBbt:00003685

**Comment by Robbie1977** [comment]
FYI - It's due to the code only envisaging one interrelationship hence the post overwrites the pre relationship. Working on a fix.

**Comment by Robbie1977** [comment]
Fixed - now no limit on how many relationships can be associated to a single anatomy term from another or individual for that matter.

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00110929&name=alpha%2Fbeta%20core%20Kenyon%20cell

**Comment by Robbie1977** [comment]
Please check and flag any issues - would still like to get live ASAP (tomorrow afternoon)?

**Comment by dosumis** [comment]
Excellent.  That was quick.

**Comment by mmc46** [comment]
FlyCircuit images not shown, at least for adult antennal lobe projection neurons. Compare dev site 

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00100389&name=adult%20antennal%20lobe%20projection%20neuron%20DL2d%20adPN

with current release

http://www.virtualflybrain.org/site/tools/anatomy_finder/index.htm?id=FBbt:00100389&name=DL2d%20adPN%20(synonym)

Other neuron types, like AMMC-AMMC PN1are showing the images fine.

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00110629&name=AMMC-AMMC%20PN1%20(synonym)

**Comment by Robbie1977** [comment]
Seems to be due to reclassification:
http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=VFB_00004524&name=fru-F-000079
Parent classes: 
    * uniglomerular antennal lobe projection neuron

Is this correct?

**Comment by mmc46** [comment]
Something as gone wrong with the classification of the individuals, @dosumis might know where.

**Comment by dosumis** [comment]
My fault.  Local run of the individual build job incorrectly used the -simple version of the ontology, which lacks the axiomatisation needed for the inferences we need.  Re-running now.  Will post shortly.

We need to make it a priority to get the Jenkins build job running again, along with automated reports and tests of the owl files.  Code is in place  - just need to work on the Jenkins setup.

**Comment by dosumis** [comment]
Fixed individual files now on sandbox server branch.

**Comment by dosumis** [comment]
... or will be once I manage to sync from slow meeting wifi.

**Comment by Robbie1977** [comment]
This seems to be working now (on vfbsandbox.inf.ed.ac.uk) so I'll push over to the other dev servers.

Any objections to it going live?

**Comment by mmc46** [comment]
I was trying to check at

http://vfbdev.inf.ed.ac.uk/site/vfb_site/home.htm

but the autocomplete isn't working, so can't run the query. Any ideas?

**Comment by Robbie1977** [comment]
Should be fine now.

**Comment by mmc46** [comment]
Fine by me to go live.

**Comment by mmc46** [comment]
Found a bug. 

Query for neuron images (clustered)

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt:00003748&name=medulla

doesn't find any records

http://vfbdev.inf.ed.ac.uk/do/cluster_list.html?action=cluster_found&id=FBbt:00003748

There should be some, see main site

http://www.virtualflybrain.org/do/cluster_list.html?action=cluster_found&id=FBbt:00003748

**Comment by Robbie1977** [comment]
The individual owl data does seem a tad light:
Original:
Declaration(NamedIndividual(<http://www.virtualflybrain.org/owl/VFB_00007506>))
AnnotationAssertion(rdfs:label <http://www.virtualflybrain.org/owl/VFB_00007506> "Cha-F-000067"^^xsd:string)
AnnotationAssertion(Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "PMID:21129968"^^xsd:string) <http://purl.obolibrary.org/obo/IAO_0000115> <http://www.virtualflybrain.org/owl/VFB_00007506> "A neuron expressing P{Cha-GAL4.7.4} that is part of an adult female brain"^^xsd:string)
AnnotationAssertion(rdfs:comment <http://www.virtualflybrain.org/owl/VFB_00007506> "From analysis of a registered 3D image, this neuron is predicted to overlap the following neuropils: 2621 voxels overlap the medulla."^^xsd:string)
ClassAssertion(<http://purl.obolibrary.org/obo/FBbt_00005106> <http://www.virtualflybrain.org/owl/VFB_00007506>)
ClassAssertion(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/FBbt_00003624>) <http://www.virtualflybrain.org/owl/VFB_00007506>)
ClassAssertion(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/FBbt_00007011>) <http://www.virtualflybrain.org/owl/VFB_00007506>)
ClassAssertion(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002131> <http://purl.obolibrary.org/obo/FBbt_00003748>) <http://www.virtualflybrain.org/owl/VFB_00007506>)
ClassAssertion(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002292> <http://flybase.org/reports/FBtp0014830>) <http://www.virtualflybrain.org/owl/VFB_00007506>)
ObjectPropertyAssertion(<http://purl.obolibrary.org/obo/RO_0002350> <http://www.virtualflybrain.org/owl/VFB_00007506> <http://www.virtualflybrain.org/owl/VFB_00017239>)
ObjectPropertyAssertion(<http://purl.obolibrary.org/obo/c099d9d6-4ef3-11e3-9da7-b1ad5291e0b0> <http://www.virtualflybrain.org/owl/VFB_00007506> <http://www.virtualflybrain.org/owl/VFB_00017239>)
ObjectPropertyAssertion(<http://purl.obolibrary.org/obo/C888C3DB-AEFA-447F-BD4C-858DFE33DBE7> <http://www.virtualflybrain.org/owl/VFB_00017239> <http://www.virtualflybrain.org/owl/VFB_00007506>)
ObjectPropertyAssertion(<http://purl.obolibrary.org/obo/RO_0002351> <http://www.virtualflybrain.org/owl/VFB_00017239> <http://www.virtualflybrain.org/owl/VFB_00007506>)

new:

    <owl:NamedIndividual rdf:about="http://vfbdev.inf.ed.ac.uk/owl/VFB_00007506">
        <owl:annotatedSource rdf:resource="http://vfbdev.inf.ed.ac.uk/owl/VFB_00007506"/>
        <obo:C888C3DB-AEFA-447F-BD4C-858DFE33DBE7 rdf:resource="http://vfbdev.inf.ed.ac.uk/owl/VFB_00007506"/>
        <obo:RO_0002351 rdf:resource="http://vfbdev.inf.ed.ac.uk/owl/VFB_00007506"/>

**Comment by mmc46** [comment]
There seems to be a problem with the individuals file.
I've checked some of the neurons that should show up for this query:fru-M-900003, fru-M-900041, fru-M-900050, Gad1-F-000020, Gad1-F-100034. 
They have the medulla annotation, but also have an extra property assertion (for which cluster they're from), in addition to the correct one, that is not really a property and has been introduced by some kind of error I think (see below). And it's messing up the query. 

![individual_flycircuit_plus](https://cloud.githubusercontent.com/assets/1872083/6695410/e93b502c-ccd8-11e4-9fda-c9483c70204f.jpg)

There are 2 of these error properties, each with 1062 uses, so it's more widespread than just for the medulla neurons. And a similar query for ellipsoid body shows the same 0 results.

**Comment by dosumis** [comment]
The OWL is correct, it is just missing the labels for a couple of object properties, exposing the UUIDs used for the shortFormID for these.  I've tested the clustered image queries  on the OWL file, including the one for the medulla) and they works fine.  Query fail looks like something we've fixed before, so I checked that the query code.  [This looks fine too](https://github.com/VirtualFlyBrain/VFB/blob/09d461dda7a88ccd796452cf1e835321f908d8fb/src/uk/ac/ed/vfb/web/WebQueryUtils.java#L17).  So, don't know what's going on.

**Comment by mmc46** [comment]
Yes, you're right. Well, it's something to do with clusters, because the unclustered query works fine.

**Comment by Robbie1977** [comment]
Sorry but it's definitely a change somwhere in the OWL causing an issue in either the simple or individuals as just recovered the issue on http://vfb-bocian.inf.ed.ac.uk/do/cluster_list.html?action=cluster_found&id=FBbt:00003748 by just copying the old versions off the live site.

**Comment by Robbie1977** [comment]
Output from debug run:

2015-03-25 23:59:11,387 (vfbsandbox.inf.ed.ac.uk) INFO [uk.ac.ed.vfb.dao.client_server.Server:139] Query: individual&c099d9d6-4ef3-11e3-9da7-b1ad5291e0b0 some (VFB_10000005 that C888C3DB-AEFA-447F-BD4C-858DFE33DBE7 some (FBbt_00005106 that RO_0002131 some FBbt_00007401))

2015-03-25 23:59:11,387 (vfbsandbox.inf.ed.ac.uk) DEBUG [uk.ac.ed.vfb.dao.client_server.server_includes.DLQueryServer:70] Asking Query: individual&c099d9d6-4ef3-11e3-9da7-b1ad5291e0b0 some (VFB_10000005 that C888C3DB-AEFA-447F-BD4C-858DFE33DBE7 some (FBbt_00005106 that RO_0002131 some FBbt_00007401))

2015-03-25 23:59:11,387 (vfbsandbox.inf.ed.ac.uk) DEBUG [uk.ac.ed.vfb.dao.client_server.server_includes.DLQueryServer:93] running: uk.ac.ed.vfb.dao.client_server.server_includes.DLQUeryEngineBrainInd@3c94026e

2015-03-25 23:59:11,387 (vfbsandbox.inf.ed.ac.uk) DEBUG [uk.ac.ed.vfb.dao.client_server.server_includes.ADLQueryEngine:38] currExpr: c099d9d6-4ef3-11e3-9da7-b1ad5291e0b0 some (VFB_10000005 that C888C3DB-AEFA-447F-BD4C-858DFE33DBE7 some (FBbt_00005106 that RO_0002131 some FBbt_00007401))

2015-03-25 23:59:11,675 (vfbsandbox.inf.ed.ac.uk) INFO [uk.ac.ed.vfb.dao.client_server.server_includes.DLQueryServer:98] DLQueryServer returning 0 result(s)

**Comment by Robbie1977** [comment]
Why is the cluster definition so different:
old individual:
```
[blanik]jenkins: cat /partition/bocian/tomcat/fly/webapps/vfb/resources/fbbt_vfb_ind_pr_nr.owl | grep VFB_10000005
Declaration(Class(<http://purl.obolibrary.org/obo/vfb/VFB_10000005>))
AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/vfb/VFB_10000005> "cluster")
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016830>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016831>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016832>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016833>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016834>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016835>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016836>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016837>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016838>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016839>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016840>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016841>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016842>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016843>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016844>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016845>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016846>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016847>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016848>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016849>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016850>)
ClassAssertion(<http://purl.obolibrary.org/obo/vfb/VFB_10000005> <http://vfb-bocian.inf.ed.ac.uk/owl/VFB_00016851>)
...
```

new individual:
```
[blanik]jenkins: cat resources/fbbt_vfb_ind_pr_nr.owl | grep VFB_10000005
    <!-- http://purl.obolibrary.org/obo/vfb/VFB_10000005 -->
    <owl:Class rdf:about="http://purl.obolibrary.org/obo/vfb/VFB_10000005">
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/vfb/VFB_10000005"/>
...
```

**Comment by dosumis** [comment]
Old is functional syntax. New = rdf xml.  Both are valid OWL syntaxes.  I prefer to use functional as more readable and makes for much smaller files. Changed because functional syntax conversion failing for reasons I don't understand.  (Note - functional syntax assertions can be read in isolation, so grep is appropriate.  For obvious reasons, this is not true of the XML.

Original functional syntax has odd URIs.  I have no idea where this base came from 'http://vfb-bocian.inf.ed.ac.uk/owl' !  Shouldn't maker a difference to queries though, as all queries now go through elk, which returns short form ID strings - not OWL entities.  Might make a difference to rolling beans.  Would have to check code.

**Comment by Robbie1977** [comment]
The base change is me - ensure ontologies on test servers only ref the test
servers.

would it be worth testing a functional version of the individuals to check
brain isn't having issues with the format?

**Comment by dosumis** [comment]
Found the problem.  Two different versions of exemplar relations with different base URIs.  This confused Protege so that queries worked at least some of the time.   Should be fixed in uploaded file on Sandbox-Server.  Now working on finishing script that tests all query types _before_ new builds are uploaded.

Also has new version IRI http://purl.obolibrary.org/obo/fbbt/vfb/2015-03-26/fbbt_vfb_ind_pr_nr.owl. You can extract the version for display on the site, just as for fbbt-simple.owl.

**Comment by Robbie1977** [comment]
can you re-add to the sandbox as the file seems to always get mangled when git tries to merge your fork with the existing.

I can't deploy from jenkins as the VFB_owl copy hasn't been updated - There is a deployment script that works to load the individuals file from VFB_owl to sandbox safely.

I've added a git attributes file to prevent merging of the owl files so if you pull the latest copy then reapply your new version it should work.

**Comment by dosumis** [comment]
I'll post a compressed version on VFB_owl.

**Comment by Robbie1977** [comment]
Ok maybe it wasn't mangled as getting the same error:
```
2015-03-27 14:30:08,342 (vfbsandbox.inf.ed.ac.uk) DEBUG [uk.ac.ed.vfb.dao.client_server.server_includes.DLQueryServer:53] Creating Brain Ind reasoner....

2015-03-27 14:30:08,343 (vfbsandbox.inf.ed.ac.uk) DEBUG [uk.ac.ed.vfb.dao.client_server.server_includes.ADLQueryEngine:48] Loading ontology for: class uk.ac.ed.vfb.dao.client_server.server_includes.DLQUeryEngineBrainInd...
Exception in thread "main" java.lang.NoSuchMethodError: org.semanticweb.owlapi.io.UnparsableOntologyException.(Lorg/semanticweb/owlapi/model/IRI;Ljava/util/Map;)V
at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:236)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:829)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:775)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:788)
at uk.ac.ed.vfb.dao.client_server.server_includes.ADLQueryEngine.(ADLQueryEngine.java:51)
at uk.ac.ed.vfb.dao.client_server.server_includes.DLQUeryEngineBrainInd.(DLQUeryEngineBrainInd.java:21)
at uk.ac.ed.vfb.dao.client_server.server_includes.DLQueryServer.(DLQueryServer.java:54)
at uk.ac.ed.vfb.dao.client_server.Server.init(Server.java:82)
at uk.ac.ed.vfb.dao.client_server.Server.(Server.java:47)
at uk.ac.ed.vfb.dao.client_server.Server.main(Server.java:93)
```

**Comment by dosumis** [comment]
To make sure we're on the same page:

* Individuals ontology should not be deployed from the Jenkins build, because this appears to be broken.  Local build works fine.  I believe that moving to Maven should fix problems with Jenkins build.  In the meantime, I'm building locally.

* The latest version of the individuals file is now in compressed (gz) form at https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/owl/fbbt_vfb_ind_pr_nr.owl.gz
I also added an MD5 for this: https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/owl/fbbt_vfb_ind_pr_nr.owl.md5

*  I'm only using the full compression system on the VFB repo.  On VFB_owl I've stuck to gz, because I wanted something generic that will work for anyone I point to the file.

* Version IRI for this file now has the form:
http://purl.obolibrary.org/obo/fbbt/vfb/2015-03-26/fbbt_vfb_ind_pr_nr.owl
(although perhaps this would make more sense
http://purl.obolibrary.org/obo/fbbt/vfb/2015-03-26/fbbt_vfb_ind_pr_nr.owl.gz)

http://purl.obolibrary.org/obo/fbbt/vfb/ resolves to https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/master/src/owl/

For archive purposes and to follow the URI scheme, I'm adding subdirectories for releases under this directory.

**Comment by Robbie1977** [comment]
It's being deployed from the compressed version if an uncompressed is not available
The checksum of the file after compression and copying to sandbox is dee118fd9b823b66d823dc67c5c926b6 (this will change once the url's are changed - this doesn't make any difference to the fault I've checked).

I'm currently adding more debugging to identify what syntax is causing the issue.

**Comment by dosumis** [comment]
Its looking like this is a bug with reading large xml docs that is found in aome java version:

http://stackoverflow.com/questions/20482331/whats-causing-these-parseerror-exceptions-when-reading-off-an-aws-sqs-queue-in

Running my test code from CL has been working fine, but when trying to run my test code from eclipse (pointing to an older java install) I get a load error consistent with this bug:

org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; The parser has encountered more than "64,000" entity expansions in this document; this is the limit imposed by the application.

Possible to get round it if I can save in functional syntax.  I believe there are other workarounds that owltools devs have used in the past.

Which version of java is being used on the server?

**Comment by dosumis** [comment]
Functional syntax version at https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/owl/fbbt_vfb_ind_pr_nr.owl.gz

**Comment by Robbie1977** [comment]
deploying now

Java(TM) SE Runtime Environment (build 1.7.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

**Comment by Robbie1977** [comment]
All seems to be fixed:

http://vfbsandbox.inf.ed.ac.uk/do/cluster_list.html?action=cluster_found&id=FBbt:00007401

**Comment by Robbie1977** [comment]
Just removing debug code then I'll push to dev server for final checking.

@dosumis well spotted. I can get java upgraded if you want?

**Comment by Robbie1977** [comment]
@dosumis the versionIRI tag is not included in the functional version?

**Comment by dosumis** [comment]
Seems to be there.  Protege can read it.

**Comment by Robbie1977** [comment]
Found it it's just not tagged the same.

All ready to go live if everyone is happy? (use http://vfbdev.inf.ed.ac.uk as the test version)

**Comment by Robbie1977** [comment]
@mmc46 All issues previously flagged now appear to be resolved are you happy for the version on http://vfbdev.inf.ed.ac.uk to go onto the live site?

**Comment by mmc46** [comment]
Yes, everything looks ok.

**Comment by Robbie1977** [comment]
I'll begin testing deployment for overnight release.
