### ISSUE TITLE
Inconsistency in naming of lineage clones from same set

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#495]
Original set (aIP-d clone of Cachero 2010):
http://www.virtualflybrain.org/site/tools/view_stack/3rdPartyStack.htm?tpbid=VFB_00020125

Compared with (aDT-a_M):
http://www.virtualflybrain.org/site/tools/view_stack/3rdPartyStack.htm?tpbid=VFB_00017892

Support info:
http://www.virtualflybrain.org/site/tools/view_stack/3rdPartyStack.htm?tpbid=VFB_00020125
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by dosumis** [comment]
Fixed in DB.  Will be visible next time individuals regenerated.
