### ISSUE TITLE
Any objections to changing the bg colour to purple (Red&Blue) rather than grey on single channel display

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#519]
Makes the green stand out much better and easily done on single channel display.

Will have to consider for composite etc but for now it would improve signal visibility greatly.

**Comment by Robbie1977** [comment]
![image](https://cloud.githubusercontent.com/assets/4630768/6527515/2f241048-c413-11e4-932b-324d4ec9cf96.png)
![image](https://cloud.githubusercontent.com/assets/4630768/6527530/54a1e0b6-c413-11e4-9d76-e4da1068f275.png)

**Comment by mmc46** [comment]
Fine by me.

**Comment by dosumis** [comment]
Agree it looks better. How does it look in combination with painted mask?

**Comment by Robbie1977** [comment]
That would be more of a problem hence I'm not suggesting doing that at this
point

**Comment by dosumis** [comment]
So it reverts to grey once you select a domain?

**Comment by Robbie1977** [comment]
Not overlapping with expression but we have issues with the signal and
overlapping colours in the current browser. Working on the assumption it's
less likely to be a user action when viewing signal.

Long term we need to control colours for all items displayed as discussed
previously.

**Comment by Robbie1977** [comment]
Will be superseded by V1.5
