### ISSUE TITLE
Make open OWL query endpoint

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#520]
Background:

Andrew Straw's [neuron catalog](https://github.com/strawlab/neuron-catalog) now supports mapping of their annotation shorthand to the Drosophila anatomy ontology.  It does this by consuming JSON files of adult brain neurons and brain regions (neuropils + tracts) of the form:

~~~~~~json

{
        "ID": "FBbt_00003632",
        "name": "adult central complex",
        "synonyms": [
            "CX",
            "adult central body complex",
            "central body",
            "central body complex"
        ]
    },
...
~~~~~~

So far I've generated these using simple Jython/Brain scripts, but I'd like to be able to provide such files dynamically via a webservice.

This same endpoint can be used to generate JSON for populating SOLR.  Ideally we'd align JSON with standards (JSON-LD?), but I'd also like to get something working quickly.  I'd be happy using the simple structure above in version 1.0.  This will be sufficient for driving basic autocomplete with SOLR & in neuron catalog.

We also need to design query JSON.  This can be pretty simple, just specifying a manchester syntax query as a string, and specifying the type of query (subclasses, individuals, superclasses).

**Comment by dosumis** [comment]
This GIST contains an example script taking JSON input as argv[1] and saving JSON output to file

https://gist.github.com/dosumis/54ceeae6bf0d5676459f

Needs

1.  Piring with a standard http server with queries/results as JSON via POST/GET
2. Error handling.

Might be easiest to rewrite in Java.

**Comment by dosumis** [comment]
Hi @Robbie1977 , would like to get this done soonish.  Please let me know if you need any more info.

Cheers,
David

**Comment by jefferis** [comment]
Out of curiosity, does the fbbt.learn step take long? I guess we don't need to worry about optimisation now but I imagine one might want to keep a process going with that in memory?

Also is there anything stopping me from running this script locally out of curiosity? Best,

Greg.

Gregory Jefferis

**Comment by Robbie1977** [comment]
@dosumis what data do you want individuals to return?

**Comment by dosumis** [comment]
On 14 Apr 2015, at 15:55, Gregory Jefferis <notifications@github.com> wrote:

> Out of curiosity, does the fbbt.learn step take long? I guess we don't need to worry about optimisation now but I imagine one might want to keep a process going with that in memory?
 
That's the idea.  The learn step should run on server initialistation.  Query time should then be milliseconds.  (the aim of the gist was just to show method calls rather than architecture.
> 
> Also is there anything stopping me from running this script locally out of curiosity? Best,

You'll need Jython 2.7 (I'm currently using beta 4), Brain (1.5) + owltools ().  All can be installed via Maven (I can post config as a gist), or install Jython directly and run Brain and owltools from jars (https://github.com/VirtualFlyBrain/VFB/tree/master/WEB-INF/lib)

> 
> Greg.

**Comment by mmc46** [comment]
@dosumis what java are you using?

**Comment by dosumis** [comment]
1.7.0_75-b13 (avoiding upgrading to Java 8 for now).

**Comment by Robbie1977** [comment]
@dosumis could you give an example query and response in JSON-LD as we need to decide what format to use. (a useful validator: http://json-ld.org/playground/index.html)

**Comment by Robbie1977** [comment]
The basic JSON you requested is running on sandbox:

http://vfbsandbox.inf.ed.ac.uk/do/jsonQuery.html?json={"query_type":"descendant_class","query":"FBbt:00003679"}

```
{
    "results": [
        {
            "ID": "FBbt:00040035",
            "name": "fan-shaped body layer",
            "synonyms": [
                "layer of fan-shaped body"
            ]
        },
        {
            "ID": "FBbt:00007487",
            "name": "fan-shaped body layer 1",
            "synonyms": [
                "fan shaped body layer 1"
            ]
        },
        ...
    ]
}
```

http://vfbsandbox.inf.ed.ac.uk/do/jsonQuery.html?json={"query_type":"individuals","query":"FBbt:00003679"}

```
{
    "results": [
        {
            "ID": "VFB_00010117",
            "name": "Cha-F-000010"
        },
        {
            "ID": "VFB_00010154",
            "name": "Cha-F-000014"
        },
        ...
    ]
}
```

**Comment by jefferis** [comment]
Just put up a very simple R package to make these queries:

https://github.com/jefferis/vfbr

Suggestions for more interesting examples / easier functions welcome.

Best, G.

**Comment by jefferis** [comment]
@dosumis what should I be able to do in terms of queries via the endpoint as is? For example, how do I get a list of all neuropil domains, neuroblasts etc, etc?

**Comment by Robbie1977** [comment]
I've removed it for the second - sorry
Going to add a new ticket for that takes Manchester syntax queries to allow for more flexible queries.

**Comment by dosumis** [comment]
> Going to add a new ticket for that takes Manchester syntax queries to allow for more flexible queries.

This was what I originally asked for.  Apologies if unclear.  Linking new ticket to hear for future ref:  #568 

> @dosumis what should I be able to do in terms of queries via the endpoint as is? For example, how do I get a list of all neuropil domains, neuroblasts etc, etc?

For now at least, you'll need to query with OWL shortForm IDs.  Unfortunately, we are currently displaying the old OBO style IDs on VFB (i've been trying to banish these for years).  To convert, you just need to change the colon to and underscore.

Here's the page for neuroblast
http://www.virtualflybrain.org/site/tools/anatomy_finder/index.htm?id=FBbt:00001333

To find all neuroblasts: { "query_type": 'descendant_class', "query" : "FBbt_00001333"}

To find all neurons that overlap the 'mushroom body calyx'

To find all neurons that overlap the 'calyx of adult musroom body' { "query_type": 'descendant_class', "query" : "FBbt_00005106 that RO_0002131 some FBbt_00007385 "}  # 

We obviously need a quick reference guide for useful relation IDs - or better still the ability to query using quoted names.

We also need some canned queries - the most obvious one being 'overlaps some X', where X must be a brain region => all known classes for annotation of that region (this will pull down parts as well as overlaping entities).

**Comment by Robbie1977** [comment]
Owl format is fine too:
http://www.virtualflybrain.org/site/tools/anatomy_finder/index.htm?id=FBbt_00001333
