### ISSUE TITLE
Maximum projection in browser?

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#521]
For stack viewing in the browser, we currently have maximum projection thumbnails at the bottom of the page.  This is better than nothing, but it is still hard to use this as a guide to 3D browsing.  A better solution might be to allow users to toggle the browser between maximum projection & single slices or to use a slider to adjust the number of layers being viewed.

**Comment by cahirokane** [comment]
I agree - although single slices will only be informative with some kind 
of slider

C

On 15/03/2015 10:32, David Osumi-Sutherland wrote:
>
> For stack viewing in the browser, we currently have maximum projection 
> thumbnails at the bottom of the page. This is better than nothing, but 
> it is still hard to use this as a guide to 3D browsing. A better 
> solution might be to allow users to toggle the browser between maximum 
> projection & single slices or to use a slider to adjust the number of 
> layers being viewed.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/VirtualFlyBrain/VFB/issues/521>.
>

-- 

---------
Dr. Cahir O'Kane,  Reader in Genetics
Dept of Genetics, University of Cambridge, Downing St, Cambridge, CB2 3EH, UK
Office: 01223-333177   International 44-1223-333177    Internal 33177
Lab:    01223-766488   Flylab: 01223-333971    Fax: 01223-333992
http://www.gen.cam.ac.uk/research-groups/okane
http://www.neuroscience.cam.ac.uk/directory/profile.php?cokane

For colorblind-friendly figures and slides: http://jfly.iam.u-tokyo.ac.jp/color/

**Comment by Robbie1977** [comment]
This only works with a HTML5 canvas merge so needs a new viewer.

So I've been experimenting with different blend modes:
http://vfbsandbox3.inf.ed.ac.uk/do/blendDemo.html?x=512&y=256&z=109&pit=0&yaw=0&rol=0&scl=1&dst=0.0&mod=zeta&qlt=80&cvt=png&alpha=150&inv=true&csy=318&csx=637&bg=bw&id=,VFBt_00100000,VFBd_00100027,VFBd_00100009,VFBd_00100049,VFBd_00100050,VFBd_00100011,VFBi_00000001

And designed a prototype viewer:

 http://vfbsandbox3.inf.ed.ac.uk/do/viewer2d.html?x=512&y=256&z=109&pit=0&yaw=0&rol=0&scl=1&alpha=150&st=108&bg=bw&id=%2CVFBt_00100000%2CVFBd_00100027%2CVFBd_00100009%2CVFBd_00100049%2CVFBd_00100050%2CVFBd_00100011%2CVFBi_00000001&csx=637&csy=318&pix=0&piy=0&dst=0.0&mod=zeta&cvt=png&bg=bw&inv=false#tabCont

**Comment by Robbie1977** [comment]
Adding this to V1.5 is not a quick one and definitely won't be quick to load - will investigate options as there is a max projection option (ish) in the new release of WlzIIP server.

**Comment by Robbie1977** [comment]
being superseded by Geppetto intergration
