### ISSUE TITLE
Help link on header top right doesn't link anywhere

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#561]
http://www.virtualflybrain.org/do/help.htm

**Comment by Robbie1977** [comment]
which page is the link on?

**Comment by mmc46** [comment]
Seen it here

http://www.virtualflybrain.org/do/individual_list.html?action=exemplar_neuron&id=FBbt:00110120

http://www.virtualflybrain.org/do/cluster_list.html?action=cluster_found&id=FBbt:00100016

http://www.virtualflybrain.org/do/individual_list.html?action=neuron_found&id=VFB_00007316&region=fru-F-800038

It works fine on main pages, but not query results.

**Comment by Robbie1977** [comment]
By the looks of it we never had one.

I'll take a stab at writing one.

**Comment by mmc46** [comment]
It might make sense to have a general help page, collecting the different ones we currently have linked from the header, which change depending on the page you're on.  As they currently don't make much sense: 

Eg. The help link from the Overview and the other pages under 'The VB site' goes to usage of stack viewer.

http://www.virtualflybrain.org/site/vfb_site/overview.htm
http://www.virtualflybrain.org/site/vfb_site/help.htm

The help link from the header would always point to this general page.

**Comment by Robbie1977** [comment]
I'm going to point the missing pages to the tutorial page for now but we need to decide a unified help system.
I do favour having hidden help on the individual page items as I question if people would read through all the text on these full help pages to find their question.
