### ISSUE TITLE
Home search box disappeared in dev

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#574]
The search box at the top of the home page has disappeared after centring the layout.

**Comment by mmc46** [comment]
After being fixed, it's happened again. This time just the actual search box is missing.

**Comment by mmc46** [comment]
It's now showing this instead of 'Esc'.  After clicking on it, it shows 'Esc'.
It's also showing to the left of it, what I think is a bullet point for a list.
![search_home](https://cloud.githubusercontent.com/assets/1872083/8066504/e51339c6-0edf-11e5-80db-3e9c98348837.png)

**Comment by Robbie1977** [comment]
it's a temp filter to select only anatomy or individuals
