### ISSUE TITLE
Labelling of search box on results pages

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#575]
Great that there is now a search box to use for refining results.

e.g. see top right here
http://vfbdev.inf.ed.ac.uk/do/ont_bean_list.html?action=synaptic&id=FBbt:00007401
(+ try typing 'ad')

But I think it needs to be labelled 'refine results' rather than 'search', as the latter makes it look too much like the regular search box. I suspect many users will think this is a way to start a new search.

**Comment by Robbie1977** [comment]
I think this has been superseded

**Comment by mmc46** [comment]
A similar box t this is called 'Filter' in the viewer page, but still 'Search' in the results page.

Can the latter be changed for consistency?
