### ISSUE TITLE
VFB 1.5 layout issues

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#576]
Progress on the various components on VFB 1.5 is great, but layout us currently very much a work-in-progress. We will need to address layout issues soon if we are to push this out as a beta.  Some potential solutions to some of these issues are already in the [VFB2.0 functional spec](https://github.com/VirtualFlyBrain/VFB_2/blob/master/specs/functional_specs_pub.md#vfb-20-functional-spec).  I think we should combine work on VFB 1.5 layout with work on the VFB2.0 functional spec.

Ideally we'd do this with mockups.  @Robbie1977 How easy would it be to build mockups using the new framework? 

Some basic issue to address: 

* Standardisation of search bar location on all pages (in standard header?)
* Relative location of main panels (do we need more use of tabs to fit in content?)
  * 2D viewer (+controls)
  * TermInfo  (and within that, max projections images)
  * Display/selection/browsing panel, as shown below (& its components) 
![image](https://cloud.githubusercontent.com/assets/112839/8255225/563b864a-1696-11e5-83cf-45b9ac76efca.png)

  (Aiming for this rather general ticket to be a locus for discussion how to co-ordinate and very general layout issues.  Any specific requests that come up in discussion should be made into new tickets, linked to this one with a # ref.)

**Comment by Robbie1977** [comment]
A new version of Datatables is out so have more flexibility in layout.

Currently going for:
![image](https://cloud.githubusercontent.com/assets/4630768/9656270/0054e6a2-522f-11e5-8547-80a0641efa6d.png)

**Comment by dosumis** [comment]
Notes from meeting with EBI UX.  

First impression of VFB 1.5 compared to VFB 1:

* The page is very busy.  It is not clear what the user is expected to focus on.  
   * More clear in VFB 1 in that page seems to be centred around one term at at time.  
   * Is it possible to hide some details by default?
* Layout needs to be stable.  Right now elements move around depending on the size of the page and the size of individual elements (which can change depending on conten/zoom settings.  
   * Need to work with mockups of stable layouts to come up with a solution.

**Comment by Robbie1977** [comment]
could fix the zoom which would resolve movement although should only be moving on zoom changing and only between side by side and on top and below - anything else is a glitch that needs resolving so please report.

Could go for a fixed view with move over zoom such as: http://www.elevateweb.co.uk/image-zoom/examples#inner-zoom or the original zoom in fixed window.

Which version was tested? vfbdev or old sandbox?

Can remove any features easily enough - any ones you think we should lose?

**Comment by dosumis** [comment]
Layout discussion and suggestions here: https://github.com/VirtualFlyBrain/VFB/blob/master/doc/VFB1.5_proposals/Layout_suggestions.pptx?raw=true
