### ISSUE TITLE
Using old ontology

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#577]
The site is using the ontology from 2014-11-07, when it should be using the 2015-03-11 one, that goes with the FlyBase chado FB_2015_02 (which is live). It means it is missing, among other things, the updates related to Yoshi Aso's paper.

For the upcoming FB_2015_03 release, scheduled for Friday, 26th June, the ontology will be the one from 2015-05-12.

**Comment by dosumis** [comment]
I'll rebuild individuals files using  FBbt 2015-05-12.

Need that release cycle SOP sorted!

**Comment by Robbie1977** [comment]
updated - please check everything is as expected.

**Comment by mmc46** [comment]
The changes have taken effect, but there are things to correct. The autocomplete hasn't updated, which means that if something has changed name, it's not possible to search for it.

Example with the change below:  
alpha'/beta' anterior Kenyon cell ; FBbt:00100250 has changed name to alpha'/beta' anterior-posterior Kenyon cell (the two terms, anterior FBbt:00100250, and posterior FBbt:00100254 were merged, with one id being the main and the other the alternative one, respectively)

Autocomplete only shows alpha'/beta' anterior Kenyon cell. There are no options for the current name. This needs fixing.

Choosing alpha'/beta' anterior Kenyon cell brings up the term page with the updated name, so that's fine. 

http://www.virtualflybrain.org/site/tools/anatomy_finder/index.htm?id=FBbt:00100250&name=alpha%27%2Fbeta%27%20anterior%20Kenyon%20cell

Same issue as above for other merged terms that have changed name: mushroom body alpha' anterior-posterior layer (FBbt:00100266), mushroom body beta' anterior-posterior layer (FBbt:00100269).

**Comment by Robbie1977** [comment]
sorry forgot to restart the ontology server - looks to be fine now.

**Comment by mmc46** [comment]
Still can't see it. Tried the 3 browsers after clearing the cache.

**Comment by Robbie1977** [comment]
on the live version? what are you searching for and expecting to see?

**Comment by mmc46** [comment]
I'm searching on the main site, with 

alpha'/beta' anterior-posterior Kenyon cell

No term matching that.

**Comment by Robbie1977** [comment]
which term does that appear on?

**Comment by Robbie1977** [comment]
interesting it's picking up the synonyms but not the name - this might be a
complicated one - I'll run some tests.

**Comment by mmc46** [comment]
It goes to alpha'/beta' anterior Kenyon cell ; FBbt:00100250. Which is the term that corresponds to the main id after the merge.

The synonyms it it picking up are the ones that were already there, on each of the terms (before the merge).
alpha'/beta' anterior Kenyon cell
alpha'/beta' posterior Kenyon cell

**Comment by Robbie1977** [comment]
I've got the same problem on the dev using solr so thing this might be one
for David.
It also has problems resolving the search but this maybe unrelated.
{ "id": "fbbt:http://purl.obolibrary.org/obo/FBbt_00100250", "uri": "
http://purl.obolibrary.org/obo/FBbt_00100250", "short_form": [
"FBbt_00100250", "FBbt:00100250" ], "label": "alpha'/beta' anterior Kenyon
cell", "label_suggest": [ "alpha'/beta' anterior Kenyon cell", "alpha'/beta'
anterior neuron", "mushroom body alpha'/beta' anterior neuron", "mushroom
body alpha-prime/beta-prime anterior neuron", "beta'a", "alpha'a",
"alpha'/beta'a
neuron", "alpha'/beta'a", "mushroom body alpha'/beta' anterior Kenyon cell"
], "synonym": [ "alpha'/beta' anterior neuron", "mushroom body alpha'/beta'
anterior neuron", "mushroom body alpha-prime/beta-prime anterior neuron",
"beta'a", "alpha'a", "alpha'/beta'a neuron", "alpha'/beta'a", "mushroom
body alpha'/beta' anterior Kenyon cell" ], "description": [ "A subgroup of
the mushroom body alpha'/beta' neurons that mainly innervates the anterior
stratum of the alpha' and beta' lobes." ], "ontology_name": "fbbt", "
ontology_uri": "
http://purl.obolibrary.org/obo/fbbt/vfb/2015-03-26/fbbt_vfb_ind_pr_nr.owl ",
"type": "class", "is_defining_ontology": false, "has_children": false, "
is_root": false, "logical_description": [ "has_presynaptic_terminal_in some
mushroom body alpha'-lobe", "has_presynaptic_terminal_in some mushroom body
beta'-lobe" ], "creation_date_annotation": [ "2010-09-09T04:26:05Z" ], "
id_annotation": [ "FBbt:00100250" ], "database_cross_reference_annotation": [
"VFB:FBbt_00100250" ], "has_obo_namespace_annotation": [
"fly_anatomy.ontology" ], "comment_annotation": [ "Comparison of the
expression patterns of the enhancer traps NP65, NP1131, NP6522 and NP7427
prompted the classification of three subpopulations (anterior, middle and
posterior) of alpha'/beta' neurons by Tanaka et al., (2008), according to
their terminal positions. Comparisons using these enhancer trap lines
suggests that the neurons terminating in the anterior of the alpha' lobe
are the same subclass as those terminating in the anterior of the beta'
lobe." ], "created_by_annotation": [ "sr544" ], "bbop_sibling_graph_json":
"", "_version_": 1504949667671048200 }

**Comment by dosumis** [comment]
As discussed in last meeting - current tuning of this SOLR search is known to be broken + I'm not sure the query endpoint on vfbdev is set correctly.  

Hi @simonjupp: Have you updated OLS SOLR to Ilinca's tuning yet?  If not, can you give us an ETA?
Also, could you share instructions for setting up the query endpoint?  
Cheers,
David

**Comment by Robbie1977** [comment]
I've got the same problem on the dev using solr so thing this might be one
for David.
It also has problems resolving the search but this maybe unrelated.

```javascript
{ "id": "fbbt:http://purl.obolibrary.org/obo/FBbt_00100250", "uri": "
http://purl.obolibrary.org/obo/FBbt_00100250", "short_form": [
"FBbt_00100250", "FBbt:00100250" ], "label": "alpha'/beta' anterior Kenyon
cell", "label_suggest": [ "alpha'/beta' anterior Kenyon cell", "alpha'/beta'
anterior neuron", "mushroom body alpha'/beta' anterior neuron", "mushroom
body alpha-prime/beta-prime anterior neuron", "beta'a", "alpha'a",
"alpha'/beta'a
neuron", "alpha'/beta'a", "mushroom body alpha'/beta' anterior Kenyon cell"
], "synonym": [ "alpha'/beta' anterior neuron", "mushroom body alpha'/beta'
anterior neuron", "mushroom body alpha-prime/beta-prime anterior neuron",
"beta'a", "alpha'a", "alpha'/beta'a neuron", "alpha'/beta'a", "mushroom
body alpha'/beta' anterior Kenyon cell" ], "description": [ "A subgroup of
the mushroom body alpha'/beta' neurons that mainly innervates the anterior
stratum of the alpha' and beta' lobes." ], "ontology_name": "fbbt", "
ontology_uri": "
http://purl.obolibrary.org/obo/fbbt/vfb/2015-03-26/fbbt_vfb_ind_pr_nr.owl ",
"type": "class", "is_defining_ontology": false, "has_children": false, "
is_root": false, "logical_description": [ "has_presynaptic_terminal_in some
mushroom body alpha'-lobe", "has_presynaptic_terminal_in some mushroom body
beta'-lobe" ], "creation_date_annotation": [ "2010-09-09T04:26:05Z" ], "
id_annotation": [ "FBbt:00100250" ], "database_cross_reference_annotation": [
"VFB:FBbt_00100250" ], "has_obo_namespace_annotation": [
"fly_anatomy.ontology" ], "comment_annotation": [ "Comparison of the
expression patterns of the enhancer traps NP65, NP1131, NP6522 and NP7427
prompted the classification of three subpopulations (anterior, middle and
posterior) of alpha'/beta' neurons by Tanaka et al., (2008), according to
their terminal positions. Comparisons using these enhancer trap lines
suggests that the neurons terminating in the anterior of the alpha' lobe
are the same subclass as those terminating in the anterior of the beta'
lobe." ], "created_by_annotation": [ "sr544" ], "bbop_sibling_graph_json":
"", "_version_": 1504949667671048200 }
```

**Comment by dosumis** [comment]
I think both autocompletes must still be pointing at the old ontology.

**Comment by Robbie1977** [comment]
The text used for the uri in the footer is taken from the owl file
directly. It might be an idea to recompile a new one.

**Comment by mmc46** [comment]
I think this has been solved.
