### ISSUE TITLE
Not able to add things to viewer from term page

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#588]
I'm not able to add this term to the viewer. I'm clicking on the green paperclip, but nothing happens.
I remember this working before.

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/?id=FBbt_00003982

**Comment by mmc46** [comment]
From other reports and some more checking, it seems widespread.

The green paperclip works when adding things from the viewer page (after doing a search using the Search tab).

**Comment by Robbie1977** [comment]
Resolved now
