### ISSUE TITLE
Show total number of hits on top of results table

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#589]
Could the total number of hits be shown on top of the table? Maintaining or not the count at the bottom.
This is especially useful for laptops, as, at least in mine, only the first 3-5 hits fit on the screen, and so need to scroll down to check how many hits there are in total.

**Comment by Robbie1977** [comment]
This is annoying I agree and did try to resolve this in Datatables but the layout gets very glitchy if you move things from the standard.

The open all should give a total although will look at something more consistent across reports

**Comment by Robbie1977** [comment]
Added
