### ISSUE TITLE
Sorting query results by Available images gives some top hits with no images.

### ISSUE THREAD

**Issue by mnqslbs2** [VirtualFlyBrain/VFB#592]
When you perform a query by selecting Neurons with synaptic terminals in the AMMC, you get 27 results. When click to sort the results by available images this seems to work to some extent in that it sorts all 27 results. It however, brings some hits that have no images to the top (see image below).
![screen shot 2015-06-30 at 12 55 00](https://cloud.githubusercontent.com/assets/8876153/8430224/73772e3c-1f27-11e5-94f9-32690ded3ff5.png)

**Comment by Robbie1977** [comment]
This is due to it sorting by the underlying ID, this has been changed to sort by number of images found.
