### ISSUE TITLE
some show me icons on front page fail on vfbalpha

### ISSUE THREAD

**Issue by jefferis** [VirtualFlyBrain/VFB#593]
@mmc46 @robbie1977 I think it would be worth clicking on all of them. 

http://bit.ly/vfbalpha or http://bit.ly/vfbdev

For me [Overlay 3 different image stacks that overlap the central complex](http://vfbsandbox3.inf.ed.ac.uk/do/composite_view.html?action=load&uuid=2050-07-05_10.04.35.973) fails.

Also some of them open a new window and some don't. We should probably standardise.

**Comment by mmc46** [comment]
Now all opening in a new tab. 47e047cd9523b78e85d5edbada8d668fd7bddd90

Still to fix the 'Overlay image'.

**Comment by Robbie1977** [comment]
Sadly was also broken on the main site, so have fixed both although the original used examples we seem to have dropped:
VFB_00016207
VFB_00020020
VFB_00020062

For the new one I've just picked different examples from the overlap report so feel free to improve but if OK let me know and I'll modify the old main site example to match.
http://vfbdev.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000,VFBi_00006883,VFBi_00000254,VFBi_00007134

**Comment by jefferis** [comment]
@dosumis @mmc46 

> VFB_00016207
> VFB_00020020
> VFB_00020062

The neurons are still there for sure. Have the ids changed?

**Comment by mmc46** [comment]
At least 2 of these were lineage clones, so the problem might be related to #594. 
I’ll check the OWL.

**Comment by mmc46** [comment]
There seems to be a problem with the OWL file, but @dosumis should check.
The Yu2013.owl, which is imported to make the final file is empty (also clear from file size: 1KB vs Ito2013 83KB), and so no Yu2013 individuals are present in fbbt_vfb_ind_pr_nr.owl.

>> VFB_00016207
>> 

 still there, corresponds to VGlut-F-000176.
>> VFB_00020020
>> VFB_00020062
>> 

correspond to Yu 2013 clones, so are missing.

Related to problem in #594.

**Comment by Robbie1977** [comment]
@dosumis @mmc46 what's the plan with this issue?

**Comment by mmc46** [comment]
I was hoping @dosumis could redo the OWL in time for the meeting.

**Comment by dosumis** [comment]
I’ve been in a meeting for the past two days so managed to miss this.  Found the problem - typo in the config I use for specifying dataset for build.  Fixed and rebuilding now.  Also using the opportunity to remove the Aso neurons from the build, given that the images are not available on the server yet.

- David

**Comment by dosumis** [comment]
New version uploaded. Available from purl

**Comment by Robbie1977** [comment]
2015-07-04 14:09:03,119 (vfb-bocian.inf.ed.ac.uk) ERROR [uk.ac.ed.vfb.dao.client_server.server_includes.DLQueryServer:139] 

2015-07-04 14:09:03,120 (vfb-bocian.inf.ed.ac.uk) ERROR [uk.ac.ed.vfb.dao.client_server.server_includes.DLQueryServer:140] Trying to retrieve individual for id: VFB_00020020
Still missing VFB_00020020

2015-07-04 14:09:03,120 (vfb-bocian.inf.ed.ac.uk) ERROR [uk.ac.ed.vfb.dao.client_server.Server:163] Ontology server NullPointerException:
java.lang.NullPointerException
at uk.ac.ed.vfb.dao.client_server.server_includes.ADLQueryEngine.getOntBeanForId(ADLQueryEngine.java:99)
at uk.ac.ed.vfb.dao.client_server.server_includes.DLQueryServer.getBeanForId(DLQueryServer.java:141)
at uk.ac.ed.vfb.dao.client_server.Server$ClientHandler.run(Server.java:147)

**Comment by Robbie1977** [comment]
where is the new version located exactly

**Comment by Robbie1977** [comment]
Think I found the issue - the gzip has the old copy - trying the uncompressed version now

**Comment by Robbie1977** [comment]
fixed and deployed
