### ISSUE TITLE
Add to viewer not showing for lineage clones

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#594]
The green paperclip is missing, for any clones that I've tried. 

http://vfbdev.inf.ed.ac.uk/do/ont_bean_list.html?action=lineage_clone&id=FBbt:00045048

Paperclip is there for neuropils.

**Comment by mmc46** [comment]
Now missing from this neuropil as well

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/?id=FBbt_00110633

**Comment by Robbie1977** [comment]
This is because they are not available in the current template (painted region)

The individuals should be shown in Images but adding to viewer would not work hence no paperclip.

**Comment by Robbie1977** [comment]
Going to close but if you want to change this behaviour just reopen.

**Comment by mmc46** [comment]
The lineage individuals are all on JFRC2, and can be added to the viewer in the main site.
Not sure I understand what you mean.

**Comment by Robbie1977** [comment]
The issue is that the FBbt ref has individuals VFB refs that are shown in the images but doesn't directly have an image representation. It may have a single, multiple of none.

I could add a link if individuals are available but should I add all or just the first found?

**Comment by Robbie1977** [comment]
Are you talking about under the image or next to the name?

**Comment by mmc46** [comment]
Under the image, like 

http://vfbsandbox3.inf.ed.ac.uk/site/tools/anatomy_finder/?id=FBbt_00100389 <http://vfbsandbox3.inf.ed.ac.uk/site/tools/anatomy_finder/?id=FBbt_00100389>

It’s a similar case to the lineage clones like here, I think.

http://vfbsandbox3.inf.ed.ac.uk/site/tools/anatomy_finder/?id=FBbt_00100389 <http://vfbsandbox3.inf.ed.ac.uk/site/tools/anatomy_finder/?id=FBbt_00100389>

But no buttons on above. Maybe it’s because it lists only one image. Clicking on it opens it in the viewer, so that’s fine.

The problem is there should be 2 images, for most of these adult lineage clones, one from Ito2013 and one from Yu2013. 
From checking some other clones, and the main site: it seems that no images from Yu are being shown. They used to, so I’m not sure what the problem is. 
I can check the OWL.

**Comment by Robbie1977** [comment]
individual file fixed
