### ISSUE TITLE
Synonym missing from autocomplete

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#599]
(Not sure if this is related to other automplete issues)

The synonym 'EB' (exact) is not showing up on the autocomplete.
I checked the whole list that appeared when I typed 'EB'. The related synonym 'eb' is on the autocomplete list though.

http://vfbsandbox3.inf.ed.ac.uk/site/tools/anatomy_finder/?id=FBbt_00003678

I tried it with some other acronyms. These were not on the list either: FLA (flange), CB (central body), but other worked.

**Comment by dosumis** [comment]
Known issue. Will be fully fixed when new tuning implemented in OLS SOLR,
but may be partially fixed by changing SOLR endpoint setup. (Currently set
to label ?)

**Comment by Robbie1977** [comment]
The SOLR endpoint is correct (the proxy hides that it's not select), the problem is a bug with the OLS solr query - there has been no updates on github yet, so hopefully the fix is imminent.

**Comment by Robbie1977** [comment]
Have applied one fix (to OLS code) so they now are in the list although the tuning is still off, so have to wait for OLS fix

**Comment by Robbie1977** [comment]
Closing as it is now in the list and the tuning is in issue #362
