### ISSUE TITLE
Button missing from cluster results

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#600]
The button for 'List individual members' is missing in

http://vfbsandbox3.inf.ed.ac.uk/do/cluster_list.html?action=cluster_found&id=FBbt:00003678

The text is there.
![cluster_button_missing](https://cloud.githubusercontent.com/assets/1872083/8461198/c381eaa6-2022-11e5-97b6-be1a62f24c19.png)

**Comment by mmc46** [comment]
Just to add that the button 'open all in viewer' takes around 5sec to appear after refreshing the page. Any chance of speeding it up?

**Comment by Robbie1977** [comment]
It has to run a the list all report them import the button at present (hence the delay) - this should be improved when we improve the backend processing.

**Comment by Robbie1977** [comment]
Do you think the List individual members should be a button?

**Comment by mmc46** [comment]
Yes, I’m happy with a button.

**Comment by Robbie1977** [comment]
Done and added count to individual report open all button
