### ISSUE TITLE
Results page cutting out driver

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#607]
The page is cutting out the driver button, and there is no navigation bar to be able to scroll right.

http://vfbsandbox3.inf.ed.ac.uk/do/individual_list.html?action=exemplar_neuron&id=FBbt:00110633

![driver_off](https://cloud.githubusercontent.com/assets/1872083/8497860/8f8b7120-2178-11e5-9301-a997fb0f4b37.png)

**Comment by mmc46** [comment]
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by Robbie1977** [comment]
there was a layout problem - all fixed now
