### ISSUE TITLE
Open and list buttons wider than they should

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#608]
From homepage, example query 3 results: the open and list buttons sometime span 2 columns, other times just one.

http://vfbsandbox3.inf.ed.ac.uk/do/ont_bean_list.html?action=lineage_clone&id=FBbt:00007401

I also saw this behaviour in another similar query.

![button_wide1](https://cloud.githubusercontent.com/assets/1872083/8499711/6d3fa4aa-218d-11e5-9c5f-b22792fa4d76.png)
![button_wide2](https://cloud.githubusercontent.com/assets/1872083/8499712/709c22ea-218d-11e5-91f4-295a2fa327a4.png)

**Comment by mmc46** [comment]
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by Robbie1977** [comment]
that was an annoying one but think i've stamped it out.
