### ISSUE TITLE
search for content at point broken on sandox 3?

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#620]
Search for content by clicking on a point on the stack seems to be broken.  Either that or failing on slow wifi.

**Comment by mmc46** [comment]
It's working for me on ethernet, but not wifi. I get adult brain in anything I click.

Referring page: http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36 Size:[1422,754]

**Comment by Robbie1977** [comment]
I can't simulate this one (I'm on basic broadband over not great wifi), I'm assuming it's a timeout in the initial list loading if anything is returned. How long before the box actually appears on initial load? 

Are you sure you haven't limited the search - the conditions listed in the top right?

**Comment by mmc46** [comment]
It's happening again on the wifi at the meeting. No I didn't limit the search.

First screengrab: trying to add a a term in viewer. Always says 'adult brain'.
The second after I added saddle from the homepage. This time the wheels under name and type keep spinning. Clicking on the stack says' adult brain'.
![select_viewer](https://cloud.githubusercontent.com/assets/1872083/8512402/52377352-2338-11e5-908f-16bfbb220c7c.png)
![select_viewer2](https://cloud.githubusercontent.com/assets/1872083/8512403/58b71746-2338-11e5-991b-19e2b74a0155.png)

Referring page: http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36 Size:[1422,705]

**Comment by Robbie1977** [comment]
Agh not the search I was thinking of.

Is the circle drawn where you click? The coordinates are coming in as 0,0,69 (X,Y,Z) which is interesting as your not on slice 69 - was it run on this slice?

**Comment by Robbie1977** [comment]
Your chrome is a tiny bit out of date so might be worth trying updating.

**Comment by Robbie1977** [comment]
If you have time right click and open 'inspect element' it would be good to get the URI of the server call ('network' tab) that contains the parameter 'pri' (search for pri should find it). If you click in center the coordinates in this should match what's sent to server.

**Comment by mmc46** [comment]
Yes, the circle is drawn in the right place. And I didn't change slice, so I was on slice 85.

Chrome tells me I'm up to date. 

Where in the network tab, should I be looking for 'pri'?
![network](https://cloud.githubusercontent.com/assets/1872083/8512810/fb5fcad2-235c-11e5-82fc-e3a8f1fed6d2.png)

**Comment by Robbie1977** [comment]
Click on an item in network then click Cmd + F and type pri it should be
there in the list easiest to right click and open in new window to copy url

**Comment by Robbie1977** [comment]
I've modified the point collection to use jquery rather than javascript (hopefully more robust) on vfbdev but sounds like the coordinates are fine if the circle is drawn correctly.
Ideally when you find the wlziip server request (with the 'PRI') then the response should be two JSON'ish formatted values - would need a copy of them.

**Comment by mmc46** [comment]
I see this

Request URL:http://vfbsandbox3.inf.ed.ac.uk/fcgi/wlziipsrv.fcgi?wlz=/disk/data/VFB/IMAGE_DATA/VFB/t/001/composite.wlz&sel=0,255,255,255,220&mod=zeta&fxp=511,255,108&scl=1.0&dst=-24&pit=0&yaw=0&rol=0&qlt=80&cvt=png

**Comment by Robbie1977** [comment]
Sorry it's PRL so search for '&prl=-1'

**Comment by mmc46** [comment]
Request URL:http://vfbsandbox3.inf.ed.ac.uk/fcgi/wlziipsrv.fcgi?wlz=/disk/data/VFB/IMAGE_DATA/VFB/t/001/composite.wlz&fxp=511,255,108&scl=1.0&dst=-24&pit=0&yaw=0&rol=0&prl=-1,428.0084466934204,144&obj=Wlz-foreground-objects&obj=Wlz-coordinate-3D

**Comment by dosumis** [comment]
This is the phenotype I've been getting consistently while travelling

**Comment by Robbie1977** [comment]
BTW the 69 is correct as the voxel size is not 1:1

**Comment by Robbie1977** [comment]
let me check non-integer values are valid

**Comment by Robbie1977** [comment]
Yep that's it - it doesn't like decimal places - testing a fix to round point values.

**Comment by Robbie1977** [comment]
is your page zoomed in or out at all?

**Comment by Robbie1977** [comment]
@mmc46 Am I OK to update/restart Sandbox3 or are you using?

**Comment by Robbie1977** [comment]
Should be fixed please reopen if this occurs again.
