### ISSUE TITLE
Scroll not maintained

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#635]
In a results page displaying 25 entries at a time (and 50, didn't try 100), scrolling up from the top or bottom of the list: a small break on the scroll pull the page completely up, so that the bottom is shown. This is happening consistently.

Referring page: http://vfbsandbox3.inf.ed.ac.uk/do/gene_list.html?action=transgene&id=FBbt:00003982
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36 Size:[1420,754]

**Comment by mmc46** [comment]
Also happening when displaying 10 entries.

**Comment by Robbie1977** [comment]
Was moving when the tables data was routinely refreshed - now only updates data on change.
