### ISSUE TITLE
Change location of search box & rename refinemenent box in display tab

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#652]
Use story: User is on the stack browser page and wants to do a basic search of all site content. 

To do this they need to know to navigate to the search tab, avoiding the 'search' box (actually a refine box - should be relabelled to avoid confusion) if they are on the display tab.  It would be more intuitive, and more in line with standard web page layout if the search box were located at the top of all pages towards the right.  We could make this standard for all pages by integrating into the header.

It will probably take playing with some mockups to get this right.  

Here's the current header.
![image](https://cloud.githubusercontent.com/assets/112839/8877160/e0dc4a5a-321b-11e5-81d2-a0368fbf6264.png)

Perhaps we could move the menus down under the logo and put the search box to the right of the logo?

Or perhaps just base this on the home page search box, tweaking the layout and look so that the search box appears part of the header rather than just a separate element.

**Comment by Robbie1977** [comment]
All datatable search boxes should be labelled filter in previous ticket.
Search box redesigned and placed in header.
