### ISSUE TITLE
Need an hourglass or timer to show that page still loading

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#653]
Many pages load content a bit slowly.  I'm sure we can improve on this for textual content and thumbnails once we ditch the old data model and move to SOLR, but this issue will likely remain for display on the stack browser.  Could we have some hourglass or timer icon displayed to indicate that content is still loading (or being removed - especially slow in the stack browser).  This could be the cursor for slow loading textual content and thumbnails.  A separate icon for slow loading could be displayed in the stack browser.

**Comment by Robbie1977** [comment]
This has been added on the stack browser which other pages load slowly?

**Comment by dosumis** [comment]
Results pages.

**Comment by Robbie1977** [comment]
Done, any others you can think of?

**Comment by dosumis** [comment]
Related: Current default view in search tab before search = table of everything

![image](https://cloud.githubusercontent.com/assets/112839/8931333/5b6a0bcc-352d-11e5-9ccf-88ef8e5ebead.png)

This is, I think, distracting and not useful.  Please can it go away?

**Comment by Robbie1977** [comment]
This has now been hidden as on the anatomy finder page
