### ISSUE TITLE
Adding new image to the stack browser should automatically display metadata for that image

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#660]
If I click a thumbnail here to add to stack browser:

http://vfbdev.inf.ed.ac.uk/do/individual_list.html?action=neuron_found&id=VFB_00008951&region=VGlut-F-500688

It doesn't then display the metadata for that image. To see metadata, I need to remeber then name of the neuron/expression pattern individual and then choose it from the list.  

It should instead, display the relevant metadata by default when the image browser page loads.

**Comment by Robbie1977** [comment]
Will now always show the last added object
