### ISSUE TITLE
stack viewer: slice slider disappears after any move 

### ISSUE THREAD

**Issue by jefferis** [VirtualFlyBrain/VFB#667]
Moving through a stack becomes challenging because each time you step to a different slice the slider disappears and you need to click on the slice button again.

Also the email us button seems to have been replaced by the url as text.
<img width="1291" alt="vfb_email_button_missing" src="https://cloud.githubusercontent.com/assets/23763/9025398/0e66adea-38fb-11e5-880a-bbee217f8708.png">

Screenshot from vfbalpha, error below from re-test on vfbdev.

Support info:
http://vfbdev.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000,VFBi_00009935,VFBi_00004510,VFBi_00020033,VFBi_00016167
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36 Size:[1112,884]
{"__utma":"1.1685929467.1425462740.1431193420.1431193420.1","__utmz":"1.1431193420.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not provided)","_ga":"GA1.5.1685929467.1425462740","cookie-box":"closed","JSESSIONID":"C90CAEC821038C36131DB6034CCBBF62","_gat_UA-18509775-3":"1","dev-box":"closed","displaying":"!M571.6!M4!6Z!4dst!7-34!M1511,255,108!4alpha!7100!9blend!6screen!4inverted!7false!8!B!11!I49935!4N!6fru-F-1!F323!L34t!6<span id=\\\"partParent\\\"><li>neuron</li></span>!12!I44510!4N!6fru-F-200105!4t!6<span id=\\\"partParent\\\"><li>adult fruitless aIP-g (female) neuron</li></span>!4I!K2110443!13!I320033!4N!6LHd1 clone of Yu 2013!4t!6<span id=\\\"partParent\\\"><li>adult LHd1 lineage clone</li></span>!L1350098!14!I316167!4N!6VGlut-F-!F3147!4t!6<span id=\\\"partParent\\\"><li>neuron</li></span>!L3G!H4!2S!20!2i!6!H4!F5!4N!6Adult Ventral Nervous System!11!g108g!0"}

**Comment by Robbie1977** [comment]
This should all be resolved now.
