### ISSUE TITLE
Homepage search not responding after choosing term

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#671]
The autocomplete is working, but nothing happens after clicking on a term.

Also happening with dev.

Support info:
http://vfbsandbox3.inf.ed.ac.uk/site/vfb_site/home.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36 Size:[1355,1330]
{"cookie-box":"closed","JSESSIONID":"07ABACEC818F7B90A8C692B9B82EFAB2","dev-box":"closed","displaying":"!M570.9!M4!6Z!e8e-3!M1511,255,108!E!B!11!j1!F325!4e!L043748!0"}

**Comment by Robbie1977** [comment]
Resolved
