### ISSUE TITLE
Query 'Parts of' for neuron?

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#673]
There is currently a query for 'Parts of' for neurons, on main, dev, sandbox, bocian. It didn't use to exist, and it doesn't make much sense, if the label is correct. I haven't found any neuron types with results for this query.

Could this be a mistake carried over from the neuropil query menu, where this query appears correctly?
![parts-of](https://cloud.githubusercontent.com/assets/1872083/9039413/1cd90f64-39f3-11e5-91b1-6cf9a4d42b46.png)

**Comment by Robbie1977** [comment]
Appears to have been like that since SourceForge. @dosumis is there any possible reason for this other than a typo?

**Comment by dosumis** [comment]
We have a few cases where this does => useful results (photoreceptor cells!). But these are rare, so we should probably change => General rule should probably be no part menus for cells (not just neurons).


src/uk/ac/ed/vfb/tools/autocomplete/AutocompleteDAO.java has classification of neurons:

~~~~.java

	map.put("neuron", "subclass&FBbt_00005106");

~~~~~

This gets fed into OntBeans, which are checked by jsp.
jsp/do/ontBean.jsp  has the conditionals that control menu choices:


~~~~~~.jsp

<c:forEach items="${aclNeuron}" var="neuron" varStatus="i">
	<c:if test="${ontBean.fbbtId == neuron.fbbtId}">
		<c:set var="isNeuron" value="true" scope="request"/>
	</c:if>
</c:forEach>
<c:forEach items="${aclNeuropil}" var="neuropil" varStatus="i">
	<c:if test="${ontBean.fbbtId == neuropil.fbbtId}">
		<c:set var="isNeuropil" value="true" scope="request"/>
	</c:if>
</c:forEach>
<c:forEach items="${aclTract}" var="tract" varStatus="i">
	<c:if test="${ontBean.fbbtId == tract.fbbtId}">
		<c:set var="isTract" value="true" scope="request"/>
	</c:if>
</c:forEach>
<c:forEach items="${aclClone}" var="clone" varStatus="i">
	<c:if test="${ontBean.fbbtId == clone.fbbtId}">
		<c:set var="isClone" value="true" scope="request"/>
	</c:if>
</c:forEach>


<c:if test="${sessionScope.currURL!='/site/tools/query_builder/'}">
	<c:set var="termMenu" value="termMenuNeuron.jsp"/>
</c:if>
<c:if test="${isNeuropil && sessionScope.currURL!='/site/tools/query_builder/'}”> 
	<c:set var="termMenu" value="termMenuNeuropil.jsp"/>
</c:if>
<c:if test="${isTract && sessionScope.currURL!='/site/tools/query_builder/'}">
	<c:set var="termMenu" value="termMenuTract.jsp"/>
</c:if>
<c:if test="${isClone && sessionScope.currURL!='/site/tools/query_builder/'}">
	<c:set var="termMenu" value="termMenuClone.jsp"/>
</c:if>
<c:if test="${fn:contains(sessionScope.currURL,'/site/tools/query_builder/')}">
	<c:set var="termMenu" value="termMenuQB.jsp"/>
</c:if>

~~~~~~~

Looks like there is a lookup for neurons, which is then ignored.  Also termMenuNeuron.jsp is used as a default.  Here are all of the jsp menu files we have.
(Side note - those foreach loops look terribly inefficient!)

jsp/includes/bits/termMenuClone.jsp	
jsp/includes/bits/termMenuNeuropil.jsp	
jsp/includes/bits/termMenuTract.jsp
jsp/includes/bits/termMenuNeuron.jsp
jsp/includes/bits/termMenuQB.jsp

Proposed fix:

1. Add in a lookup to AutocompleteDAO.java for cells”
	map.put(“cell", "subclass&FBbt_00007002");


2. Make termMenuGeneric.jsp (base on current termMenuNeuron.jsp)

3. Make termMenuCell.jsp (base on current termMenuNeuron.jsp minus part query)

4. Edit jsp/do/ontBean.jsp following existing patterns to
    (a) Add test for cell
    (b) Specify termMenuGeneric.jsp as first (potentially over-ridden test)
    (c) Specify new termMenuCell.jsp if test for cell is True

**Comment by dosumis** [comment]
Out of date.  Superseded by classification system in Neo.
