### ISSUE TITLE
Rendering issues on Safari

### ISSUE THREAD

**Issue by korffw** [VirtualFlyBrain/VFB#676]
Support info:
http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000,VFBd_00100026,VFBi_00006287,VFBi_00003915,VFBi_00003794,VFBi_00009884,VFBi_00009938,VFBi_00006191,VFBi_00006192,VFBi_00003743,VFBi_00009955,VFBi_00007805,VFBi_00006212,VFBi_00004708,VFBi_00004716,VFBi_00007352,VFBi_00006364,VFBi_00001045,VFBi_00001308,VFBi_00000469,VFBi_00000592,VFBi_00001170,VFBi_00001766,VFBi_00009725,VFBi_00009687,VFBi_00004035,VFBi_00010349
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9 Size:[2560,1378]
{"_ga":"GA1.5.1831946260.1440100421","_gat_UA-18509775-1":"1","cookie-box":"closed","dev-box":"closed","displaying":"!M571.6!M4!6Z!e8e0!M1511,255,108!e1e!H1!2S!20!2i!6!H1!F5!11!c3c2!I46287!13!I43915!14!I43794!15!I49884!16!I49938!17!I46191!18!I46192!19!I43743!110!I49955!111!I47805!112!I46212!113!I44708!114!I44716!115!I47352!116!I46364!117!I41045!118!I41308!119!I5469!120!I5592!121!I41170!122!I41766!123!I49725!124!I49687!125!I44035!126!I310349!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!H4!2S!20!2i!6!H4!F5!4N!6Adult Ventral Nervous System!11!2i!6!D0a!F33599!0","JSESSIONID":"FC73A656287415743C56A9ABCAC58B6C"}

**Comment by Robbie1977** [comment]
default zoom missing extra padding - resolved in new version
