### ISSUE TITLE
Banners keep coming back in Firefox

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#677]
The yellow (test server) and blue banner (cookies) keep coming back with changes in the viewer. In this case I was changing slice.

I need to use Firefox for what I was doing as it is behaving better with the NBLAST site.

Support info:
http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000,VFBi_00014024
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:39.0) Gecko/20100101 Firefox/39.0 Size:[1265,672]
{"displaying":"!M570.8!M4!6Z!e8e-12!M1511,255,108!e1e!B!11!I314024!4N!6Trh-F-5!F329!4t!O8antennal mechanosensory and motor center B1 projection neuron!O9!4I!K2110120!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!0","_ga":"GA1.5.1256516695.1435940546","JSESSIONID":"C24D78B132EBB1854F495B9817B771AE","_gat_UA-18509775-1":"1"}

**Comment by Robbie1977** [comment]
Temp fix put in place.

**Comment by Robbie1977** [comment]
#679 should resolve this long term.

**Comment by Robbie1977** [comment]
Problem identified as HTML execution order issue and resolved
