### ISSUE TITLE
Need to be able to resolve Parent class from SOLR

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#680]
We need either ID or name of parent class stored in the solr doc.

parent_uri exists in the schema but is not populated

**Comment by dosumis** [comment]
Rather surprising. Can you post an example. Perhaps in different field?  Or may be to do with absence pre-reasoning in source OWL file.

**Comment by Robbie1977** [comment]
Shows all the populated fields:
http://vfbdev.inf.ed.ac.uk/search/ontologySuggest?sort=score+desc&wt=json&indent=ture&rows=2&fl=*,score&q=short_form:FBbt_00003748

**Comment by dosumis** [comment]
OK. Think we need to instantiate more inference during generation of ontology+ind file. Easy to fix.

**Comment by dosumis** [comment]
Notes:

* Instantiation of inference on classes is needed if we are to use one big ontology file with classes + individuals to load into SOLR.
* There also seems to be a problem with SOLR (or our use of it) in that I see no statement of parent classes in the above example.  The OWL has Medulla subClassOf 'synaptic neuropil domain' .     "is_root":false,  Suggests that the loading script knows that this class has asserted parents.

**Comment by dosumis** [comment]
Looks like you could use parent_uri query:

e.g.

http://fub.bar:nnnn/solr/#/ontology/query?q=parent_uri:%22http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00005106%22

**Comment by dosumis** [comment]
Scratch that - this is backwards.  Allows you to specify a parent to get child terms.

**Comment by Robbie1977** [comment]
But can you find the parent from child?

**Comment by dosumis** [comment]
Use child_uri instead:
/solr/#/ontology/query?q=child_uri:%22http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00002071%22

**Comment by dosumis** [comment]
Similar fields are already being used to store large numbers of results for transitive closure over class hierarchy (see ancestor_uri).  Query results could be cached using the same pattern.

**Comment by dosumis** [comment]
ancestor_uri is also a potential alternative route to classification for choice of query menus.

From page: query by ancestor URI -> check for specified class URI in list of results.

**Comment by dosumis** [comment]
New version of individuals file here:

https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/owl/fbbt_vfb_ind_prc_nr.owl.gz

This has instantiated classification for classes, so missing parents in SOLR (or neo4J) should no longer be a problem.

Might want to wait until discussion/demo of Neo4J before implementing anything though.

Note - given a new name for now as I'd like to test whether this is slower for OWL queries than the current ind file.

**Comment by Robbie1977** [comment]
flycircuit links need updating in individual prc (sure you already changed in DB):
VFB_00000001:
should be: http://flycircuit.tw/modules.php?name=clearpage&op=detail_table&neuron=fru-M-200266
currently: http://flycircuit.tw/modules.php?name=clearpage&op=detail_table&idid=1

**Comment by dosumis** [comment]
> what is the field label for parent class?

As mentioned above, you can use child_uri, but I'm convinced we need to switch to pulling metadata from neo4J.  I'll write up an umbrella ticket for this, but did you look at the JSON output examples I sent by mail?

**Comment by dosumis** [comment]
> flycircuit links need updating in individual prc (sure you already changed in DB).

Odd.  I'm sure I did too.  Looking into it now.

**Comment by Robbie1977** [comment]
when is this likely to work for individuals?

**Comment by dosumis** [comment]
> when is this likely to work for individuals?  
Typing by named class only (which we call parent class on VFB) is already available for individuals.

Missing metadata for individuals in OLS (Neo4j and SOLR):
* typing via anonymous class expressions (which we treat as relationships in VFB) 
* OWL Facts (relationships between individuals).  We need these for management of information about registered/patined image context and metadata.
* OWL value restrictions (linking classes to individuals).  We need these for the clusters.
* References on defs (also missing for classes)

We need a strategy and a timeline for getting the missing components into NEO4J (missing elements identical to SOLR).  @simonjupp

Relevant tracker issues:
* https://github.com/EBISPOT/OLS/issues/13
* https://github.com/EBISPOT/OLS/issues/2

**Comment by dosumis** [comment]
> > flycircuit links need updating in individual prc (sure you already changed in DB).

> Odd. I'm sure I did too. Looking into it now.

Fixed. Regnerating

**Comment by Robbie1977** [comment]
Now using child_iri to resolve type in key table in vfbdev for domains.

@dosumis do we have any idea when individuals will support child/parent and also logical descriptions?

**Comment by dosumis** [comment]
Asked again (https://github.com/EBISPOT/OLS/issues/13#issuecomment-154449431).
Planning to script myself if it's not happening soon.

Note - also straightfoward from neo4J.  See
https://github.com/VirtualFlyBrain/VFB_2/blob/master/schema_draft_docs/using_neo4J_for_crude_typing.md

One potential advantage of neo4J is that you'll be able to use it to pull
pub metadata:  I'm planning to import this from  FB (and possibly some
other sources) into neo4J - probably as nodes in their own right.
Individuals can also be pulled directly from neo4J without any intervening
elk query - although not super fast.  High up the graph I'm getting query
times of 2-3 seconds.

Prototyping this on a server at the EBI but for you to have access I'll
need to be able to run scripts against Edinburgh instances.

Is it possible for you to open up neo4J and SOLR instances in Edinburgh
that I have write access to via the API?  Would obviously need to be via VPN

**Comment by dosumis** [comment]
Works in Neo4J.
