### ISSUE TITLE
Need to resolve 'type' for anatomy in SOLR

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#681]
Need to identify anatomy into classes such as neuropil, neuron, clone etc.

This is required for identifying available queries however we could simply record that an item has a number of neurons with synapses here; ideally the id's of results precomputed?

**Comment by dosumis** [comment]
This = high level classes used for structuring site. Agreement is to use reasoner to add subset tags.

**Comment by dosumis** [comment]
Added as labels in Neo4J: https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/add_constraints_and_redundant_labels.py
