### ISSUE TITLE
Adding dates to releases page

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#684]
It would be more useful if in the Releases page, in addition to 

The site is currently using version FB2015_04 of the FlyBase chado database.

it would say the date of this release. 

Also, it would be good if there was sentence with the date of the current VFB release.

**Comment by Robbie1977** [comment]
where could we get this information? is there an official date?

**Comment by mmc46** [comment]
There is a release schedule for FlyBase.

http://flybase.org/static_pages/docs/release_schedule.html <http://flybase.org/static_pages/docs/release_schedule.html>

and another listing here

http://flybase.org/static_pages/downloads/archivedata3.html <http://flybase.org/static_pages/downloads/archivedata3.html>

Sometimes the release gets delayed by a few days. The actual release date is always shown in the footer and header on the site, I’m not sure if it’s practical to grab it from there.

Header:
New Release: FB2015_04, released September 3rd, 2015

Footer:
version FB2015_04, released September 3, 2015

**Comment by Robbie1977** [comment]
I've used the file date from the public ftp now shows:
[ FB2015_04 released on 03/09/15 ]
