### ISSUE TITLE
Making consistent download buttons

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#685]
The buttons have blue background in results and grey in viewer. And different options available.

![viewer](https://cloud.githubusercontent.com/assets/1872083/9683148/40f4315a-5305-11e5-850a-84205365ce4c.png)
![results](https://cloud.githubusercontent.com/assets/1872083/9683149/40f9e7b2-5305-11e5-8b08-8eec9ffa49b3.png)

Can they be made consistent? I prefer the grey background, the font looks a bit weird on the blue.

**Comment by Robbie1977** [comment]
That's due to the report not yet being updated to latest version if you're happy I'll update all to match.

I limited the options to the essential but could add pdf and/or excel but they seem superfluous as csv is more universal and print does a better job then pdf.

**Comment by Robbie1977** [comment]
These have now all been changed to the latest version and new layout
