### ISSUE TITLE
Search in header not finding terms

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#691]
I've tried a search in dev and sandbox3 with 'protocere' and not getting any hits.
Some other ones had worked fine.
![search_issue](https://cloud.githubusercontent.com/assets/1872083/9741862/bdf5ac0e-5654-11e5-890b-75bca9463c6a.png)

**Comment by Robbie1977** [comment]
There is a serious issue with the SOLR not resolving on some examples such as 'AMM'

@dosumis more to discuss with simon which hopefully is already fixed. If he has a new (stable) version let me know ASAP and I'll get it reinstalled for sandbox demo.

**Comment by mmc46** [comment]
Can we please get some kind of fix for this before the FliACT workshop on Friday morning? 

Neither 'AMMC' or the full name  'antennal mechanosensory and motor center' give any results.

**Comment by Robbie1977** [comment]
Give me the ids and I can add to initial list in the source of the page

**Comment by mmc46** [comment]
FBbt:00003982 antennal mechanosensory and motor center

FBbt:00045051 cantle

FBbt:00110633 antennal mechanosensory and motor center AMMC-IVLP projection neuron 2

FBbt:00050019 adult DM1 lineage clone

None of the queries I've tried today on sandbox3 today has worked.

**Comment by Robbie1977** [comment]
Sandbox3 is still on faulty DB will be swapping back today - was just testing Josh's suggestions.

**Comment by Robbie1977** [comment]
How are the searches on vfbdev?

**Comment by mmc46** [comment]
It’s working on dev, thanks.

The only thing I’ve noticed, which you’d mentioned before was that a search for ‘can’t doesn’t work, but the full word ‘cantle’ does.

**Comment by Robbie1977** [comment]
should now be working better.

**Comment by mmc46** [comment]
Much better thanks.
