### ISSUE TITLE
QueryBuilder not working in 1.5

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#692]
### VFB 1.5
on http://vfbdev.inf.ed.ac.uk/

![image](https://cloud.githubusercontent.com/assets/112839/9758521/1de14b66-56df-11e5-9e10-011782066919.png)

### VFB 1 (public)
![image](https://cloud.githubusercontent.com/assets/112839/9758554/40d53b14-56df-11e5-81dd-0f394efd41bb.png)

**Comment by Robbie1977** [comment]
Is working in my browser - can you ensure you're not getting a cached version from the broken FB DB

**Comment by dosumis** [comment]
OK.  Clearing browser history fixed it.  (Can't be anything to do with broken FB though as QB queries don't use FB at all).

**Comment by Robbie1977** [comment]
just re-enable cache and check there isn't any issues with caching the result page but haven't had any issues during my testing but will keep an eye out.
