### ISSUE TITLE
Add filter or option to show all results in viewer page

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#696]
When displaying a lot of things in the viewer, these get ordered into pages, like in other result pages.
But, in contrast to those, there is no option to filter, or to change the number of things displayed in a page. 
Finding a specific neuron, for example, then takes much longer.

Either making these lists the same as normal results list (both options present) or at least one of these would be good.

**Comment by Robbie1977** [comment]
Trying to declutter as per feedback so we need to decide what options we need.

Might attempt to force a conditional hide so these things only appear when needed - say when more than 10 items are shown. This has proved tricky in the past as fighting the inbuilt updates (hence type reappearing)

**Comment by Robbie1977** [comment]
have re added the selection tool as fits under list with new layout.

Filter is proving to be an issue as doesn't seem to function in current build - hopefully will be resolved in new build so leaving out for now as page search works with all shown.
