### ISSUE TITLE
Viewer displayed type column

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#697]
The Viewer table used to show a 'type' column in the Displayed tab. This has now disappeared (on dev).
That column made it very easy to see what type of neuron it was, comparing through a list of displayed neurons, and it would be good to have it back. 

Now, to see that information, I have to click on each neuron at a time and look at the term info.

![current_columns](https://cloud.githubusercontent.com/assets/1872083/9786847/270a851e-57b5-11e5-82dd-240eba09b738.png)
![previous_columns](https://cloud.githubusercontent.com/assets/1872083/9786848/270c2b6c-57b5-11e5-9516-c2cfc0930f12.png)

**Comment by Robbie1977** [comment]
once included in the solr data it will return

**Comment by Robbie1977** [comment]
returned
