### ISSUE TITLE
Links to fly circuit broken

### ISSUE THREAD

**Issue by fewtrem** [VirtualFlyBrain/VFB#706]
nav to: http://www.virtualflybrain.org/do/cluster_list.html?action=cluster_found&id=FBbt:00007053
Click on the pink image, it says "You can't access this file directly..."

**Comment by jefferis** [comment]
That's sthg they've changed. But would be worth checking if one of the other identifier types works (rather than idid integer id).

**Comment by Robbie1977** [comment]
they seem to use nid but that appears not to be the same thing?

**Comment by Robbie1977** [comment]
can use the name:
http://flycircuit.tw/modules.php?name=clearpage&op=detail_table&neuron=fru-F-400149

**Comment by Robbie1977** [comment]
Currently modifying remote id's to match names:
```
UPDATE third_party_site_lookup
SET remoteid = local_stack_url
WHERE source_name = 'FlyCircuit'
```

**Comment by Robbie1977** [comment]
working fine on dev site going to update live service now.

**Comment by Robbie1977** [comment]
All fixed!

**Comment by dosumis** [comment]
@Robbie1977 
This info is now in the mysql DB. Full linkout URLs are now in  annotation axioms in the owl.  Thought you'd switched to this - but guess you're waiting for SOLR.  Anyway - this now needs to be updated.  Given that we're struggling in this case to get a reliable unique ID for linkouts, it may be worth extending the MySQL to make a dbxref table allowing multiple linkout IDs for an image. (Thinking about it - probably worthwhile anyway given that multiple hosting of the same data is likely to become more common in future.)

**Comment by dosumis** [comment]
See #442
