### ISSUE TITLE
Flybase report link not working

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#708]
http://flybase.org/reports/FBtp0023247.html not resolving.

Support info:
http://vfbdev.inf.ed.ac.uk/do/gene_list.html?action=transgene&id=FBbt_00100248
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36 Size:[1920,630]
!M571.1!M4!6Z!e8e26!M1511,255,108!e1e!B!11!I47702!4N!6Cha-F-200103!G!C!G!D8!G!P3!4N!6Adult Ventral Nervous System!0

**Comment by Robbie1977** [comment]
not sure if our link is out of date or flybase is missing it?

**Comment by mmc46** [comment]
It should be linking to the insertion, FBti, not the construct, FBtp.

http://flybase.org/reports/FBti0100742.html

**Comment by Robbie1977** [comment]
it is resolving correctly for all other genes in that report so the question is this wrong in flybase or in one of our DB's?

**Comment by dosumis** [comment]
This must be an error in FlyBase.  I'll try to trace.

**Comment by dosumis** [comment]
Seems to be an expression record for an obsolete feature.  I thought these
were flushed in a cascading delete, but doesn't seem to have happened - at
least here.  I can add a check for obsolete features in the view table
generation.  @Robbie1977 - where does the SQL for view generation live
now?  Seems to have moved.

Note to self:

SQL generating view tables vfbview_transgene_expressed_gp &
vfbview_gene_expressed_gp

Both need an additional clause in the WHERE:

and feature.is_obsolete IS FALSE

Must be from same join to feature as used for column transgene_feature_id.

**Comment by Robbie1977** [comment]
in the GIHUB repo:

https://github.com/VirtualFlyBrain/VFB_DB/blob/master/TableQueries/chado_views_for_vfb.sql

**Comment by dosumis** [comment]
Pushed fix to master on 
https://github.com/VirtualFlyBrain/VFB_DB

SQL tested on public chado.

Please drop the view tables:
vfbview_transgene_expressed_gp
vfbview_gene_expressed_gp
& regenerate.
Ta,
David

**Comment by Robbie1977** [comment]
After rebuilding twice just noticed that No update is shown on VFB_DB - are you sure you pushed it?

**Comment by dosumis** [comment]
Not sure why that didn't work. Just pushed again. This time looks successful. Sorry. David

**Comment by Robbie1977** [comment]
fix works!

Blanik done, bocian next.
