### ISSUE TITLE
Images returning after clear all

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#712]
I first noticed this on Friday morning, and again today.
Sometimes, when I clear the display with 'clear all', and then open another tab or refresh the page, the images are still shown on the viewer.

This is happened with vfbsandbox3 for sure (not sure with dev).

**Comment by Robbie1977** [comment]
I need to modify the storage mechanism to cope with multiple tabs as data is just being overwritten by whichever is the last to save.

**Comment by Robbie1977** [comment]
@mmc46 should now be consistent between windows.
