### ISSUE TITLE
Query shows incorrect total before query run

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#714]
Check cache not causing issue

Support info:
http://vfbdev.inf.ed.ac.uk/do/ont_query_result.html?action=multiquery
Mozilla/5.0 (iPhone; CPU iPhone OS 9_0 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13A344 Safari/601.1 Size:[414,628]
!M87-0.2!M4!6Z!e8e0!M1255,511,115!E!H1!2S!20!2i!6!H1!F5!11!I42495!12!I49974!13!I47358!14!I49931!15!I41173!16!I5180!17!I314351!18!I314569!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!4N!6Adult Ventral Nervous System Template!0

**Comment by dosumis** [comment]
Seeing a lot of these data problems that seem to come from caching issues.
Is it worth adding an agenda item for the next meeting to discuss caching
strategy, why it is needed and how it can be managed to avoid stale data
problems?

**Comment by Robbie1977** [comment]
This issue is caused by the count coming from a static url so there is no way to know its a different request. This can be solved by putting a timecode in request or removing caching on that request in Apache setup.

This is the only issue I'm aware of?

**Comment by dosumis** [comment]
Another example (?) - After you reverted to the old FlyBase release last
week when the new FlyBase dump got screwed up, I couldn't get results for
many queries until I cleared the cache (at your instruction)

**Comment by Robbie1977** [comment]
This is a situation that should never occur and without not using caching there isn't much we can do to prevent caching doing caching - we could enforce checking but that slows everything down just as much. This would clear naturally after the max timeout. If this situation did occur I'd disable caching for the timeout period to prevent the faulty data being used.

**Comment by Robbie1977** [comment]
Ultimately I'll limit or reduce caching on the Dev servers so changes show immediately.

**Comment by Robbie1977** [comment]
I've enabled any page to prevent itself being cached - should only be necessary when the url doesn't change with the query.

so the query results (including count) and the query builder should no longer be cached.
