### ISSUE TITLE
Title of example queries section hidden when resizing

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#720]
Support info:
http://vfbdev.inf.ed.ac.uk/site/vfb_site/home.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36 Size:[2247,1433]
!M57-0.1!M4!6Z!e8e0!M1511,255,108!e1e!B Template!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

![resize](https://cloud.githubusercontent.com/assets/1872083/10098267/fc3e404a-6377-11e5-8216-566e93f7d7c3.png)

**Comment by mmc46** [comment]
This resizing issue also happens in viewer page.

Referring page: http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000,VFBd_00100026,VFBd_00100017,VFBd_00100036,VFBd_00100019,VFBd_00100018,VFBd_00100009
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36 Size:[2115,1478]
LocalData: !3C!2T!6!H1!A511,255,108!E!H1!2S!20!2i!6!H1!F5!11!c3c2!c6c3!c7c4!c8c5!c9c6!j1!F49!4e!L0345048!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

![viewer_resize](https://cloud.githubusercontent.com/assets/1872083/10100686/57294ec4-638b-11e5-9e39-02505e4b67bf.png)

**Comment by Robbie1977** [comment]
I'm assuming you've done a search (maximising the search box width) before reducing the page size?

I'll look at shrinking the search after completion.

**Comment by mmc46** [comment]
Yes, or at least I typed something in, even if I didn’t end up choosing any of the results.

**Comment by Robbie1977** [comment]
will now shrink back every time you leave the search
