### ISSUE TITLE
Obsolete neuropil in tree

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#721]
The term delta is shown on the anatomy tree. This term is obsoleted, and it shouldn't be shown.

Referring page: http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000,VFBd_00100026,VFBd_00100017,VFBd_00100036,VFBd_00100019,VFBd_00100018
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36 Size:[2183,1478]
LocalData: !3C!2T!6!H1!A511,255,108!E!H1!2S!20!2i!6!H1!F5!11!c3c2!c6c3!c7c4!c8c5!j1!F318!4e!L0315407!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by Robbie1977** [comment]
Removed 

FYI the data for the tree is in meta.json and tree.json in the template repository under refData folder:
https://github.com/VirtualFlyBrain/DrosAdultBRAINdomains/tree/master/refData
