### ISSUE TITLE
VFB beta link on front page of old site

### ISSUE THREAD

**Issue by jefferis** [VirtualFlyBrain/VFB#723]
@Robbie1977 @mmc46  I think this would be helpful based on feedback at the meeting. Thanks, Greg.

**Comment by cahirokane** [comment]
Agreed - I think that people liked playing around with the new interface. Should be OK if the link (and the new site) are clearly labeled as beta versions. 
Cahir

**Comment by Robbie1977** [comment]
Live now in the new features - will add a blog post next
