### ISSUE TITLE
Viewer sliders moving to left

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#733]
After refreshing the page, they show up on top for 2-3 seconds, then move to the left for 2-3 seconds and then back to the top.

![sliders](https://cloud.githubusercontent.com/assets/1872083/10763370/960b00ca-7cc1-11e5-9f2f-a08dbda72a58.png)

Referring page: http://vfbdev.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36 Size:[2457,1454]
LocalData: !M57-0.1!M4!6Z!e8e0!M1511,255,108!E!B Template!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by Robbie1977** [comment]
Seems to occur when the DOM selects all objects causing all to open - haven't been able to pin down why hence the watchdog that is hiding them when it does happen.

**Comment by Robbie1977** [comment]
Finally resolved this on in vfbdev
