### ISSUE TITLE
anatomy finder links still in place in type column

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#747]
Support info:
http://vfbsandbox3.inf.ed.ac.uk/do/individual_list.html?action=exemplar_neuron&id=FBbt:00067363
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 Size:[1289,621]
!M57-0.1!M4!6Z!e8e-53!M1511,255,108!E!B Template!11!j1!F326!4e!L043679!4L!687!4t!6synaptic neuropil domain!L212!j1!F47!4e!L047053!4L!6187!4t!6synaptic neuropil domain!L2G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by Robbie1977** [comment]
@dosumis resolved but you might need to click refresh to ensure it's not using the cached copy.
