### ISSUE TITLE
Fail to load list of images from results page

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#750]
Error info:
http://vfbsandbox3.inf.ed.ac.uk/do/individual_list.html?action=exemplar_neuron&id=FBbt:00110327
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

**Comment by Robbie1977** [comment]
@dosumis can you confirm this no longer occurs?
