### ISSUE TITLE
linked image from cluster query - metadata not in term info

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#752]
Clicking on exemplar image here
http://vfbsandbox3.inf.ed.ac.uk/do/cluster_list.html?action=cluster_found&id=FBbt:00007053

=> individual added to stack viewer, but metadata not displayed in TermInfo

Support info:
http://vfbsandbox3.inf.ed.ac.uk/do/cluster_list.html?action=cluster_found&id=FBbt:00007053
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 Size:[1302,621]
!M57-0.1!M4!6Z!e8e0!M1511,255,108!e1e!H1!2S!20!2i!6!H1!F5!11!j1!F326!4e!L043679!4L!687!L212!j1!F47!4e!L047053!4L!6187!L213!I313061!L1367363!14!j1!F336!4e!L047385!4L!6116!L143685!15!j1!F324!4e!L047401!4L!62!L143924!16!I46475!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by Robbie1977** [comment]
Same issue as #753

**Comment by Robbie1977** [comment]
Resolved in the latest build
