### ISSUE TITLE
Clicking on thumbails in individual TermInfo => 404 rather than adding to stack

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#754]
e.g. Try Gad1-F-200073

The image doesn't look like it is hyperlinked (cursor doesn't change on floatover).  But it can be clicked => http://vfbsandbox3.inf.ed.ac.uk/site/stacks/site/stacks/index.htm.

It should simply add to stack browser.

(Found during UX testing)

Support info:
http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 Size:[1296,666]
!M57-0.1!M4!6Z!e8e0!M1511,255,108!e1e!H1!2S!20!2i!6!H1!F5!11!j1!F326!4e!L043679!4L!687!L212!j1!F47!4e!L047053!4L!6187!L213!I313061!L1367363!14!j1!F336!4e!L047385!4L!6116!L143685!15!j1!F324!4e!L047401!4L!62!L143924!16!I46475!L1367367!17!I315955!L1367367!18!I311319!L1367353!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by Robbie1977** [comment]
Resolved in latest build
