### ISSUE TITLE
Viewer refreshes on its own (when multiple windows are open)

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#759]
When nothing is being done, the viewer keeps on refreshing. The interval between refreshes seems to vary.

This is on dev.

Movie of this happening has been sent to Rob, as it's not supported here.

Referring page: http://vfbdev.inf.ed.ac.uk/site/stacks/index.htm
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 Size:[2113,1434]
LocalData: !M57-0.1!M4!6Z!e8e-6!M1511,255,108!e1e!H1!2S!20!2i!6!H1!F5!11!I47819!12!I44669!13!I44719!14!I44824!15!I44724!4I!K2110417!16!I323120!17!I323207!18!I321498!P19!I322681!P110!I322495!4v!7!P8}}!8!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by Robbie1977** [comment]
is this in firefox?

**Comment by mmc46** [comment]
Chrome/46.0.2490.86

**Comment by Robbie1977** [comment]
Does this happen repeatably?

What are your zoom and slice settings as they appear odd?

```JSON
{"current":{"template":"VFBt_001","scl":-0.1,"mod":"zeta","slice":"Z","dst":-6,"pit":0,"yaw":0,"rol":0,"qlt":80,"cvt":"png","fxp":"511,255,108","alpha":100,"blend":"screen","inverted":false},"VFBt_001":{"selected":{"0":{"id":"VFBt_00100000"},"1":{"id":"VFBi_00007819"},"2":{"id":"VFBi_00004669"},"3":{"id":"VFBi_00004719"},"4":{"id":"VFBi_00004824"},"5":{"id":"VFBi_00004724","typeid":"FBbt_00110417"},"6":{"id":"VFBi_00023120"},"7":{"id":"VFBi_00023207"},"8":{"id":"VFBi_00021498","visible":false},"9":{"id":"VFBi_00022681","visible":false},"10":{"id":"VFBi_00022495","visible":false}}},"VFBt_002":{"selected":{"0":{"id":"VFBt_00200000"}}},"VFBt_003":{"selected":{"0":{"id":"VFBt_00300000"}}},"VFBt_004":{"selected":{"0":{"id":"VFBt_00400000"}}}}
```

**Comment by mmc46** [comment]
Those details are shown in the movie. It happens repeatably.

**Comment by Robbie1977** [comment]
Does it occur immediately on load or after time?

Do you have more than one window open?

Sorry about all the questions but I can't repeat on any browser here but the scl (zoom) level being minus in your local data (from report) hints at the settings getting corrupted possibly by a load from another window (fixing that issue now).

Can you open the inspect element window then reload page and copy the status history from the console when it happens?

**Comment by mmc46** [comment]
It only seems to happen if I have more than one window open.
A few seconds after opening the second window, without changing the zoom or slice, it starts happening.

The console says

overridden by another session

**Comment by Robbie1977** [comment]
It's alternating control between the two screens which triggers a rescaling event - hence the clear and redraw. 
Preventing shared zoom and distance settings between screens.
Ensuring only the active window stores it's data.

**Comment by Robbie1977** [comment]
Speeding up the switchover and putting an * on the title of the slaved window.

**Comment by Robbie1977** [comment]
Resolved
