### ISSUE TITLE
New menu item for users to tell us about their paper

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#769]
I've been noticing that a few important anatomy and/or expression papers are not being flagged by users when they get their FlyBase email after publication. This means they go under the radar and they're not curated as quickly as they should.

Can we add a new menu item, maybe to 'Site', for them to tell us about their paper, and encouraging them to fill in their FlyBase email (named maybe 'Tell us about your paper').

This could also go in 'About us', subsection 'Contact us' but wouldn't be so noticed there.

**Comment by Robbie1977** [comment]
agreed, can we provide the same link at the flybase email to avoid them having to search through the junk/deleted etc?
It Might be a good idea to have a specific menu to encourage users to flag their data or and mistakes/issues in the data (Nomenclature SourceForge Tickets) etc.

**Comment by mmc46** [comment]
Each person gets an individual link, which pre-selects the publication, but we could link to the general tool.

http://flybase.org/submission/publication/

**Comment by Robbie1977** [comment]
Added by @mmc46
