### ISSUE TITLE
Janelia Brain image in home is squashed

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#770]
On dev, the image of the Janelia Brain in home looks squashed along its width. Could this be corrected?

**Comment by Robbie1977** [comment]
Which image in particular - do you have a screen capture?

**Comment by mmc46** [comment]
![squashed_jfrc](https://cloud.githubusercontent.com/assets/1872083/12512177/94d95d5a-c10e-11e5-82a5-84f825e7eb0c.png)

**Comment by Robbie1977** [comment]
I've tweaked the max ratio so if you check in 2 minutes should be better.
