### ISSUE TITLE
Adding neuropil from Anatomy tab -> Displayed tab

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#771]
Whenever a neuropil is added from the Anatomy tab in the Viewer page, the Displayed tab is shown. 

When adding more than one neuropil this behaviour wastes time and becomes annoying. 
Could this be changed, so that the neuropil is added but the Anatomy tab remains open?

**Comment by Robbie1977** [comment]
Have prevented the tab from changing for anything other than a selection on the image
