### ISSUE TITLE
News falls to botom left

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#784]
As the screen gets bigger, the news falls to the left, below the videos. Can this be prevented? So always keeping it to the right of the videos.

Support info:
http://vfbdev.inf.ed.ac.uk/site/vfb_site/home.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0 Size:[2366,1431]
!M56-0.1!e2eZ!e8e0!M1511,255,108!E!B Template!G!C Template!G!D8 Template!4t!6<a href=\"http://www.flybase.org/reports/FBgn0259246.html\" target=\"_blank\">Nc82</a>\n\t\t\t\t\t\t\t!G!P3!4N!6Adult Ventral Nervous System Template!0

**Comment by Robbie1977** [comment]
I'll fix the news tab so it behaves as all the others and goes full width at the point is goes to mobile screen width.
