### ISSUE TITLE
Add link back to VFB classic from front page?

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#789]
Assuming you are going to keep VFB 1 running for some transition period.  If so, can you add a link back to it from the front page?

**Comment by Robbie1977** [comment]
Sandbox1 (http://vfbsandbox1.inf.ed.ac.uk/) has been configured as a old server copy.

Rather just put this in bottom of the news release and discretely in the 'site' menu as would rather people started using the new site. Open to suggestions but don't advise putting it prominently as suggests we don't have confidence in the new system.

**Comment by mmc46** [comment]
That sounds good to me.
