### ISSUE TITLE
Losing layers following fast sliding through sections:

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#892]
Followed this link from the front page: http://www.virtualflybrain.org/site/stacks/index.htm?add=VFBt_00100000,VFBi_00016207,VFBi_00020020,VFBi_00020062&clear=true

Tried scrolling though sections in stack.  Stained layers disappeared.  Only background is visible.

Support info:
http://vfb-bocian.inf.ed.ac.uk/site/vfb_site/home.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36 Size:[1623,690]
!M56-0.1!e2eZ!e8e0!M1511,255,108!E!B Template!11!j1!F49!4e!L0345048!4L!6252!L24t!6synaptic neuropil domain!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by Robbie1977** [comment]
This is normal - they should have redrawn the second you stop scrolling

**Comment by dosumis** [comment]
>  they should have redrawn the second you stop scrolling

But they didn't, and still haven't.

**Comment by Robbie1977** [comment]
can you inspect the page and list any errors?

**Comment by Robbie1977** [comment]
one of the libraries we use seems to have gone offline:
http://cdn.datatables.net/s/bs/jszip-2.5.0,pdfmake-0.1.18,dt-1.10.10,b-1.1.0,b-flash-1.1.0,b-html5-1.1.0,b-print-1.1.0,r-2.0.0,sc-1.4.0/pdfmake.min.js.map

**Comment by dosumis** [comment]
> one of the libraries we use seems to have gone offline:

Can we have a test for that?

Here's JS console (seems to be some problem with access control?)

Failed to load /fcgi/wlziipsrv.fcgi?wlz=/disk/data/VFB/IMAGE_DATA/VFB/i/0002/0062/volume.wlz&sel=0,0,0,255&mod=zeta&fxp=511,255,108&scl=1.1&dst=39&pit=0&yaw=0&rol=0&qlt=80&cvt=png
/site/stacks/index.htm?id=VFB_00016207:1 XMLHttpRequest cannot load http://vfb-bocian.inf.ed.ac.uk/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.virtualflybrain.org' is therefore not allowed access.
stackManager.js:1357 error,,
stackManager.js:1357 Failed to load /fcgi/wlziipsrv.fcgi?wlz=/disk/data/VFB/IMAGE_DATA/VFB/i/0001/6207/volume.wlz&sel=0,0,255,0&mod=zeta&fxp=511,255,108&scl=1.1&dst=3&pit=0&yaw=0&rol=0&qlt=80&cvt=png
stackManager.js:1357 Failed to load /fcgi/wlziipsrv.fcgi?wlz=/disk/data/VFB/IMAGE_DATA/VFB/i/0002/0020/volume.wlz&sel=0,255,0,255&mod=zeta&fxp=511,255,108&scl=1.1&dst=3&pit=0&yaw=0&rol=0&qlt=80&cvt=png
/site/stacks/index.htm?id=VFB_00016207:1 XMLHttpRequest cannot load http://vfb-bocian.inf.ed.ac.uk/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.virtualflybrain.org' is therefore not allowed access.
stackManager.js:1357 error,,
/site/stacks/index.htm?id=VFB_00016207:1 XMLHttpRequest cannot load http://vfb-bocian.inf.ed.ac.uk/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.virtualflybrain.org' is therefore not allowed access.

**Comment by Robbie1977** [comment]
That was a read herring as not even sure were Safari is getting the error.
Have switched to the backup and am resolving what seems to be a Smudge filter error.

**Comment by dosumis** [comment]
Seems to be working right now.  Had the bug several times earlier.

**Comment by Robbie1977** [comment]
Rechecking all refs to be sure but should be back in 2 secs.

**Comment by Robbie1977** [comment]
Do you want to check at your end and then send an all clear on twitter
