### ISSUE TITLE
csv files for clusters with incorrect fields

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#893]
[Virtual Fly Brain Neurons with some part in saddle, clustered by shape.xlsx](https://github.com/VirtualFlyBrain/VFB/files/152706/Virtual.Fly.Brain.Neurons.with.some.part.in.saddle.clustered.by.shape.xlsx)

This is referenced in to https://github.com/VirtualFlyBrain/Management/issues/11, but it makes more sense here.

The csv download option for cluster doesn't work very well, with the fields not correct.
An example csv is attached, from this query. 

http://www.virtualflybrain.org/do/cluster_list.html?action=cluster_found&id=FBbt:00045048

Currently, with many extra columns:

Cluster | Exemplar name | Summary Source | Exemplar Preview | Members of cluster | extra | extra | extra | extra | extra | extra | extra
---------|--------|-----|--------|-------|--------|-------|-------|-------|-------|------|-------|
saddle| clustered by shape: VGlut-F-800026 | A neuron expressing P{VGlut-GAL4.D} that is part of an adult female brain"> | VGlut-F-800026 | A neuron expressing P{VGlut-GAL4.D} that is part of an adult female brain | FlyCircuit | saddle | clustered by shape: FlyCircuit (VGlut-F-800026) | VGlut-F-800026 | A neuron expressing P{VGlut-GAL4.D} that is part of an adult female brain" onclick="post('/site/stacks/index.htm' | {'add':'VFB_00014922'});" style="cursor: pointer;"> | List individual members | 

The file should have columns:
- cluster (VFB id of exemplar)
- exemplar name
- summary (description)
- source (in this case FlyCircuit)

**Comment by Robbie1977** [comment]
it's the commas in the alt text that are creating extra rows - I'll get a fix on vfbdev ASAP

As for customising what columns are returned this might require some more planning as would need to look at all reports.

**Comment by Robbie1977** [comment]
FYI Datatables should be quoting the fields (by default) is the first issue (https://datatables.net/reference/button/csv) so updating all the libaries as had left them untouched to not change anything.

**Comment by Robbie1977** [comment]
Now we're getting the columns in the right place:
![image](https://cloud.githubusercontent.com/assets/4630768/13428427/59833a7e-dfb2-11e5-9f10-e9531216c3ad.png)

So I'll look at dropping the extraneous fields...

it's also changed the look slightly too.

**Comment by mmc46** [comment]
Something wrong with the formatting of the page on dev now (as compared to main), not sure if related.

![vfbdev](https://cloud.githubusercontent.com/assets/1872083/13428616/8aff0b04-dfb3-11e5-82cf-d082cb28a149.png)

![vfbmain](https://cloud.githubusercontent.com/assets/1872083/13428621/8f94e03a-dfb3-11e5-8e39-953339ff0f0b.png)

**Comment by Robbie1977** [comment]
As I said this was why I hadn't updated to latest version as it's totally changed the default formatting. 
It will take some work to get the formatting configured - do we want to aim for what we had before?

**Comment by Robbie1977** [comment]
@mmc46 looking at what we put in the columns and the first column is an issue as we don't actually use the VFB cluster id's and hence don't have access in the report, given that what do we want in the first column?

It should be at present  (without bugs): "Neurons with some part in <i>saddle</i>, clustered by shape: VGlut-F-800026"

**Comment by mmc46** [comment]
Exemplar name?

**Comment by mmc46** [comment]
"It will take some work to get the formatting configured - do we want to aim for what we had before?"
Yes, if possible.

**Comment by Robbie1977** [comment]
added space round the cluster image

**Comment by Robbie1977** [comment]
@mmc46 if you're happy with the new layout I can start propagating to the other report and look at their outputs too.

**Comment by mmc46** [comment]
Two more things, if possible: 
- remove the black border
- centre the column names

**Comment by Robbie1977** [comment]
coming now

**Comment by mmc46** [comment]
The column names still don't show centred to me.

**Comment by Robbie1977** [comment]
Done - do you think centred, left or justified for actual text?

**Comment by mmc46** [comment]
I'd say centred or justified. I'd probably check how the justified looks in a bigger screen.

**Comment by Robbie1977** [comment]
gone with centred

**Comment by mmc46** [comment]
Looks good to me, thanks.

**Comment by Robbie1977** [comment]
All report have been reformatted inline on vfbdev
