### ISSUE TITLE
Top menu extending down in viewer

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#894]
This is now happening on the viewer page in Firefox. I checked, didn't see it in chrome.

![top_bar_issue](https://cloud.githubusercontent.com/assets/1872083/13436260/479b8cb6-dfd6-11e5-8086-07b84856b8d3.png)

Support info:
http://www.virtualflybrain.org/site/stacks/index.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:43.0) Gecko/20100101 Firefox/43.0 Size:[1204,640]
!M56-0.1!e2eZ!e8e-51!M1511,255,108!E!B Template!11!j1!F49!4e!L0345048!4L!6252!L24t!6synaptic neuropil domain!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by Robbie1977** [comment]
The actual menu ('site' etc) seems to be more to the right will try and figure out what firefox is interpreting differently.

**Comment by Robbie1977** [comment]
added space round the cluster image

**Comment by Robbie1977** [comment]
Resolved in vfbdev
