### ISSUE TITLE
Selection of neuropil blocks

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#940]
Selection by clicking on the stack viewer should select the most specific neuropil ('synaptic neuropil').  Selection of the encompassing block as well (which happens now) is confusing and unlikely to conform to user expectations.  Even if the users can work out what's going on, it still takes time to deselect the blocks in order to see the more specific neuropils.

I can understand that this is in place in order to allow selection of tracts when they overlap painted neuropils, so there are bigger discussions to be had about default behaviour.   But I still think it is an important issue to deal with ASAP.

**Comment by Robbie1977** [comment]
Need to let the system to be able to differentiate as the two have no difference. As a temporary measure I was planning on utilising the 'selected' metadata to control what anatomy is reported by click and which are added when adding all anatomy.
We will need to ensure this is covered in the neo4j data for all domain individuals in future.

**Comment by dosumis** [comment]
It is trivial to add more neo4J labels to classify neuropils by type: block vs domain vs subdomain.  The rule of preference for selection can then be

subdomain > domain > block. 

Would this be quick enough?

**Comment by Robbie1977** [comment]
we'd need the indexes stored with the anatomy so we could run a query for the first result with a set background, matching a set of indexes, ordered by subdomain, domain, block.
If that isn't quick enough then we might need to buffer the anatomy tree for the background that is open on load to work it out.

**Comment by dosumis** [comment]
Storing index numbers is pretty straightforward and already planned. Simpler to do once channels and images are coming from neo4J-KB rather than LMB, as otherwise we need to hack/extend the LMB SQL schema.

**Comment by Robbie1977** [comment]
The original issue is now resolved.
