### ISSUE TITLE
Results list keeps reordering on its own - main site

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#942]
Doing a query for subclasses or 'motor neuron'. The results page, showing 10 of 198 results, keeps reordering the hits, every few seconds, and only stopped after 4-5min. This means that the hits shown at any one time keep changing.

I'll upload a movie to slack after making the ticket. 
See movie for example. It's in lowres but you can see the names changing.

Referring page: http://www.virtualflybrain.org/do/ont_bean_list.html?action=subclass&id=FBbt:00005123
System details: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:47.0) Gecko/20100101 Firefox/47.0 Size:[2022,1431]
LocalData: !M56-0.1!e2eZ!e8e0!M1511,255,108!E!B Template!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by mmc46** [comment]
I think @Robbie1977 has fixed this, but he can confirm.

**Comment by Robbie1977** [comment]
This was resolved and has been pushed live.
