### ISSUE TITLE
Add direct links from Individual neurons to NBLast queries

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB#997]
It is now possible to launch NBLast searches for specified neurons directly on the LMB NBlast site. 

e.g. http://flybrain.mrc-lmb.cam.ac.uk:8080/NBLAST_on-the-fly/#query_all=fru-M-500112,all_use_mean=TRUE

In order provide NBLAST functionality easily from VFB, we should use these to provide NBLAST query links from individual neurons on VFB to search for similar neurons and (most importantly) to search for predicted GAL4 driver lines.   This can be replaced later by are own NBLAST queries, but  given demand I think it is worth getting this functionality on VFB ASAP. 

This will work for any single neuron from FlyCircuit.  Should be able to use Neo to check this.  Please let me know if any more work needed to achieve this.

**Comment by jefferis** [comment]
Just to add that these queries are actually live although the real computation has already been done. We will need to keep an eye on server load (there is a tiny server right now) and consider linking to some kind of cached version if necessary. Thoughts @ajdm?

**Comment by Robbie1977** [comment]
Links added to http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?id=VFB_00000003 

Awaiting query-all fix in https://github.com/jefferislab/NBLAST_on-the-fly/issues/52

**Comment by Robbie1977** [comment]
@dosumis @mmc46 @jefferis If you're all happy (http://vfbsandbox3.inf.ed.ac.uk) this can be pushed to go live?

**Comment by dosumis** [comment]
Looks good, but aren't the submenu options duplicates of the two options to the of NBLAST?

![image](https://cloud.githubusercontent.com/assets/112839/18965328/a91cd3f6-8674-11e6-81b7-bbafadaff4dd.png)

**Comment by Robbie1977** [comment]
Yep, was aiming to cover all user expectations

**Comment by mmc46** [comment]
That was my comment. I would remove the NBLAST submenu and have

Similar neurons (NBLAST)
Potential GAL4 matches (NBLAST)

or similar, to make clear it’s related to
 NBLAST.

**Comment by dosumis** [comment]
Agree.  Really great to see this BTW.  We should add a screenshot to the SAB report & put out an announcement on all channels when it's live.

**Comment by Robbie1977** [comment]
Functionally your happy though?

**Comment by dosumis** [comment]
Yep

**Comment by Robbie1977** [comment]
New version should be online on sandbox3 in 2 minutes

**Comment by Robbie1977** [comment]
will be live in the morning update
