### ISSUE TITLE
Term info not showing up

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#998]
Search on the main site homepage for 'superior medial protocerebrum'. It finds the term and the viee page starts loading. But the term info for it doesn't show. Just the placeholder text:

"Click anywhere on the stack viewer or use the Search or Anatomy menu tabs to select an anatomy term.

Information for the selected anatomical term will be displayed here, with further query options visible after selection."

The term shows up in the viewer menu. Clicking on it doesn't solve the problem.

Support info:
http://www.virtualflybrain.org/site/stacks/index.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:48.0) Gecko/20100101 Firefox/48.0 Size:[2029,1450]
!M56-0.1!e2eZ!e8e50!M1511,255,108!E!B Template!11!j1!F329!4e!L047055!4L!6228!4t!6synaptic neuropil domain!L2G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by dosumis** [comment]
Still broken!  I have tweeted an apology.  Note - sandbox3 is working fine.
